souffle: souffle::RAMIEqRelation Class Reference
souffle::RAMIEqRelation Class Reference
Interpreter Equivalence Relation.
#include <RAMIRelation.h>
Public Member Functions
std::vector< RamDomain * > extend (const RamDomain *tuple) override
Find the new knowledge generated by inserting a tuple.
void extend (const RAMIRelation &rel) override
Extend this relation with new knowledge generated by inserting all tuples from a relation.
void insert (const RamDomain *tuple) override
Insert tuple.
RAMIEqRelation (size_t relArity, const MinIndexSelection *orderSet, std::string relName)
Public Member Functions inherited from souffle::RAMIRelation
iterator begin () const
get iterator begin of relation
bool empty () const
Check whether relation is empty.
iterator end () const
get iterator begin of relation
bool exists (const RamDomain *tuple) const
check whether a tuple exists in the relation
size_t getArity () const
Get arity of relation.
std::vector< std::string > & getAttributeTypeQualifiers ()
Get AttributeType for the relation.
RAMIIndex * getIndex (const SearchSignature &col) const
get index for a given search signature.
RAMIIndex * getIndexByPos (int idx) const
get index for a given order.
size_t getLevel ()
const std::string & getName () const
std::string getName ()
SearchSignature getTotalIndexKey () const
Obtains a full index-key for this relation.
void insert (const RAMIRelation &other)
Merge another relation into this relation.
void purge ()
Purge table.
RAMIRelation (size_t relArity, const MinIndexSelection *orderSet, std::string relName)
RAMIRelation (const RAMIRelation &other)=delete
void setAttributes (const std::vector< std::string > attributeTypes)
Set AttributeType for the relation.
void setLevel (size_t level)
size_t size () const
Gets the number of contained tuples.
virtual ~RAMIRelation ()=default
Detailed Description
Interpreter Equivalence Relation.
Definition at line 285 of file RAMIRelation.h.
Constructor & Destructor Documentation
souffle::RAMIEqRelation::RAMIEqRelation (size_t relArity, const MinIndexSelection * orderSet, std::string relName) inline
Definition at line 287 of file RAMIRelation.h.
             : RAMIRelation(relArity, orderSet, relName) {}
Member Function Documentation
std::vector<RamDomain*> souffle::RAMIEqRelation::extend (const RamDomain * tuple) inline override virtual
Find the new knowledge generated by inserting a tuple.
Reimplemented from souffle::RAMIRelation.
Definition at line 311 of file RAMIRelation.h.
{
         std::vector<RamDomain*> newTuples;
         newTuples.push_back(new RamDomain[2]{tuple[0], tuple[0]});
         newTuples.push_back(new RamDomain[2]{tuple[0], tuple[1]});
         newTuples.push_back(new RamDomain[2]{tuple[1], tuple[0]});
         newTuples.push_back(new RamDomain[2]{tuple[1], tuple[1]});
         std::vector<const RamDomain*> relevantStored;
         for (const RamDomain* vals : *this) {
             if (vals[0] == tuple[0] || vals[0] == tuple[1] || vals[1] == tuple[0] || vals[1] == tuple[1]) {
                 relevantStored.push_back(vals);
             }
         }
         for (const auto vals : relevantStored) {
             newTuples.push_back(new RamDomain[2]{vals[0], tuple[0]});
             newTuples.push_back(new RamDomain[2]{vals[0], tuple[1]});
             newTuples.push_back(new RamDomain[2]{vals[1], tuple[0]});
             newTuples.push_back(new RamDomain[2]{vals[1], tuple[1]});
             newTuples.push_back(new RamDomain[2]{tuple[0], vals[0]});
             newTuples.push_back(new RamDomain[2]{tuple[0], vals[1]});
             newTuples.push_back(new RamDomain[2]{tuple[1], vals[0]});
             newTuples.push_back(new RamDomain[2]{tuple[1], vals[1]});
         }
         return newTuples;
     }
void souffle::RAMIEqRelation::extend (const RAMIRelation & rel) inline override virtual
Extend this relation with new knowledge generated by inserting all tuples from a relation.
Reimplemented from souffle::RAMIRelation.
Definition at line 340 of file RAMIRelation.h.
References souffle::RAMIRelation::extend(), and souffle::RAMIRelation::insert().
{
         std::vector<RamDomain*> newTuples;
         // store all values that will be implicitly relevant to the those that we will insert
         for (const auto* tuple : rel) {
             for (auto* newTuple : extend(tuple)) {
                 newTuples.push_back(newTuple);
             }
         }
         for (const auto* newTuple : newTuples) {
             RAMIRelation::insert(newTuple);
             delete[] newTuple;
         }
     }
void souffle::RAMIEqRelation::insert (const RamDomain * tuple) inline override virtual
Insert tuple.
Reimplemented from souffle::RAMIRelation.
Definition at line 291 of file RAMIRelation.h.
References souffle::RAMIRelation::extend(), and souffle::RAMIRelation::insert().
{
         // TODO: (pnappa) an eqrel check here is all that appears to be needed for implicit additions
         // TODO: future optimisation would require this as a member datatype
         // brave soul required to pass this quest
         // // specialisation for eqrel defs
         // std::unique_ptr<binaryrelation> eqreltuples;
         // in addition, it requires insert functions to insert into that, and functions
         // which allow reading of stored values must be changed to accommodate.
         // e.g. insert =>  eqRelTuples->insert(tuple[0], tuple[1]);
         // for now, we just have a naive & extremely slow version, otherwise known as a O(n^2) insertion
         // ):
         for (auto* newTuple : extend(tuple)) {
             RAMIRelation::insert(newTuple);
             delete[] newTuple;
         }
     }
The documentation for this class was generated from the following file:
RAMIRelation.h