souffle: souffle::LVMEqRelation Class Reference
souffle::LVMEqRelation Class Reference
Interpreter Equivalence Relation.
#include <LVMRelation.h>
Public Member Functions
std::vector< RamDomain * > extend (const TupleRef &tuple)
Find the new knowledge generated by inserting a tuple.
void extend (const LVMRelation &rel) override
Extend this relation with new knowledge generated by inserting all tuples from a relation.
bool insert (const TupleRef &tuple) override
Insert tuple.
LVMEqRelation (size_t arity, const std::string &relName, const std::vector< std::string > &attributeTypes, const MinIndexSelection &orderSet)
Public Member Functions inherited from souffle::LVMRelation
Iterator begin () const
bool contains (const TupleRef &tuple) const
Tests whether this relation contains the given tuple.
bool empty () const
Check if the relation is empty.
Iterator end () const
bool exists (const TupleRef &tuple) const
Check if a tuple exists in realtion.
size_t getArity () const
Return arity.
const std::vector< std::string > & getAttributeTypeQualifiers () const
Return the attribute types.
size_t getLevel () const
Return the level of the relation.
const std::string & getName () const
Return the relation name.
virtual bool insert (const RamDomain *tuple)
Add the given tuple to this relation.
void insert (const LVMRelation &other)
Add all entries of the given relation to this relation.
LVMRelation (std::size_t arity, const std::string &name, const std::vector< std::string > &attributeTypes, const MinIndexSelection &orderSet, IndexFactory factory=&createBTreeIndex)
Creates a relation, build all necessary indexes.
LVMRelation (LVMRelation &other)=delete
virtual void purge ()
Clear all indexes.
Stream range (const size_t &indexPos, const TupleRef &low, const TupleRef &high) const
Obtains a stream covering the interval between the two given entries.
void removeIndex (const size_t &indexPos)
Drops an index from the maintained indexes.
Stream scan () const
Obtains a stream to scan the entire relation.
void setLevel (size_t level)
Set level.
size_t size () const
Return number of tuples in relation (full-order)
void swap (LVMRelation &other)
Swaps the content of this and the given relation, including the installed indexes.
virtual ~LVMRelation ()=default
Additional Inherited Members
Protected Attributes inherited from souffle::LVMRelation
size_t arity
std::vector< std::string > attributeTypes
std::vector< std::unique_ptr< LVMIndex > > indexes
size_t level = 0
LVMIndex * main
std::string relName
Detailed Description
Interpreter Equivalence Relation.
Definition at line 198 of file LVMRelation.h.
Constructor & Destructor Documentation
souffle::LVMEqRelation::LVMEqRelation (size_t arity, const std::string & relName, const std::vector< std::string > & attributeTypes, const MinIndexSelection & orderSet)
Definition at line 121 of file LVMRelation.cpp.
         : LVMRelation(arity, name, attributeTypes, orderSet) {}
Member Function Documentation
std::vector< RamDomain * > souffle::LVMEqRelation::extend (const TupleRef & tuple)
Find the new knowledge generated by inserting a tuple.
Definition at line 145 of file LVMRelation.cpp.
References souffle::LVMRelation::scan().
Referenced by extend(), and insert().
{
     std::vector<RamDomain*> newTuples;
     newTuples.push_back(new RamDomain[2]{tuple[0], tuple[0]});
     newTuples.push_back(new RamDomain[2]{tuple[0], tuple[1]});
     newTuples.push_back(new RamDomain[2]{tuple[1], tuple[0]});
     newTuples.push_back(new RamDomain[2]{tuple[1], tuple[1]});
     std::vector<const RamDomain*> relevantStored;
     for (const TupleRef& vals : this->scan()) {
         if (vals[0] == tuple[0] || vals[0] == tuple[1] || vals[1] == tuple[0] || vals[1] == tuple[1]) {
             relevantStored.push_back(new RamDomain[2]{vals[0], vals[1]});
         }
     }
     for (auto& vals : relevantStored) {
         newTuples.push_back(new RamDomain[2]{vals[0], tuple[0]});
         newTuples.push_back(new RamDomain[2]{vals[0], tuple[1]});
         newTuples.push_back(new RamDomain[2]{vals[1], tuple[0]});
         newTuples.push_back(new RamDomain[2]{vals[1], tuple[1]});
         newTuples.push_back(new RamDomain[2]{tuple[0], vals[0]});
         newTuples.push_back(new RamDomain[2]{tuple[0], vals[1]});
         newTuples.push_back(new RamDomain[2]{tuple[1], vals[0]});
         newTuples.push_back(new RamDomain[2]{tuple[1], vals[1]});
         delete[] vals;
     }
     return newTuples;
 }
void souffle::LVMEqRelation::extend (const LVMRelation & rel) override virtual
Extend this relation with new knowledge generated by inserting all tuples from a relation.
Reimplemented from souffle::LVMRelation.
Definition at line 174 of file LVMRelation.cpp.
References souffle::LVMRelation::arity, extend(), souffle::LVMRelation::insert(), and souffle::LVMRelation::scan().
{
     std::vector<RamDomain*> newTuples;
     // store all values that will be implicitly relevant to the those that we will insert
     for (const auto& tuple : rel.scan()) {
         for (auto& newTuple : extend(tuple)) {
             newTuples.push_back(newTuple);
         }
     }
     for (const auto& newTuple : newTuples) {
         LVMRelation::insert(TupleRef(newTuple, arity));
         delete[] newTuple;
     }
 }
bool souffle::LVMEqRelation::insert (const TupleRef & tuple) override virtual
Insert tuple.
Reimplemented from souffle::LVMRelation.
Definition at line 125 of file LVMRelation.cpp.
References souffle::LVMRelation::arity, extend(), and souffle::LVMRelation::insert().
{
     // TODO: (pnappa) an eqrel check here is all that appears to be needed for implicit additions
     // TODO: future optimisation would require this as a member datatype
     // brave soul required to pass this quest
     // // specialisation for eqrel defs
     // std::unique_ptr<binaryrelation> eqreltuples;
     // in addition, it requires insert functions to insert into that, and functions
     // which allow reading of stored values must be changed to accommodate.
     // e.g. insert =>  eqRelTuples->insert(tuple[0], tuple[1]);
     // for now, we just have a naive & extremely slow version, otherwise known as a O(n^2) insertion
     // ):
     for (auto& newTuple : extend(tuple)) {
         LVMRelation::insert(TupleRef(newTuple, arity));
         delete[] newTuple;
     }
     return true;
 }
The documentation for this class was generated from the following files:
LVMRelation.h
LVMRelation.cpp