souffle: souffle::NullaryIndex Class Reference
souffle::NullaryIndex Class Reference
An index wrapper for nullary indexes.
Data Structures
class Source
Public Member Functions
void clear () override
Clears the content of this index, turning it empty.
bool contains (const TupleRef &tuple) const override
Tests whether the given tuple is present in this index or not.
bool empty () const override
Tests whether this index is empty or not.
size_t getArity () const override
Obtains the arity of the given index.
bool insert (const TupleRef &tuple) override
Inserts a tuple into this index.
void insert (const LVMIndex &src) override
Inserts all elements of the given index.
Stream range (const TupleRef &low, const TupleRef &high) const override
Returns a stream covering the elements.
Stream scan () const override
Returns a stream covering the entire index content.
std::size_t size () const override
Obtains the number of elements stored in this index.
Public Member Functions inherited from souffle::LVMIndex
virtual ~LVMIndex ()=default
Private Attributes
bool present
Detailed Description
An index wrapper for nullary indexes.
For those, no complex nested data structure is required.
Definition at line 84 of file LVMIndex.cpp.
Member Function Documentation
void souffle::NullaryIndex::clear () inline override virtual
Clears the content of this index, turning it empty.
Implements souffle::LVMIndex.
Definition at line 147 of file LVMIndex.cpp.
{
         present = false;
     }
bool souffle::NullaryIndex::contains (const TupleRef & tuple) const inline override virtual
Tests whether the given tuple is present in this index or not.
Implements souffle::LVMIndex.
Definition at line 134 of file LVMIndex.cpp.
References souffle::TupleRef::size().
{
         assert(tuple.size() == 0);
         return present;
     }
bool souffle::NullaryIndex::empty () const inline override virtual
Tests whether this index is empty or not.
Implements souffle::LVMIndex.
Definition at line 114 of file LVMIndex.cpp.
{
         return !present;
     }
size_t souffle::NullaryIndex::getArity () const inline override virtual
Obtains the arity of the given index.
Implements souffle::LVMIndex.
Definition at line 110 of file LVMIndex.cpp.
{
         return 0;
     }
bool souffle::NullaryIndex::insert (const TupleRef & tuple) inline override virtual
Inserts a tuple into this index.
Implements souffle::LVMIndex.
Definition at line 122 of file LVMIndex.cpp.
References souffle::TupleRef::size().
{
         assert(tuple.size() == 0);
         bool res = present;
         present = true;
         return res;
     }
void souffle::NullaryIndex::insert (const LVMIndex & src) inline override virtual
Inserts all elements of the given index.
Implements souffle::LVMIndex.
Definition at line 129 of file LVMIndex.cpp.
References souffle::LVMIndex::empty(), and souffle::LVMIndex::getArity().
{
         assert(src.getArity() == 0);
         present = present | !src.empty();
     }
Stream souffle::NullaryIndex::range (const TupleRef & low, const TupleRef & high) const inline override virtual
Returns a stream covering the elements.
Implements souffle::LVMIndex.
Definition at line 143 of file LVMIndex.cpp.
{
         return scan();
     }
Stream souffle::NullaryIndex::scan () const inline override virtual
Returns a stream covering the entire index content.
Implements souffle::LVMIndex.
Definition at line 139 of file LVMIndex.cpp.
{
         return std::make_unique<Source>(present);
     }
std::size_t souffle::NullaryIndex::size () const inline override virtual
Obtains the number of elements stored in this index.
Implements souffle::LVMIndex.
Definition at line 118 of file LVMIndex.cpp.
{
         return present ? 1 : 0;
     }
Field Documentation
bool souffle::NullaryIndex::present private
Definition at line 86 of file LVMIndex.cpp.
The documentation for this class was generated from the following file:
LVMIndex.cpp