souffle: souffle::LVMGenerator Class Reference
souffle::LVMGenerator Class Reference
LVMGenerator takes an RAM program and transfer it into an equivalent Bytecode representation.
#include <LVMGenerator.h>
Public Member Functions
virtual std::unique_ptr< LVMCode > getCodeStream ()
LVMGenerator (SymbolTable &symbolTable, const RamStatement &entry, RelationEncoder &relationEncoder)
The transformation is done in the constructor.
Protected Member Functions
void visitAggregate (const RamAggregate &aggregate, size_t exitAddress) override
void visitAutoIncrement (const RamAutoIncrement &inc, size_t exitAddress) override
void visitBreak (const RamBreak &breakOp, size_t exitAddress) override
void visitChoice (const RamChoice &choice, size_t exitAddress) override
void visitClear (const RamClear &clear, size_t exitAddress) override
void visitConjunction (const RamConjunction &conj, size_t exitAddress) override
void visitConstraint (const RamConstraint &relOp, size_t exitAddress) override
void visitCreate (const RamCreate &create, size_t exitAddress) override
void visitDebugInfo (const RamDebugInfo &dbg, size_t exitAddress) override
void visitDrop (const RamDrop &drop, size_t exitAddress) override
void visitEmptinessCheck (const RamEmptinessCheck &emptiness, size_t exitAddress) override
void visitExistenceCheck (const RamExistenceCheck &exists, size_t exitAddress) override
void visitExit (const RamExit &exit, size_t exitAddress) override
void visitFact (const RamFact &fact, size_t exitAddress) override
void visitFalse (const RamFalse &lfalse, size_t exitAddress) override
void visitFilter (const RamFilter &filter, size_t exitAddress) override
void visitIndexAggregate (const RamIndexAggregate &aggregate, size_t exitAddress) override
void visitIndexChoice (const RamIndexChoice &indexChoice, size_t exitAddress) override
void visitIndexScan (const RamIndexScan &scan, size_t exitAddress) override
void visitIntrinsicOperator (const RamIntrinsicOperator &op, size_t exitAddress) override
void visitLoad (const RamLoad &load, size_t exitAddress) override
void visitLogRelationTimer (const RamLogRelationTimer &timer, size_t exitAddress) override
void visitLogSize (const RamLogSize &size, size_t exitAddress) override
void visitLogTimer (const RamLogTimer &timer, size_t exitAddress) override
void visitLoop (const RamLoop &loop, size_t exitAddress) override
void visitMerge (const RamMerge &merge, size_t exitAddress) override
void visitNegation (const RamNegation &neg, size_t exitAddress) override
void visitNestedOperation (const RamNestedOperation &nested, size_t exitAddress) override
void visitNode (const RamNode &node, size_t exitAddress) override
void visitNumber (const RamNumber &num, size_t exitAddress) override
void visitPackRecord (const RamPackRecord &pack, size_t exitAddress) override
void visitParallel (const RamParallel &parallel, size_t exitAddress) override
void visitProject (const RamProject &project, size_t exitAddress) override
void visitProvenanceExistenceCheck (const RamProvenanceExistenceCheck &provExists, size_t exitAddress) override
void visitQuery (const RamQuery &insert, size_t exitAddress) override
void visitScan (const RamScan &scan, size_t exitAddress) override
void visitSequence (const RamSequence &seq, size_t exitAddress) override
Visit RAM stmt.
void visitStore (const RamStore &store, size_t exitAddress) override
void visitStratum (const RamStratum &stratum, size_t exitAddress) override
void visitSubroutineArgument (const RamSubroutineArgument &arg, size_t exitAddress) override
void visitSubroutineReturnValue (const RamSubroutineReturnValue &ret, size_t exitAddress) override
void visitSwap (const RamSwap &swap, size_t exitAddress) override
void visitTrue (const RamTrue &ltrue, size_t exitAddress) override
void visitTupleElement (const RamTupleElement &access, size_t exitAddress) override
void visitTupleOperation (const RamTupleOperation &search, size_t exitAddress) override
void visitUndefValue (const RamUndefValue &undef, size_t exitAddress) override
void visitUnpackRecord (const RamUnpackRecord &lookup, size_t exitAddress) override
void visitUserDefinedOperator (const RamUserDefinedOperator &op, size_t exitAddress) override
Protected Member Functions inherited from souffle::RamVisitor< void, size_t >
LINK (Create, RelationStatement)
LINK (Fact, RelationStatement)
LINK (Load, AbstractLoadStore)
LINK (Store, AbstractLoadStore)
LINK (AbstractLoadStore, RelationStatement)
LINK (Query, Statement)
LINK (Clear, RelationStatement)
LINK (Drop, RelationStatement)
LINK (LogSize, RelationStatement)
LINK (RelationStatement, Statement)
LINK (Merge, BinRelationStatement)
LINK (Swap, BinRelationStatement)
LINK (BinRelationStatement, Statement)
LINK (Sequence, ListStatement)
LINK (Loop, Statement)
LINK (Parallel, ListStatement)
LINK (ListStatement, Statement)
LINK (Exit, Statement)
LINK (LogTimer, Statement)
LINK (LogRelationTimer, Statement)
LINK (DebugInfo, Statement)
LINK (Stratum, Statement)
LINK (Statement, Node)
LINK (Project, Operation)
LINK (SubroutineReturnValue, Operation)
LINK (UnpackRecord, TupleOperation)
LINK (Scan, RelationOperation)
LINK (ParallelScan, Scan)
LINK (IndexScan, IndexOperation)
LINK (ParallelIndexScan, IndexScan)
LINK (Choice, RelationOperation)
LINK (ParallelChoice, Choice)
LINK (IndexChoice, IndexOperation)
LINK (ParallelIndexChoice, IndexChoice)
LINK (RelationOperation, TupleOperation)
LINK (Aggregate, RelationOperation)
LINK (IndexAggregate, IndexOperation)
LINK (IndexOperation, RelationOperation)
LINK (TupleOperation, NestedOperation)
LINK (Filter, AbstractConditional)
LINK (Break, AbstractConditional)
LINK (AbstractConditional, NestedOperation)
LINK (NestedOperation, Operation)
LINK (Operation, Node)
LINK (True, Condition)
LINK (False, Condition)
LINK (Conjunction, Condition)
LINK (Negation, Condition)
LINK (Constraint, Condition)
LINK (ExistenceCheck, AbstractExistenceCheck)
LINK (ProvenanceExistenceCheck, AbstractExistenceCheck)
LINK (EmptinessCheck, Condition)
LINK (AbstractExistenceCheck, Condition)
LINK (Condition, Node)
LINK (Number, Expression)
LINK (UndefValue, Expression)
LINK (TupleElement, Expression)
LINK (IntrinsicOperator, AbstractOperator)
LINK (UserDefinedOperator, AbstractOperator)
LINK (AbstractOperator, Expression)
LINK (AutoIncrement, Expression)
LINK (PackRecord, Expression)
LINK (SubroutineArgument, Expression)
LINK (Expression, Node)
LINK (Program, Node)
LINK (Relation, Node)
LINK (RelationReference, Node)
virtual void visitNode (const RamNode &, Params...)
The base case for all visitors – if no more specific overload was defined.
void operator() (const RamNode &node, Params...args)
The main entry for the user allowing visitors to be utilized as functions.
void operator() (const RamNode *node, Params...args)
The main entry for the user allowing visitors to be utilized as functions.
virtual void visit (const RamNode &node, Params...args)
The main entry for a visit process conducting the dispatching of a visit to the various sub-types of RamNodes.
virtual void visit (const RamNode *node, Params...args)
virtual ~RamVisitor ()=default
A virtual destructor.
Private Member Functions
void cleanUp ()
Clean up all the content except for addressMap This is for the double traverse when transforming from RAM -> LVM Bytecode.
void emitExistenceCheckInst (const size_t &arity, const size_t &relId, const size_t &indexPos, const std::vector< int > &typeMask)
Emit existence check instructions.
void emitRangeIndexInst (const size_t &arity, const size_t &relId, const size_t &indexPos, const size_t &counterLabel, const std::vector< int > &typeMask)
Emit range index instructions.
template<class RamNode >
size_t getIndexPos (RamNode &node)
Get the index position in a relation based on the SearchSignature.
size_t getNewAddressLabel ()
Get new Address Label.
size_t getNewIterator ()
Get new iterator.
size_t getNewTimer ()
Get new Timer.
size_t lookupAddress (size_t addressLabel)
void setAddress (size_t addressLabel, size_t value)
Set the value of address label.
Private Attributes
std::vector< size_t > addressMap
Address map.
std::unique_ptr< LVMCode > code
code stream
size_t currentAddressLabel = 0
Current address label.
size_t iteratorIndex = 0
Current iterator index.
RelationEncoder & relationEncoder
Relation Encoder.
SymbolTable & symbolTable
Symbol table.
size_t timerIndex = 0
Current timer index for logger.
Detailed Description
LVMGenerator takes an RAM program and transfer it into an equivalent Bytecode representation.
Definition at line 110 of file LVMGenerator.h.
Constructor & Destructor Documentation
souffle::LVMGenerator::LVMGenerator (SymbolTable & symbolTable, const RamStatement & entry, RelationEncoder & relationEncoder) inline
The transformation is done in the constructor.
This is done by traversing the tree twice, in order to find the necessary information (Jump destination) for LVM branch operations.
Definition at line 117 of file LVMGenerator.h.
References souffle::LVM_STOP.
             : symbolTable(symbolTable), code(new LVMCode(symbolTable)), relationEncoder(relationEncoder) {
         (*this)(entry, 0);
         (*this).cleanUp();
         (*this)(entry, 0);
         code->push_back(LVM_STOP);
     }
Member Function Documentation
void souffle::LVMGenerator::cleanUp () inline private
Clean up all the content except for addressMap This is for the double traverse when transforming from RAM -> LVM Bytecode.
Definition at line 1132 of file LVMGenerator.h.
                    {
         code->clear();
         code->getIODirectives().clear();
         currentAddressLabel = 0;
         iteratorIndex = 0;
         timerIndex = 0;
     }
void souffle::LVMGenerator::emitExistenceCheckInst (const size_t & arity, const size_t & relId, const size_t & indexPos, const std::vector< int > & typeMask) inline private
Emit existence check instructions.
Definition at line 1187 of file LVMGenerator.h.
References i, j, souffle::LVM_ExistenceCheck, souffle::LVM_ExistenceCheckOneArg, RAM_DOMAIN_SIZE, and types.
{
         size_t numOfTypeMasks = arity / RAM_DOMAIN_SIZE + (arity % RAM_DOMAIN_SIZE != 0);
         // Emit special instruction for relation with arity < RAM_DOMAIN_SIZE
         // to avoid overhead of checking argument size --- as it is the most common case
         // TODO (xiaowen): benchmark suggest no noticeable difference whether we add
         // this optimization or not.
         if (numOfTypeMasks == 1) {
             code->push_back(LVM_ExistenceCheckOneArg);
         } else {
             code->push_back(LVM_ExistenceCheck);
         }
         code->push_back(relId);
         code->push_back(indexPos);
         for (size_t i = 0; i < numOfTypeMasks; ++i) {
             RamDomain types = 0;
             for (size_t j = 0; j < RAM_DOMAIN_SIZE; ++j) {
                 auto projectedIndex = i * RAM_DOMAIN_SIZE + j;
                 if (projectedIndex >= arity) {
                     break;
                 }
                 types |= (typeMask[projectedIndex] << j);
             }
             code->push_back(types);
         }
     }
void souffle::LVMGenerator::emitRangeIndexInst (const size_t & arity, const size_t & relId, const size_t & indexPos, const size_t & counterLabel, const std::vector< int > & typeMask) inline private
Emit range index instructions.
Definition at line 1215 of file LVMGenerator.h.
References i, j, souffle::LVM_ITER_InitRangeIndex, souffle::LVM_ITER_InitRangeIndexOneArg, RAM_DOMAIN_SIZE, and types.
{
         size_t numOfTypeMasks = arity / RAM_DOMAIN_SIZE + (arity % RAM_DOMAIN_SIZE != 0);
         // Emit special instruction for relation with arity < RAM_DOMAIN_SIZE
         // to avoid overhead of checking argumnet size --- as it is the most common case
         // TODO (xiaowen): benchmark suggest no noticeable difference whether we add
         // this optimization or not.
         if (numOfTypeMasks == 1) {
             code->push_back(LVM_ITER_InitRangeIndexOneArg);
         } else {
             code->push_back(LVM_ITER_InitRangeIndex);
         }
         code->push_back(counterLabel);
         code->push_back(relId);
         code->push_back(indexPos);
         for (size_t i = 0; i < numOfTypeMasks; ++i) {
             RamDomain types = 0;
             for (size_t j = 0; j < RAM_DOMAIN_SIZE; ++j) {
                 auto projectedIndex = i * RAM_DOMAIN_SIZE + j;
                 if (projectedIndex >= arity) {
                     break;
                 }
                 types |= (typeMask[projectedIndex] << j);
             }
             code->push_back(types);
         }
     }
virtual std::unique_ptr<LVMCode> souffle::LVMGenerator::getCodeStream () inline virtual
Definition at line 125 of file LVMGenerator.h.
{
         return std::move(this->code);
     }
template<class RamNode > size_t souffle::LVMGenerator::getIndexPos (RamNode & node) inline private
Get the index position in a relation based on the SearchSignature.
Definition at line 1175 of file LVMGenerator.h.
References souffle::RamIndexAnalysis::getIndexes(), souffle::MinIndexSelection::getLexOrderNum(), souffle::RamIndexAnalysis::getSearchSignature(), i, and souffle::RelationEncoder::isa.
{
         const MinIndexSelection& orderSet = relationEncoder.isa->getIndexes(node.getRelation());
         SearchSignature signature = relationEncoder.isa->getSearchSignature(&node);
         // A zero signature is equivalent as a full order signature.
         if (signature == 0) {
             signature = (1 << node.getRelation().getArity()) - 1;
         }
         auto i = orderSet.getLexOrderNum(signature);
         return i;
     };
size_t souffle::LVMGenerator::getNewAddressLabel () inline private
Get new Address Label.
Definition at line 1141 of file LVMGenerator.h.
{
         return currentAddressLabel++;
     }
size_t souffle::LVMGenerator::getNewIterator () inline private
Get new iterator.
Definition at line 1146 of file LVMGenerator.h.
{
         return iteratorIndex++;
     }
size_t souffle::LVMGenerator::getNewTimer () inline private
Get new Timer.
Definition at line 1151 of file LVMGenerator.h.
{
         return timerIndex++;
     }
size_t souffle::LVMGenerator::lookupAddress (size_t addressLabel) inline private
Definition at line 1158 of file LVMGenerator.h.
{
         if (addressLabel < addressMap.size()) {
             return addressMap[addressLabel];
         }
         return 0;
     }
void souffle::LVMGenerator::setAddress (size_t addressLabel, size_t value) inline private
Set the value of address label.
Definition at line 1166 of file LVMGenerator.h.
{
         if (addressLabel >= addressMap.size()) {
             addressMap.resize((addressLabel + 1));
         }
         addressMap[addressLabel] = value;
     }
void souffle::LVMGenerator::visitAggregate (const RamAggregate & aggregate, size_t exitAddress) inline override protected
Definition at line 636 of file LVMGenerator.h.
References souffle::COUNT, souffle::RamAbstractAggregate::getCondition(), souffle::RamAbstractAggregate::getExpression(), souffle::RamAbstractAggregate::getFunction(), souffle::RamRelationOperation::getRelation(), souffle::RamTupleOperation::getTupleId(), souffle::LVM_Aggregate, souffle::LVM_Aggregate_COUNT, souffle::LVM_Aggregate_Return, souffle::LVM_Goto, souffle::LVM_ITER_Inc, souffle::LVM_ITER_InitFullIndex, souffle::LVM_ITER_NotAtEnd, souffle::LVM_ITER_Select, souffle::LVM_Jmpez, souffle::LVM_Jmpnz, souffle::LVM_Number, souffle::LVM_OP_ADD, souffle::LVM_OP_EQ, souffle::LVM_OP_MAX, souffle::LVM_OP_MIN, souffle::LVM_TupleElement, souffle::MAX, MAX_RAM_DOMAIN, souffle::MIN, MIN_RAM_DOMAIN, and souffle::SUM.
{
         code->push_back(LVM_Aggregate);
         size_t counterLabel = getNewIterator();
         size_t L1 = getNewAddressLabel();
         size_t L2 = getNewAddressLabel();
         // Init the Iterator
         code->push_back(LVM_ITER_InitFullIndex);
         code->push_back(counterLabel);
         code->push_back(relationEncoder.encodeRelation(aggregate.getRelation()));
         // TODO (xiaowen/#992): Count -> Size for optimization
         if (aggregate.getFunction() == souffle::COUNT &&
                 dynamic_cast<const RamTrue*>(&aggregate.getCondition()) != nullptr) {
             code->push_back(LVM_Aggregate_COUNT);
             code->push_back(counterLabel);
         } else {
             // Init value
             switch (aggregate.getFunction()) {
                 case souffle::MIN:
                     code->push_back(LVM_Number);
                     code->push_back(MAX_RAM_DOMAIN);
                     break;
                 case souffle::MAX:
                     code->push_back(LVM_Number);
                     code->push_back(MIN_RAM_DOMAIN);
                     break;
                 case souffle::COUNT:
                     code->push_back(LVM_Number);
                     code->push_back(0);
                     break;
                 case souffle::SUM:
                     code->push_back(LVM_Number);
                     code->push_back(0);
                     break;
             }
             size_t address_L0 = code->size();
             // Start the aggregate for loop
             code->push_back(LVM_ITER_NotAtEnd);
             code->push_back(counterLabel);
             code->push_back(LVM_Jmpez);
             code->push_back(lookupAddress(L1));
             // Select the element pointed by iter
             code->push_back(LVM_ITER_Select);
             code->push_back(counterLabel);
             code->push_back(aggregate.getTupleId());
             // Produce condition inside the loop
             size_t endOfLoop = getNewAddressLabel();
             if (dynamic_cast<const RamTrue*>(&aggregate.getCondition()) == nullptr) {
                 visit(aggregate.getCondition(), exitAddress);
                 code->push_back(LVM_Jmpez);  // Continue; if condition is not met
                 code->push_back(lookupAddress(endOfLoop));
             }
             if (aggregate.getFunction() != souffle::COUNT) {
                 visit(aggregate.getExpression(), exitAddress);
             }
             switch (aggregate.getFunction()) {
                 case souffle::MIN:
                     code->push_back(LVM_OP_MIN);
                     code->push_back(2);
                     break;
                 case souffle::MAX:
                     code->push_back(LVM_OP_MAX);
                     code->push_back(2);
                     break;
                 case souffle::COUNT:
                     code->push_back(LVM_Number);
                     code->push_back(1);
                     code->push_back(LVM_OP_ADD);
                     break;
                 case souffle::SUM:
                     code->push_back(LVM_OP_ADD);
                     break;
             }
             setAddress(endOfLoop, code->size());
             code->push_back(LVM_ITER_Inc);
             code->push_back(counterLabel);
             code->push_back(LVM_Goto);
             code->push_back(address_L0);
         }
         setAddress(L1, code->size());
         // write result into environment tuple
         code->push_back(LVM_Aggregate_Return);
         code->push_back(aggregate.getTupleId());
         if (aggregate.getFunction() == souffle::MIN || aggregate.getFunction() == souffle::MAX) {
             // check whether there exists a min/max first before next loop
             // Retrieve the result we just saved.
             code->push_back(LVM_TupleElement);
             code->push_back(aggregate.getTupleId());
             code->push_back(0);
             code->push_back(LVM_Number);
             code->push_back(aggregate.getFunction() == souffle::MIN ? MAX_RAM_DOMAIN : MIN_RAM_DOMAIN);
             code->push_back(LVM_OP_EQ);
             code->push_back(LVM_Jmpnz);  // If init == result, does not visit nested search
             code->push_back(lookupAddress(L2));
         }
         visitTupleOperation(aggregate, exitAddress);
         setAddress(L2, code->size());
     }
void souffle::LVMGenerator::visitAutoIncrement (const RamAutoIncrement & inc, size_t exitAddress) inline override protected
Definition at line 143 of file LVMGenerator.h.
References souffle::LVM_AutoIncrement.
{
         code->push_back(LVM_AutoIncrement);
     }
void souffle::LVMGenerator::visitBreak (const RamBreak & breakOp, size_t exitAddress) inline override protected
Definition at line 875 of file LVMGenerator.h.
References souffle::RamAbstractConditional::getCondition(), and souffle::LVM_Jmpnz.
{
         visit(breakOp.getCondition(), exitAddress);
         code->push_back(LVM_Jmpnz);
         code->push_back(exitAddress);
         visitNestedOperation(breakOp, exitAddress);
     }
void souffle::LVMGenerator::visitChoice (const RamChoice & choice, size_t exitAddress) inline override protected
Definition at line 475 of file LVMGenerator.h.
References souffle::RamAbstractChoice::getCondition(), souffle::RamRelationOperation::getRelation(), souffle::RamTupleOperation::getTupleId(), souffle::LVM_Choice, souffle::LVM_Goto, souffle::LVM_ITER_Inc, souffle::LVM_ITER_InitFullIndex, souffle::LVM_ITER_NotAtEnd, souffle::LVM_ITER_Select, souffle::LVM_Jmpez, and souffle::LVM_Jmpnz.
{
         code->push_back(LVM_Choice);
         size_t counterLabel = getNewIterator();
         size_t L1 = getNewAddressLabel();
         size_t L2 = getNewAddressLabel();
         // Init the Iterator
         code->push_back(LVM_ITER_InitFullIndex);
         code->push_back(counterLabel);
         code->push_back(relationEncoder.encodeRelation(choice.getRelation()));
         // While iterator is not at end
         size_t address_L0 = code->size();
         code->push_back(LVM_ITER_NotAtEnd);
         code->push_back(counterLabel);
         code->push_back(LVM_Jmpez);
         code->push_back(lookupAddress(L2));
         // Select the tuple pointed by iter
         code->push_back(LVM_ITER_Select);
         code->push_back(counterLabel);
         code->push_back(choice.getTupleId());
         // If condition is met, perform nested operation and exit.
         visit(choice.getCondition(), exitAddress);
         code->push_back(LVM_Jmpnz);
         code->push_back(lookupAddress(L1));
         // Else increment the iter and jump to the start of the while loop.
         code->push_back(LVM_ITER_Inc);
         code->push_back(counterLabel);
         code->push_back(LVM_Goto);
         code->push_back(address_L0);
         setAddress(L1, code->size());
         visitTupleOperation(choice, exitAddress);
         setAddress(L2, code->size());
     }
void souffle::LVMGenerator::visitClear (const RamClear & clear, size_t exitAddress) inline override protected
Definition at line 1033 of file LVMGenerator.h.
References souffle::RamRelationStatement::getRelation(), and souffle::LVM_Clear.
{
         code->push_back(LVM_Clear);
         code->push_back(relationEncoder.encodeRelation(clear.getRelation()));
     }
void souffle::LVMGenerator::visitConjunction (const RamConjunction & conj, size_t exitAddress) inline override protected
Definition at line 307 of file LVMGenerator.h.
References souffle::RamConjunction::getLHS(), souffle::RamConjunction::getRHS(), and souffle::LVM_Conjunction.
{
         visit(conj.getLHS(), exitAddress);
         visit(conj.getRHS(), exitAddress);
         code->push_back(LVM_Conjunction);
     }
void souffle::LVMGenerator::visitConstraint (const RamConstraint & relOp, size_t exitAddress) inline override protected
Definition at line 383 of file LVMGenerator.h.
References souffle::CONTAINS, souffle::EQ, souffle::GE, souffle::RamConstraint::getLHS(), souffle::RamConstraint::getOperator(), souffle::RamConstraint::getRHS(), souffle::GT, souffle::LE, souffle::LT, souffle::LVM_Constraint, souffle::LVM_OP_CONTAINS, souffle::LVM_OP_EQ, souffle::LVM_OP_GE, souffle::LVM_OP_GT, souffle::LVM_OP_LE, souffle::LVM_OP_LT, souffle::LVM_OP_MATCH, souffle::LVM_OP_NE, souffle::LVM_OP_NOT_CONTAINS, souffle::LVM_OP_NOT_MATCH, souffle::MATCH, souffle::NE, souffle::NOT_CONTAINS, and souffle::NOT_MATCH.
{
         code->push_back(LVM_Constraint);
         visit(relOp.getLHS(), exitAddress);
         visit(relOp.getRHS(), exitAddress);
         switch (relOp.getOperator()) {
             case BinaryConstraintOp::EQ:
                 code->push_back(LVM_OP_EQ);
                 break;
             case BinaryConstraintOp::NE:
                 code->push_back(LVM_OP_NE);
                 break;
             case BinaryConstraintOp::LT:
                 code->push_back(LVM_OP_LT);
                 break;
             case BinaryConstraintOp::LE:
                 code->push_back(LVM_OP_LE);
                 break;
             case BinaryConstraintOp::GT:
                 code->push_back(LVM_OP_GT);
                 break;
             case BinaryConstraintOp::GE:
                 code->push_back(LVM_OP_GE);
                 break;
             case BinaryConstraintOp::MATCH:
                 code->push_back(LVM_OP_MATCH);
                 break;
             case BinaryConstraintOp::NOT_MATCH:
                 code->push_back(LVM_OP_NOT_MATCH);
                 break;
             case BinaryConstraintOp::CONTAINS:
                 code->push_back(LVM_OP_CONTAINS);
                 break;
             case BinaryConstraintOp::NOT_CONTAINS:
                 code->push_back(LVM_OP_NOT_CONTAINS);
                 break;
             default:
                 assert(false && "unsupported operator");
         }
     }
void souffle::LVMGenerator::visitCreate (const RamCreate & create, size_t exitAddress) inline override protected
Definition at line 1028 of file LVMGenerator.h.
References souffle::RamRelationStatement::getRelation(), and souffle::LVM_Create.
{
         code->push_back(LVM_Create);
         code->push_back(relationEncoder.encodeRelation(create.getRelation()));
     }
void souffle::LVMGenerator::visitDebugInfo (const RamDebugInfo & dbg, size_t exitAddress) inline override protected
Definition at line 1017 of file LVMGenerator.h.
References souffle::RamAbstractLog::getMessage(), souffle::RamAbstractLog::getStatement(), and souffle::LVM_DebugInfo.
{
         code->push_back(LVM_DebugInfo);
         code->push_back(symbolTable.lookup(dbg.getMessage()));
         visit(dbg.getStatement(), exitAddress);
     }
void souffle::LVMGenerator::visitDrop (const RamDrop & drop, size_t exitAddress) inline override protected
Definition at line 1038 of file LVMGenerator.h.
References souffle::RamRelationStatement::getRelation(), and souffle::LVM_Drop.
{
         code->push_back(LVM_Drop);
         code->push_back(relationEncoder.encodeRelation(drop.getRelation()));
     }
void souffle::LVMGenerator::visitEmptinessCheck (const RamEmptinessCheck & emptiness, size_t exitAddress) inline override protected
Definition at line 318 of file LVMGenerator.h.
References souffle::RamEmptinessCheck::getRelation(), and souffle::LVM_EmptinessCheck.
{
         code->push_back(LVM_EmptinessCheck);
         code->push_back(relationEncoder.encodeRelation(emptiness.getRelation()));
     }
void souffle::LVMGenerator::visitExistenceCheck (const RamExistenceCheck & exists, size_t exitAddress) inline override protected
Definition at line 323 of file LVMGenerator.h.
References arity, souffle::RamRelation::getArity(), souffle::RamAbstractExistenceCheck::getRelation(), souffle::RamAbstractExistenceCheck::getValues(), i, souffle::isRamUndefValue(), souffle::LVM_ContainCheck, souffle::LVM_EmptinessCheck, and souffle::LVM_Negation.
{
         auto values = exists.getValues();
         auto arity = exists.getRelation().getArity();
         auto relId = relationEncoder.encodeRelation(exists.getRelation());
         std::vector<int> typeMask(arity);
         bool emptinessCheck = true;
         bool fullExistenceCheck = true;
         for (size_t i = arity; i-- > 0;) {
             if (!isRamUndefValue(values[i])) {
                 visit(values[i], exitAddress);
                 emptinessCheck = false;
                 typeMask[i] = 1;
             } else {
                 fullExistenceCheck = false;
             }
         }
         // Empty type mask is equivalent to a non-emptiness check
         if (emptinessCheck == true) {
             code->push_back(LVM_EmptinessCheck);
             code->push_back(relId);
             code->push_back(LVM_Negation);
         } else if (fullExistenceCheck == true) {
             // Full type mask is equivalent to a full order existence check
             code->push_back(LVM_ContainCheck);
             code->push_back(relId);
         } else {  // Otherwise we do a partial existence check.
             size_t indexPos = getIndexPos(exists);
             this->emitExistenceCheckInst(arity, relId, indexPos, typeMask);
         }
     }
void souffle::LVMGenerator::visitExit (const RamExit & exit, size_t exitAddress) inline override protected
Definition at line 990 of file LVMGenerator.h.
References souffle::RamExit::getCondition(), and souffle::LVM_Jmpnz.
{
         visit(exit.getCondition(), exitAddress);
         code->push_back(LVM_Jmpnz);
         code->push_back(exitAddress);
     }
void souffle::LVMGenerator::visitFact (const RamFact & fact, size_t exitAddress) inline override protected
Definition at line 1065 of file LVMGenerator.h.
References arity, souffle::RamRelation::getArity(), souffle::RamRelation::getName(), souffle::RamRelationStatement::getRelation(), souffle::RamFact::getValues(), i, and souffle::LVM_Fact.
{
         size_t arity = fact.getRelation().getArity();
         auto values = fact.getValues();
         for (size_t i = arity; i-- > 0;) {
             visit(values[i], exitAddress);  // Values cannot be null here
         }
         std::string targertRelation = fact.getRelation().getName();
         code->push_back(LVM_Fact);
         code->push_back(relationEncoder.encodeRelation(fact.getRelation()));
         code->push_back(arity);
     }
void souffle::LVMGenerator::visitFalse (const RamFalse & lfalse, size_t exitAddress) inline override protected
Definition at line 303 of file LVMGenerator.h.
References souffle::LVM_False.
{
         code->push_back(LVM_False);
     }
void souffle::LVMGenerator::visitFilter (const RamFilter & filter, size_t exitAddress) inline override protected
Definition at line 882 of file LVMGenerator.h.
References souffle::RamAbstractConditional::getCondition(), souffle::RamNestedOperation::getProfileText(), souffle::LVM_Filter, and souffle::LVM_Jmpez.
{
         code->push_back(LVM_Filter);
         // Profile Action
         code->push_back(symbolTable.lookup(filter.getProfileText()));
         size_t L0 = getNewAddressLabel();
         visit(filter.getCondition(), exitAddress);
         code->push_back(LVM_Jmpez);
         code->push_back(lookupAddress(L0));
         visitNestedOperation(filter, exitAddress);
         setAddress(L0, code->size());
     }
void souffle::LVMGenerator::visitIndexAggregate (const RamIndexAggregate & aggregate, size_t exitAddress) inline override protected
Definition at line 747 of file LVMGenerator.h.
References arity, souffle::COUNT, souffle::RamRelation::getArity(), souffle::RamAbstractAggregate::getCondition(), souffle::RamAbstractAggregate::getExpression(), souffle::RamAbstractAggregate::getFunction(), souffle::RamIndexOperation::getRangePattern(), souffle::RamRelationOperation::getRelation(), souffle::RamTupleOperation::getTupleId(), i, souffle::isRamUndefValue(), souffle::LVM_Aggregate_COUNT, souffle::LVM_Aggregate_Return, souffle::LVM_Goto, souffle::LVM_IndexAggregate, souffle::LVM_ITER_Inc, souffle::LVM_ITER_InitFullIndex, souffle::LVM_ITER_NotAtEnd, souffle::LVM_ITER_Select, souffle::LVM_Jmpez, souffle::LVM_Jmpnz, souffle::LVM_Number, souffle::LVM_OP_ADD, souffle::LVM_OP_EQ, souffle::LVM_OP_MAX, souffle::LVM_OP_MIN, souffle::LVM_TupleElement, souffle::MAX, MAX_RAM_DOMAIN, souffle::MIN, MIN_RAM_DOMAIN, and souffle::SUM.
{
         code->push_back(LVM_IndexAggregate);
         size_t counterLabel = getNewIterator();
         size_t L1 = getNewAddressLabel();
         size_t L2 = getNewAddressLabel();
         // Obtain the pattern for index
         auto patterns = aggregate.getRangePattern();
         auto arity = aggregate.getRelation().getArity();
         auto relId = relationEncoder.encodeRelation(aggregate.getRelation());
         std::vector<int> typeMask(arity);
         bool fullIndexSearch = true;
         for (size_t i = arity; i-- > 0;) {
             if (!isRamUndefValue(patterns[i])) {
                 visit(patterns[i], exitAddress);
                 fullIndexSearch = false;
                 typeMask[i] = 1;
             }
         }
         // Init range index based on pattern
         if (fullIndexSearch == true) {
             code->push_back(LVM_ITER_InitFullIndex);
             code->push_back(counterLabel);
             code->push_back(relId);
         } else {
             auto indexPos = getIndexPos(aggregate);
             this->emitRangeIndexInst(arity, relId, indexPos, counterLabel, typeMask);
         }
         if (aggregate.getFunction() == souffle::COUNT &&
                 dynamic_cast<const RamTrue*>(&aggregate.getCondition()) != nullptr) {
             code->push_back(LVM_Aggregate_COUNT);
             code->push_back(counterLabel);
         } else {
             // Init value
             switch (aggregate.getFunction()) {
                 case souffle::MIN:
                     code->push_back(LVM_Number);
                     code->push_back(MAX_RAM_DOMAIN);
                     break;
                 case souffle::MAX:
                     code->push_back(LVM_Number);
                     code->push_back(MIN_RAM_DOMAIN);
                     break;
                 case souffle::COUNT:
                     code->push_back(LVM_Number);
                     code->push_back(0);
                     break;
                 case souffle::SUM:
                     code->push_back(LVM_Number);
                     code->push_back(0);
                     break;
             }
             size_t address_L0 = code->size();
             // Start the aggregate for loop
             code->push_back(LVM_ITER_NotAtEnd);
             code->push_back(counterLabel);
             code->push_back(LVM_Jmpez);
             code->push_back(lookupAddress(L1));
             code->push_back(LVM_ITER_Select);
             code->push_back(counterLabel);
             code->push_back(aggregate.getTupleId());
             // Produce condition inside the loop
             size_t endOfLoop = getNewAddressLabel();
             if (dynamic_cast<const RamTrue*>(&aggregate.getCondition()) == nullptr) {
                 visit(aggregate.getCondition(), exitAddress);
                 code->push_back(LVM_Jmpez);  // Continue; if condition is not met
                 code->push_back(lookupAddress(endOfLoop));
             }
             if (aggregate.getFunction() != souffle::COUNT) {
                 visit(aggregate.getExpression(), exitAddress);
             }
             switch (aggregate.getFunction()) {
                 case souffle::MIN:
                     code->push_back(LVM_OP_MIN);
                     code->push_back(2);
                     break;
                 case souffle::MAX:
                     code->push_back(LVM_OP_MAX);
                     code->push_back(2);
                     break;
                 case souffle::COUNT:
                     code->push_back(LVM_Number);
                     code->push_back(1);
                     code->push_back(LVM_OP_ADD);
                     break;
                 case souffle::SUM:
                     code->push_back(LVM_OP_ADD);
                     break;
             }
             setAddress(endOfLoop, code->size());
             code->push_back(LVM_ITER_Inc);
             code->push_back(counterLabel);
             code->push_back(LVM_Goto);
             code->push_back(address_L0);
         }
         setAddress(L1, code->size());
         // write result into environment tuple
         code->push_back(LVM_Aggregate_Return);
         code->push_back(aggregate.getTupleId());
         if (aggregate.getFunction() == souffle::MIN || aggregate.getFunction() == souffle::MAX) {
             // check whether there exists a min/max first before next loop
             // Retrieve the result we just saved.
             code->push_back(LVM_TupleElement);
             code->push_back(aggregate.getTupleId());
             code->push_back(0);
             code->push_back(LVM_Number);
             code->push_back(aggregate.getFunction() == souffle::MIN ? MAX_RAM_DOMAIN : MIN_RAM_DOMAIN);
             code->push_back(LVM_OP_EQ);
             code->push_back(LVM_Jmpnz);  // If init == result, does not visit nested search
             code->push_back(lookupAddress(L2));
         }
         visitTupleOperation(aggregate, exitAddress);
         setAddress(L2, code->size());
     }
void souffle::LVMGenerator::visitIndexChoice (const RamIndexChoice & indexChoice, size_t exitAddress) inline override protected
Definition at line 565 of file LVMGenerator.h.
References arity, souffle::RamRelation::getArity(), souffle::RamAbstractChoice::getCondition(), souffle::RamIndexOperation::getRangePattern(), souffle::RamRelationOperation::getRelation(), souffle::RamTupleOperation::getTupleId(), i, souffle::isRamUndefValue(), souffle::LVM_Goto, souffle::LVM_IndexChoice, souffle::LVM_ITER_Inc, souffle::LVM_ITER_InitFullIndex, souffle::LVM_ITER_NotAtEnd, souffle::LVM_ITER_Select, souffle::LVM_Jmpez, and souffle::LVM_Jmpnz.
{
         code->push_back(LVM_IndexChoice);
         size_t counterLabel = getNewIterator();
         size_t L1 = getNewAddressLabel();
         size_t L2 = getNewAddressLabel();
         // Obtain the pattern for index
         auto patterns = indexChoice.getRangePattern();
         auto arity = indexChoice.getRelation().getArity();
         auto relId = relationEncoder.encodeRelation(indexChoice.getRelation());
         std::vector<int> typeMask(arity);
         bool fullIndexSearch = true;
         for (size_t i = arity; i-- > 0;) {
             if (!isRamUndefValue(patterns[i])) {
                 visit(patterns[i], exitAddress);
                 fullIndexSearch = false;
                 typeMask[i] = 1;
             }
         }
         // Init range index based on pattern
         if (fullIndexSearch == true) {
             code->push_back(LVM_ITER_InitFullIndex);
             code->push_back(counterLabel);
             code->push_back(relId);
         } else {
             auto indexPos = getIndexPos(indexChoice);
             this->emitRangeIndexInst(arity, relId, indexPos, counterLabel, typeMask);
         }
         // While iter is not at end.
         size_t address_L0 = code->size();
         code->push_back(LVM_ITER_NotAtEnd);
         code->push_back(counterLabel);
         code->push_back(LVM_Jmpez);
         code->push_back(lookupAddress(L2));
         // Select the tuple pointed by iter
         code->push_back(LVM_ITER_Select);
         code->push_back(counterLabel);
         code->push_back(indexChoice.getTupleId());
         visit(indexChoice.getCondition(), exitAddress);
         // If condition is true, perform nested operation and return.
         code->push_back(LVM_Jmpnz);
         code->push_back(lookupAddress(L1));
         // Else increment the iter and continue
         code->push_back(LVM_ITER_Inc);
         code->push_back(counterLabel);
         code->push_back(LVM_Goto);
         code->push_back(address_L0);
         setAddress(L1, code->size());
         visitTupleOperation(indexChoice, exitAddress);
         setAddress(L2, code->size());
     }
void souffle::LVMGenerator::visitIndexScan (const RamIndexScan & scan, size_t exitAddress) inline override protected
Definition at line 514 of file LVMGenerator.h.
References arity, souffle::RamRelation::getArity(), souffle::RamIndexOperation::getRangePattern(), souffle::RamRelationOperation::getRelation(), souffle::RamTupleOperation::getTupleId(), i, souffle::isRamUndefValue(), souffle::LVM_Goto, souffle::LVM_IndexScan, souffle::LVM_ITER_Inc, souffle::LVM_ITER_InitFullIndex, souffle::LVM_ITER_NotAtEnd, souffle::LVM_ITER_Select, and souffle::LVM_Jmpez.
{
         code->push_back(LVM_IndexScan);
         size_t counterLabel = getNewIterator();
         size_t L1 = getNewAddressLabel();
         // Obtain the pattern for index
         auto patterns = scan.getRangePattern();
         auto arity = scan.getRelation().getArity();
         auto relId = relationEncoder.encodeRelation(scan.getRelation());
         std::vector<int> typeMask(arity);
         bool fullIndexSearch = true;
         for (size_t i = arity; i-- > 0;) {
             if (!isRamUndefValue(patterns[i])) {
                 visit(patterns[i], exitAddress);
                 fullIndexSearch = false;
                 typeMask[i] = 1;
             }
         }
         // Init range index based on pattern
         if (fullIndexSearch == true) {
             code->push_back(LVM_ITER_InitFullIndex);
             code->push_back(counterLabel);
             code->push_back(relId);
         } else {
             auto indexPos = getIndexPos(scan);
             this->emitRangeIndexInst(arity, relId, indexPos, counterLabel, typeMask);
         }
         // While iter is not at end
         size_t address_L0 = code->size();
         code->push_back(LVM_ITER_NotAtEnd);
         code->push_back(counterLabel);
         code->push_back(LVM_Jmpez);
         code->push_back(lookupAddress(L1));
         // Select the tuple pointed by the iter
         code->push_back(LVM_ITER_Select);
         code->push_back(counterLabel);
         code->push_back(scan.getTupleId());
         // Increment the iter and jump to the start of while loop.
         visitTupleOperation(scan, lookupAddress(L1));
         code->push_back(LVM_ITER_Inc);
         code->push_back(counterLabel);
         code->push_back(LVM_Goto);
         code->push_back(address_L0);
         setAddress(L1, code->size());
     }
void souffle::LVMGenerator::visitIntrinsicOperator (const RamIntrinsicOperator & op, size_t exitAddress) inline override protected
Definition at line 147 of file LVMGenerator.h.
References souffle::ADD, souffle::BAND, souffle::BNOT, souffle::BOR, souffle::BXOR, souffle::CAT, souffle::DIV, souffle::EXP, souffle::RamAbstractOperator::getArguments(), souffle::RamIntrinsicOperator::getOperator(), souffle::LAND, souffle::LNOT, souffle::LOR, souffle::LVM_OP_ADD, souffle::LVM_OP_BAND, souffle::LVM_OP_BNOT, souffle::LVM_OP_BOR, souffle::LVM_OP_BXOR, souffle::LVM_OP_CAT, souffle::LVM_OP_DIV, souffle::LVM_OP_EXP, souffle::LVM_OP_LAND, souffle::LVM_OP_LNOT, souffle::LVM_OP_LOR, souffle::LVM_OP_MAX, souffle::LVM_OP_MIN, souffle::LVM_OP_MOD, souffle::LVM_OP_MUL, souffle::LVM_OP_NEG, souffle::LVM_OP_ORD, souffle::LVM_OP_STRLEN, souffle::LVM_OP_SUB, souffle::LVM_OP_SUBSTR, souffle::LVM_OP_TONUMBER, souffle::LVM_OP_TOSTRING, souffle::MAX, souffle::MIN, souffle::MOD, souffle::MUL, souffle::NEG, souffle::ORD, souffle::STRLEN, souffle::SUB, souffle::SUBSTR, souffle::TONUMBER, and souffle::TOSTRING.
{
         const auto& args = op.getArguments();
         switch (op.getOperator()) {
             // Unary Functor Operator
             case FunctorOp::ORD:
                 visit(args[0], exitAddress);
                 code->push_back(LVM_OP_ORD);
                 break;
             case FunctorOp::STRLEN:
                 visit(args[0], exitAddress);
                 code->push_back(LVM_OP_STRLEN);
                 break;
             case FunctorOp::NEG:
                 visit(args[0], exitAddress);
                 code->push_back(LVM_OP_NEG);
                 break;
             case FunctorOp::BNOT:
                 visit(args[0], exitAddress);
                 code->push_back(LVM_OP_BNOT);
                 break;
             case FunctorOp::LNOT:
                 visit(args[0], exitAddress);
                 code->push_back(LVM_OP_LNOT);
                 break;
             case FunctorOp::TONUMBER:
                 visit(args[0], exitAddress);
                 code->push_back(LVM_OP_TONUMBER);
                 break;
             case FunctorOp::TOSTRING:
                 visit(args[0], exitAddress);
                 code->push_back(LVM_OP_TOSTRING);
                 break;
             // Binary Functor Operators
             case FunctorOp::ADD:
                 visit(args[0], exitAddress);
                 visit(args[1], exitAddress);
                 code->push_back(LVM_OP_ADD);
                 break;
             case FunctorOp::SUB:
                 visit(args[0], exitAddress);
                 visit(args[1], exitAddress);
                 code->push_back(LVM_OP_SUB);
                 break;
             case FunctorOp::MUL:
                 visit(args[0], exitAddress);
                 visit(args[1], exitAddress);
                 code->push_back(LVM_OP_MUL);
                 break;
             case FunctorOp::DIV:
                 visit(args[0], exitAddress);
                 visit(args[1], exitAddress);
                 code->push_back(LVM_OP_DIV);
                 break;
             case FunctorOp::EXP:
                 visit(args[0], exitAddress);
                 visit(args[1], exitAddress);
                 code->push_back(LVM_OP_EXP);
                 break;
             case FunctorOp::MOD:
                 visit(args[0], exitAddress);
                 visit(args[1], exitAddress);
                 code->push_back(LVM_OP_MOD);
                 break;
             case FunctorOp::BAND:
                 visit(args[0], exitAddress);
                 visit(args[1], exitAddress);
                 code->push_back(LVM_OP_BAND);
                 break;
             case FunctorOp::BOR:
                 visit(args[0], exitAddress);
                 visit(args[1], exitAddress);
                 code->push_back(LVM_OP_BOR);
                 break;
             case FunctorOp::BXOR:
                 visit(args[0], exitAddress);
                 visit(args[1], exitAddress);
                 code->push_back(LVM_OP_BXOR);
                 break;
             case FunctorOp::LAND:
                 visit(args[0], exitAddress);
                 visit(args[1], exitAddress);
                 code->push_back(LVM_OP_LAND);
                 break;
             case FunctorOp::LOR:
                 visit(args[0], exitAddress);
                 visit(args[1], exitAddress);
                 code->push_back(LVM_OP_LOR);
                 break;
             case FunctorOp::MAX:
                 for (auto& arg : args) {
                     visit(arg, exitAddress);
                 }
                 code->push_back(LVM_OP_MAX);
                 code->push_back(args.size());
                 break;
             case FunctorOp::MIN:
                 for (auto& arg : args) {
                     visit(arg, exitAddress);
                 }
                 code->push_back(LVM_OP_MIN);
                 code->push_back(args.size());
                 break;
             case FunctorOp::CAT:
                 for (auto iter = args.rbegin(); iter != args.rend(); iter++) {
                     visit(*iter, exitAddress);
                 }
                 code->push_back(LVM_OP_CAT);
                 code->push_back(args.size());
                 break;
             // Ternary Functor Operators
             case FunctorOp::SUBSTR:
                 visit(args[0], exitAddress);
                 visit(args[1], exitAddress);
                 visit(args[2], exitAddress);
                 code->push_back(LVM_OP_SUBSTR);
                 break;
             // Undefined
             default:
                 assert(false && "unsupported operator");
                 return;
         }
     }
void souffle::LVMGenerator::visitLoad (const RamLoad & load, size_t exitAddress) inline override protected
Definition at line 1049 of file LVMGenerator.h.
References souffle::RamAbstractLoadStore::getIODirectives(), souffle::RamRelationStatement::getRelation(), and souffle::LVM_Load.
{
         code->push_back(LVM_Load);
         code->push_back(relationEncoder.encodeRelation(load.getRelation()));
         code->getIODirectives().push_back(load.getIODirectives());
         code->push_back(code->getIODirectivesSize() - 1);
     }
void souffle::LVMGenerator::visitLogRelationTimer (const RamLogRelationTimer & timer, size_t exitAddress) inline override protected
Definition at line 996 of file LVMGenerator.h.
References souffle::RamAbstractLog::getMessage(), souffle::RamRelationStatement::getRelation(), souffle::RamAbstractLog::getStatement(), souffle::LVM_LogRelationTimer, and souffle::LVM_StopLogTimer.
{
         code->push_back(LVM_LogRelationTimer);
         size_t timerIndex = getNewTimer();
         code->push_back(symbolTable.lookup(timer.getMessage()));
         code->push_back(timerIndex);
         code->push_back(relationEncoder.encodeRelation(timer.getRelation()));
         visit(timer.getStatement(), exitAddress);
         code->push_back(LVM_StopLogTimer);
         code->push_back(timerIndex);
     }
void souffle::LVMGenerator::visitLogSize (const RamLogSize & size, size_t exitAddress) inline override protected
Definition at line 1043 of file LVMGenerator.h.
References souffle::RamLogSize::getMessage(), souffle::RamRelationStatement::getRelation(), and souffle::LVM_LogSize.
{
         code->push_back(LVM_LogSize);
         code->push_back(relationEncoder.encodeRelation(size.getRelation()));
         code->push_back(symbolTable.lookup(size.getMessage()));
     }
void souffle::LVMGenerator::visitLogTimer (const RamLogTimer & timer, size_t exitAddress) inline override protected
Definition at line 1007 of file LVMGenerator.h.
References souffle::RamAbstractLog::getMessage(), souffle::RamAbstractLog::getStatement(), souffle::LVM_LogTimer, and souffle::LVM_StopLogTimer.
{
         code->push_back(LVM_LogTimer);
         size_t timerIndex = getNewTimer();
         code->push_back(symbolTable.lookup(timer.getMessage()));
         code->push_back(timerIndex);
         visit(timer.getStatement(), exitAddress);
         code->push_back(LVM_StopLogTimer);
         code->push_back(timerIndex);
     }
void souffle::LVMGenerator::visitLoop (const RamLoop & loop, size_t exitAddress) inline override protected
Definition at line 973 of file LVMGenerator.h.
References souffle::RamLoop::getBody(), souffle::LVM_Goto, souffle::LVM_IncIterationNumber, souffle::LVM_Loop, and souffle::LVM_ResetIterationNumber.
{
         size_t address_L0 = code->size();
         code->push_back(LVM_Loop);
         size_t L1 = getNewAddressLabel();
         size_t address_L1 = lookupAddress(L1);
         // Address_L1 is the destination for LVM_Exit
         visit(loop.getBody(), address_L1);
         code->push_back(LVM_IncIterationNumber);
         code->push_back(LVM_Goto);
         code->push_back(address_L0);
         code->push_back(LVM_ResetIterationNumber);
         setAddress(L1, code->size());
     }
void souffle::LVMGenerator::visitMerge (const RamMerge & merge, size_t exitAddress) inline override protected
Definition at line 1082 of file LVMGenerator.h.
References souffle::RamRelation::getName(), souffle::RamMerge::getSourceRelation(), souffle::RamMerge::getTargetRelation(), and souffle::LVM_Merge.
{
         std::string source = merge.getSourceRelation().getName();
         std::string target = merge.getTargetRelation().getName();
         code->push_back(LVM_Merge);
         code->push_back(relationEncoder.encodeRelation(merge.getSourceRelation()));
         code->push_back(relationEncoder.encodeRelation(merge.getTargetRelation()));
     }
void souffle::LVMGenerator::visitNegation (const RamNegation & neg, size_t exitAddress) inline override protected
Definition at line 313 of file LVMGenerator.h.
References souffle::RamNegation::getOperand(), and souffle::LVM_Negation.
{
         visit(neg.getOperand(), exitAddress);
         code->push_back(LVM_Negation);
     }
void souffle::LVMGenerator::visitNestedOperation (const RamNestedOperation & nested, size_t exitAddress) inline override protected
Definition at line 425 of file LVMGenerator.h.
References souffle::RamNestedOperation::getOperation().
{
         visit(nested.getOperation(), exitAddress);
     }
void souffle::LVMGenerator::visitNode (const RamNode & node, size_t exitAddress) inline override protected
Unknown Node
Definition at line 1102 of file LVMGenerator.h.
{
         assert(false && "Unknown Node type");
         /** Unknown Node */
     }
void souffle::LVMGenerator::visitNumber (const RamNumber & num, size_t exitAddress) inline override protected
Definition at line 132 of file LVMGenerator.h.
References souffle::RamNumber::getConstant(), and souffle::LVM_Number.
{
         code->push_back(LVM_Number);
         code->push_back(num.getConstant());
     }
void souffle::LVMGenerator::visitPackRecord (const RamPackRecord & pack, size_t exitAddress) inline override protected
Definition at line 283 of file LVMGenerator.h.
References souffle::RamPackRecord::getArguments(), and souffle::LVM_PackRecord.
{
         auto values = pack.getArguments();
         for (auto& value : values) {
             visit(value, exitAddress);
         }
         code->push_back(LVM_PackRecord);
         code->push_back(values.size());
     }
void souffle::LVMGenerator::visitParallel (const RamParallel & parallel, size_t exitAddress) inline override protected
Definition at line 938 of file LVMGenerator.h.
References souffle::RamListStatement::getStatements(), i, souffle::LVM_NOP, souffle::LVM_Parallel, and souffle::LVM_Stop_Parallel.
{
         // TODO(xiaowen/#998): Currently parallel execution is suppressed.
         // All parallel execution will be executed in sequence.
         auto stmts = parallel.getStatements();
         size_t size = stmts.size();
         // Special case when size = 1: run in sequence instead.
         // Currently all parallel is executed in sequence.
         if (size == 1 || true) {
             for (const auto& cur : parallel.getStatements()) {
                 visit(cur, exitAddress);
             }
             return;
         }
         code->push_back(LVM_Parallel);
         code->push_back(size);
         size_t endAddress = getNewAddressLabel();
         code->push_back(lookupAddress(endAddress));
         size_t startAddresses[size];
         for (size_t i = 0; i < size; ++i) {
             startAddresses[i] = getNewAddressLabel();
             code->push_back(lookupAddress(startAddresses[i]));
         }
         for (size_t i = 0; i < size; ++i) {
             setAddress(startAddresses[i], code->size());
             visit(parallel.getStatements()[i], exitAddress);
             code->push_back(LVM_Stop_Parallel);
             code->push_back(LVM_NOP);
         }
         setAddress(endAddress, code->size());
     }
void souffle::LVMGenerator::visitProject (const RamProject & project, size_t exitAddress) inline override protected
Definition at line 900 of file LVMGenerator.h.
References arity, souffle::RamRelation::getArity(), souffle::RamRelation::getName(), souffle::RamProject::getRelation(), souffle::RamProject::getValues(), i, and souffle::LVM_Project.
{
         size_t arity = project.getRelation().getArity();
         std::string relationName = project.getRelation().getName();
         auto values = project.getValues();
         for (size_t i = values.size(); i-- > 0;) {
             assert(values[i]);
             visit(values[i], exitAddress);
         }
         code->push_back(LVM_Project);
         code->push_back(arity);
         code->push_back(relationEncoder.encodeRelation(project.getRelation()));
     }
void souffle::LVMGenerator::visitProvenanceExistenceCheck (const RamProvenanceExistenceCheck & provExists, size_t exitAddress) inline override protected
Definition at line 354 of file LVMGenerator.h.
References arity, souffle::RamRelation::getArity(), souffle::RamAbstractExistenceCheck::getRelation(), souffle::RamAbstractExistenceCheck::getValues(), i, souffle::isRamUndefValue(), souffle::LVM_EmptinessCheck, and souffle::LVM_Negation.
{
         // By leaving the last two pattern mask empty (0), we can transfer a provenance existence into an
         // equivalent Ram existence check.
         // Unlike RamExistence, a ProvenanceExistence can never be a full order existence check.
         auto values = provExists.getValues();
         auto arity = provExists.getRelation().getArity();
         auto relId = relationEncoder.encodeRelation(provExists.getRelation());
         std::vector<int> typeMask(arity);
         bool emptinessCheck = true;
         for (size_t i = arity - 2; i-- > 0;) {
             if (!isRamUndefValue(values[i])) {
                 visit(values[i], exitAddress);
                 emptinessCheck = false;
                 typeMask[i] = 1;
             }
         }
         // Empty type mask is equivalent to a non-emptiness check
         if (emptinessCheck == true) {
             code->push_back(LVM_EmptinessCheck);
             code->push_back(relId);
             code->push_back(LVM_Negation);
         } else {  // Otherwise we do a partial existence check.
             size_t indexPos = getIndexPos(provExists);
             this->emitExistenceCheckInst(arity, relId, indexPos, typeMask);
         }
     }
void souffle::LVMGenerator::visitQuery (const RamQuery & insert, size_t exitAddress) inline override protected
Definition at line 1077 of file LVMGenerator.h.
References souffle::RamQuery::getOperation(), and souffle::LVM_Query.
{
         code->push_back(LVM_Query);
         visit(insert.getOperation(), exitAddress);
     }
void souffle::LVMGenerator::visitScan (const RamScan & scan, size_t exitAddress) inline override protected
Definition at line 440 of file LVMGenerator.h.
References souffle::RamRelationOperation::getRelation(), souffle::RamTupleOperation::getTupleId(), souffle::LVM_Goto, souffle::LVM_ITER_Inc, souffle::LVM_ITER_InitFullIndex, souffle::LVM_ITER_NotAtEnd, souffle::LVM_ITER_Select, souffle::LVM_Jmpez, and souffle::LVM_Scan.
{
         code->push_back(LVM_Scan);
         size_t counterLabel = getNewIterator();
         size_t L1 = getNewAddressLabel();
         // Init the Iterator
         code->push_back(LVM_ITER_InitFullIndex);
         code->push_back(counterLabel);
         code->push_back(relationEncoder.encodeRelation(scan.getRelation()));
         // While iterator is not at end
         size_t address_L0 = code->size();
         code->push_back(LVM_ITER_NotAtEnd);
         code->push_back(counterLabel);
         code->push_back(LVM_Jmpez);
         code->push_back(lookupAddress(L1));
         // Select the tuple pointed by iter
         code->push_back(LVM_ITER_Select);
         code->push_back(counterLabel);
         code->push_back(scan.getTupleId());
         // Perform nested operation
         visitTupleOperation(scan, lookupAddress(L1));
         // Increment the Iter and jump to the start of the while loop
         code->push_back(LVM_ITER_Inc);
         code->push_back(counterLabel);
         code->push_back(LVM_Goto);
         code->push_back(address_L0);
         setAddress(L1, code->size());
     }
void souffle::LVMGenerator::visitSequence (const RamSequence & seq, size_t exitAddress) inline override protected
Visit RAM stmt.
Definition at line 931 of file LVMGenerator.h.
References souffle::RamListStatement::getStatements(), and souffle::LVM_Sequence.
{
         code->push_back(LVM_Sequence);
         for (const auto& cur : seq.getStatements()) {
             visit(cur, exitAddress);
         }
     }
void souffle::LVMGenerator::visitStore (const RamStore & store, size_t exitAddress) inline override protected
Definition at line 1057 of file LVMGenerator.h.
References souffle::RamAbstractLoadStore::getIODirectives(), souffle::RamRelationStatement::getRelation(), and souffle::LVM_Store.
{
         code->push_back(LVM_Store);
         code->push_back(relationEncoder.encodeRelation(store.getRelation()));
         code->getIODirectives().push_back(store.getIODirectives());
         code->push_back(code->getIODirectivesSize() - 1);
     }
void souffle::LVMGenerator::visitStratum (const RamStratum & stratum, size_t exitAddress) inline override protected
Definition at line 1023 of file LVMGenerator.h.
References souffle::RamStratum::getBody(), and souffle::LVM_Stratum.
{
         code->push_back(LVM_Stratum);
         visit(stratum.getBody(), exitAddress);
     }
void souffle::LVMGenerator::visitSubroutineArgument (const RamSubroutineArgument & arg, size_t exitAddress) inline override protected
Definition at line 292 of file LVMGenerator.h.
References souffle::RamSubroutineArgument::getArgument(), and souffle::LVM_Argument.
{
         code->push_back(LVM_Argument);
         code->push_back(arg.getArgument());
     }
void souffle::LVMGenerator::visitSubroutineReturnValue (const RamSubroutineReturnValue & ret, size_t exitAddress) inline override protected
Definition at line 912 of file LVMGenerator.h.
References souffle::RamSubroutineReturnValue::getValues(), i, souffle::isRamUndefValue(), souffle::LVM_ReturnValue, and types.
{
         std::string types;
         auto expressions = ret.getValues();
         size_t size = expressions.size();
         for (size_t i = size; i-- > 0;) {
             if (isRamUndefValue(expressions[i])) {
                 types += '_';
             } else {
                 types += 'V';
                 visit(expressions[i], exitAddress);
             }
         }
         code->push_back(LVM_ReturnValue);
         code->push_back(ret.getValues().size());
         code->push_back(symbolTable.lookup(types));
     }
void souffle::LVMGenerator::visitSwap (const RamSwap & swap, size_t exitAddress) inline override protected
Definition at line 1090 of file LVMGenerator.h.
References souffle::RamBinRelationStatement::getFirstRelation(), souffle::RamRelation::getName(), souffle::RamBinRelationStatement::getSecondRelation(), and souffle::LVM_Swap.
{
         std::string first = swap.getFirstRelation().getName();
         std::string second = swap.getSecondRelation().getName();
         code->push_back(LVM_Swap);
         code->push_back(relationEncoder.encodeRelation(swap.getFirstRelation()));
         code->push_back(relationEncoder.encodeRelation(swap.getSecondRelation()));
     }
void souffle::LVMGenerator::visitTrue (const RamTrue & ltrue, size_t exitAddress) inline override protected
Definition at line 299 of file LVMGenerator.h.
References souffle::LVM_True.
{
         code->push_back(LVM_True);
     }
void souffle::LVMGenerator::visitTupleElement (const RamTupleElement & access, size_t exitAddress) inline override protected
Definition at line 137 of file LVMGenerator.h.
References souffle::RamTupleElement::getElement(), souffle::RamTupleElement::getTupleId(), and souffle::LVM_TupleElement.
{
         code->push_back(LVM_TupleElement);
         code->push_back(access.getTupleId());
         code->push_back(access.getElement());
     }
void souffle::LVMGenerator::visitTupleOperation (const RamTupleOperation & search, size_t exitAddress) inline override protected
Definition at line 429 of file LVMGenerator.h.
References souffle::RamNestedOperation::getProfileText(), and souffle::LVM_Search.
{
         code->push_back(LVM_Search);
         if (search.getProfileText().empty()) {
             code->push_back(0);
         } else {
             code->push_back(1);
         }
         code->push_back(symbolTable.lookup(search.getProfileText()));
         visitNestedOperation(search, exitAddress);
     }
void souffle::LVMGenerator::visitUndefValue (const RamUndefValue & undef, size_t exitAddress) inline override protected
Definition at line 1098 of file LVMGenerator.h.
{
         assert(false && "Compilation error");
     }
void souffle::LVMGenerator::visitUnpackRecord (const RamUnpackRecord & lookup, size_t exitAddress) inline override protected
Definition at line 622 of file LVMGenerator.h.
References souffle::RamUnpackRecord::getArity(), souffle::RamUnpackRecord::getExpression(), souffle::RamTupleOperation::getTupleId(), and souffle::LVM_UnpackRecord.
{
         // (xiaowen): In the case where reference we want to look up is null, we should return.
         // This can be expressed by the LVM instructions or delegate to CPP code.
         // For now, it is done by passing the next IP (L0) and let CPP to handle the case.
         visit(lookup.getExpression(), exitAddress);
         code->push_back(LVM_UnpackRecord);
         size_t L0 = getNewAddressLabel();
         code->push_back(lookup.getArity());
         code->push_back(lookup.getTupleId());
         code->push_back(lookupAddress(L0));
         visitTupleOperation(lookup, exitAddress);
         setAddress(L0, code->size());
     }
void souffle::LVMGenerator::visitUserDefinedOperator (const RamUserDefinedOperator & op, size_t exitAddress) inline override protected
Definition at line 273 of file LVMGenerator.h.
References souffle::RamAbstractOperator::getArgCount(), souffle::RamAbstractOperator::getArgument(), souffle::RamUserDefinedOperator::getName(), souffle::RamUserDefinedOperator::getType(), i, and souffle::LVM_UserDefinedOperator.
{
         for (size_t i = op.getArgCount(); i-- > 0;) {
             visit(op.getArgument(i), exitAddress);
         }
         code->push_back(LVM_UserDefinedOperator);
         code->push_back(symbolTable.lookup(op.getName()));
         code->push_back(symbolTable.lookup(op.getType()));
         code->push_back(op.getArgCount());
     }
Field Documentation
std::vector<size_t> souffle::LVMGenerator::addressMap private
Address map.
Definition at line 1118 of file LVMGenerator.h.
std::unique_ptr<LVMCode> souffle::LVMGenerator::code private
code stream
Definition at line 1112 of file LVMGenerator.h.
size_t souffle::LVMGenerator::currentAddressLabel = 0 private
Current address label.
Definition at line 1115 of file LVMGenerator.h.
size_t souffle::LVMGenerator::iteratorIndex = 0 private
Current iterator index.
Definition at line 1121 of file LVMGenerator.h.
RelationEncoder& souffle::LVMGenerator::relationEncoder private
Relation Encoder.
Definition at line 1127 of file LVMGenerator.h.
SymbolTable& souffle::LVMGenerator::symbolTable private
Symbol table.
Definition at line 1109 of file LVMGenerator.h.
size_t souffle::LVMGenerator::timerIndex = 0 private
Current timer index for logger.
Definition at line 1124 of file LVMGenerator.h.
The documentation for this class was generated from the following file:
LVMGenerator.h