souffle: souffle::RamAbstractOperator Class Reference
souffle::RamAbstractOperator Class Reference
Abstract class for an operator/functor.
#include <RamExpression.h>
Public Member Functions
void apply (const RamNodeMapper &map) override
Apply the mapper to all child nodes.
size_t getArgCount () const
Get number of arguments.
const RamExpression & getArgument (size_t i) const
Get i-th argument value.
std::vector< RamExpression * > getArguments () const
Get argument values.
std::vector< const RamNode * > getChildNodes () const override
Obtain list of all embedded child nodes.
RamAbstractOperator (std::vector< std::unique_ptr< RamExpression >> args)
Public Member Functions inherited from souffle::RamExpression
RamExpression * clone () const override=0
Create a clone (i.e.
Public Member Functions inherited from souffle::RamNode
bool operator!= (const RamNode &other) const
Inequality check for two RAM nodes.
bool operator== (const RamNode &other) const
Equivalence check for two RAM nodes.
virtual void print (std::ostream &out=std::cout) const =0
Print RAM node.
RamNode ()=default
virtual ~RamNode ()=default
Protected Member Functions
bool equal (const RamNode &node) const override
Equality check for two RAM nodes.
Protected Attributes
std::vector< std::unique_ptr< RamExpression > > arguments
Arguments of user defined operator.
Detailed Description
Abstract class for an operator/functor.
Definition at line 48 of file RamExpression.h.
Constructor & Destructor Documentation
souffle::RamAbstractOperator::RamAbstractOperator (std::vector< std::unique_ptr< RamExpression >> args) inline
Definition at line 50 of file RamExpression.h.
 : arguments(std::move(args)) {}
Member Function Documentation
void souffle::RamAbstractOperator::apply (const RamNodeMapper & mapper) inline override virtual
Apply the mapper to all child nodes.
Reimplemented from souffle::RamNode.
Definition at line 76 of file RamExpression.h.
{
         for (auto& arg : arguments) {
             arg = map(std::move(arg));
         }
     }
bool souffle::RamAbstractOperator::equal (const RamNode & other) const inline override protected virtual
Equality check for two RAM nodes.
Default action is that nothing needs to be checked.
Reimplemented from souffle::RamNode.
Reimplemented in souffle::RamUserDefinedOperator, and souffle::RamIntrinsicOperator.
Definition at line 86 of file RamExpression.h.
References souffle::equal_targets().
Referenced by souffle::RamIntrinsicOperator::equal(), and souffle::RamUserDefinedOperator::equal().
{
         assert(nullptr != dynamic_cast<const RamAbstractOperator*>(&node));
         const auto& other = static_cast<const RamAbstractOperator&>(node);
         return equal_targets(arguments, other.arguments);
     }
size_t souffle::RamAbstractOperator::getArgCount () const inline
Get number of arguments.
Definition at line 64 of file RamExpression.h.
Referenced by souffle::Synthesiser::emitCode(), souffle::RAMI::evalExpr(), and souffle::LVMGenerator::visitUserDefinedOperator().
{
         return arguments.size();
     }
const RamExpression& souffle::RamAbstractOperator::getArgument (size_t i) const inline
Get i-th argument value.
Definition at line 58 of file RamExpression.h.
References i.
Referenced by souffle::Synthesiser::emitCode(), souffle::RAMI::evalExpr(), and souffle::LVMGenerator::visitUserDefinedOperator().
{
         assert(i >= 0 && i < arguments.size() && "argument index out of bounds");
         return *arguments[i];
     }
std::vector<RamExpression*> souffle::RamAbstractOperator::getArguments () const inline
Get argument values.
Definition at line 53 of file RamExpression.h.
References souffle::toPtrVector().
Referenced by souffle::Synthesiser::emitCode(), souffle::RAMI::evalExpr(), souffle::RamLevelAnalysis::getLevel(), and souffle::LVMGenerator::visitIntrinsicOperator().
{
         return toPtrVector(arguments);
     }
std::vector<const RamNode*> souffle::RamAbstractOperator::getChildNodes () const inline override virtual
Obtain list of all embedded child nodes.
Reimplemented from souffle::RamNode.
Definition at line 68 of file RamExpression.h.
{
         std::vector<const RamNode*> res;
         for (const auto& cur : arguments) {
             res.push_back(cur.get());
         }
         return res;
     }
Field Documentation
std::vector<std::unique_ptr<RamExpression> > souffle::RamAbstractOperator::arguments protected
Arguments of user defined operator.
Definition at line 84 of file RamExpression.h.
The documentation for this class was generated from the following file:
RamExpression.h