souffle: souffle::RAMIRelInterface::iterator_base Class Reference
souffle::RAMIRelInterface::iterator_base Class Reference
Iterator wrapper class.
#include <RAMIProgInterface.h>
Public Member Functions
iterator_base * clone () const override
Clone iterator.
iterator_base (uint32_t arg_id, const RAMIRelInterface *r, RAMIRelation::iterator i)
tuple & operator* () override
Get current tuple.
void operator++ () override
Increment iterator.
~iterator_base () override=default
Public Member Functions inherited from souffle::Relation::iterator_base
virtual uint32_t getId () const
iterator_base (uint32_t arg_id)
bool operator== (const iterator_base &o) const
Protected Member Functions
bool equal (const Relation::iterator_base &o) const override
Check equivalence.
Private Attributes
RAMIRelation::iterator it
const RAMIRelInterface * ramRelationInterface
tuple tup
Additional Inherited Members
Protected Attributes inherited from souffle::Relation::iterator_base
uint32_t id
Detailed Description
Iterator wrapper class.
Definition at line 100 of file RAMIProgInterface.h.
Constructor & Destructor Documentation
souffle::RAMIRelInterface::iterator_base::iterator_base (uint32_t arg_id, const RAMIRelInterface * r, RAMIRelation::iterator i) inline
Definition at line 102 of file RAMIProgInterface.h.
References ~iterator_base().
                 : Relation::iterator_base(arg_id), ramRelationInterface(r), it(i), tup(r) {}
souffle::RAMIRelInterface::iterator_base::~iterator_base () override virtual default
Reimplemented from souffle::Relation::iterator_base.
Referenced by iterator_base().
Member Function Documentation
iterator_base* souffle::RAMIRelInterface::iterator_base::clone () const inline override virtual
Clone iterator.
Implements souffle::Relation::iterator_base.
Definition at line 130 of file RAMIProgInterface.h.
References souffle::Relation::iterator_base::getId(), it, and ramRelationInterface.
{
             return new RAMIRelInterface::iterator_base(getId(), ramRelationInterface, it);
         }
bool souffle::RAMIRelInterface::iterator_base::equal (const Relation::iterator_base & o) const inline override protected virtual
Check equivalence.
Implements souffle::Relation::iterator_base.
Definition at line 136 of file RAMIProgInterface.h.
References e, it, o, and ramRelationInterface.
{
             try {
                 auto iter = dynamic_cast<const RAMIRelInterface::iterator_base&>(o);
                 return ramRelationInterface == iter.ramRelationInterface && it == iter.it;
             } catch (const std::bad_cast& e) {
                 return false;
             }
         }
tuple& souffle::RAMIRelInterface::iterator_base::operator* () inline override virtual
Get current tuple.
Implements souffle::Relation::iterator_base.
Definition at line 112 of file RAMIProgInterface.h.
References souffle::RAMIRelInterface::getArity(), souffle::RAMIRelInterface::getAttrType(), souffle::RAMIRelInterface::getSymbolTable(), i, it, ramRelationInterface, souffle::SymbolTable::resolve(), souffle::tuple::rewind(), and tup.
{
             // set tuple stream to first element
             tup.rewind();
             // construct the tuple to return
             for (size_t i = 0; i < ramRelationInterface->getArity(); i++) {
                 if (*(ramRelationInterface->getAttrType(i)) == 's') {
                     std::string s = ramRelationInterface->getSymbolTable().resolve((*it)[i]);
                     tup << s;
                 } else {
                     tup << (*it)[i];
                 }
             }
             tup.rewind();
             return tup;
         }
void souffle::RAMIRelInterface::iterator_base::operator++ () inline override virtual
Increment iterator.
Implements souffle::Relation::iterator_base.
Definition at line 107 of file RAMIProgInterface.h.
References it.
{
             ++it;
         }
Field Documentation
RAMIRelation::iterator souffle::RAMIRelInterface::iterator_base::it private
Definition at line 147 of file RAMIProgInterface.h.
Referenced by clone(), equal(), operator*(), and operator++().
const RAMIRelInterface* souffle::RAMIRelInterface::iterator_base::ramRelationInterface private
Definition at line 146 of file RAMIProgInterface.h.
Referenced by clone(), equal(), and operator*().
tuple souffle::RAMIRelInterface::iterator_base::tup private
Definition at line 148 of file RAMIProgInterface.h.
Referenced by operator*().
The documentation for this class was generated from the following file:
RAMIProgInterface.h