souffle: souffle::tuple Class Reference
souffle::tuple Class Reference
Defines a tuple for the OO interface such that relations with varying columns can be accessed.
#include <SouffleInterface.h>
Public Member Functions
decltype(array)::iterator begin ()
(insert) iterator for direct access to tuple's data (experimental)
tuple & operator<< (const std::string &str)
place a symbol into the current element of the tuple
tuple & operator<< (RamDomain number)
place a number into the current element of the tuple
tuple & operator>> (std::string &str)
read a symbol from the tuple
tuple & operator>> (RamDomain &number)
read a number from the tuple
RamDomain & operator[] (size_t idx)
direct access to tuple elements via index TODO: this interface should be hidden and only be used by friendly classes such as iterators; users should not use this interface.
const RamDomain & operator[] (size_t idx) const
void rewind ()
reset stream pointer to first element of tuple
size_t size () const
return number of elements in the tuple
tuple (const Relation *r)
tuple (const tuple &t)
tuple (Relation *r, std::initializer_list< RamDomain > il)
direct constructor using initialization list (experimental)
Data Fields
const RamDomain * data = nullptr
allows printing using WriteStream
Private Attributes
std::vector< RamDomain > array
size_t pos
const Relation & relation
Detailed Description
Defines a tuple for the OO interface such that relations with varying columns can be accessed.
Definition at line 139 of file SouffleInterface.h.
Constructor & Destructor Documentation
souffle::tuple::tuple (const Relation * r) inline
Definition at line 145 of file SouffleInterface.h.
 : relation(*r), array(r->getArity()), pos(0), data(array.data()) {}
souffle::tuple::tuple (const tuple & t) inline
Definition at line 146 of file SouffleInterface.h.
 : relation(t.relation), array(t.array), pos(t.pos), data(array.data()) {}
souffle::tuple::tuple (Relation * r, std::initializer_list< RamDomain > il) inline
direct constructor using initialization list (experimental)
Definition at line 233 of file SouffleInterface.h.
References souffle::Relation::getArity().
                                                           : relation(*r), array(il), pos(il.size()) {
         assert(il.size() == r->getArity() && "wrong tuple arity");
     }
Member Function Documentation
decltype(array) ::iterator souffle::tuple::begin () inline
(insert) iterator for direct access to tuple's data (experimental)
Definition at line 226 of file SouffleInterface.h.
{
         return array.begin();
     }
tuple& souffle::tuple::operator<< (const std::string & str) inline
place a symbol into the current element of the tuple
Definition at line 184 of file SouffleInterface.h.
References souffle::Relation::getAttrType(), souffle::Relation::getSymbolTable(), souffle::SymbolTable::lookup(), and souffle::Relation::size().
{
         assert(pos < size() && "exceeded tuple's size");
         assert(*relation.getAttrType(pos) == 's' && "wrong element type");
         array[pos++] = relation.getSymbolTable().lookup(str);
         return *this;
     }
tuple& souffle::tuple::operator<< (RamDomain number) inline
place a number into the current element of the tuple
Definition at line 194 of file SouffleInterface.h.
References souffle::Relation::getAttrType(), and souffle::Relation::size().
{
         assert(pos < size() && "exceeded tuple's size");
         assert((*relation.getAttrType(pos) == 'i' || *relation.getAttrType(pos) == 'r') &&
                 "wrong element type");
         array[pos++] = number;
         return *this;
     }
tuple& souffle::tuple::operator>> (std::string & str) inline
read a symbol from the tuple
Definition at line 205 of file SouffleInterface.h.
References souffle::Relation::getAttrType(), souffle::Relation::getSymbolTable(), souffle::SymbolTable::resolve(), and souffle::Relation::size().
{
         assert(pos < size() && "exceeded tuple's size");
         assert(*relation.getAttrType(pos) == 's' && "wrong element type");
         str = relation.getSymbolTable().resolve(array[pos++]);
         return *this;
     }
tuple& souffle::tuple::operator>> (RamDomain & number) inline
read a number from the tuple
Definition at line 215 of file SouffleInterface.h.
References souffle::Relation::getAttrType(), and souffle::Relation::size().
{
         assert(pos < size() && "exceeded tuple's size");
         assert((*relation.getAttrType(pos) == 'i' || *relation.getAttrType(pos) == 'r') &&
                 "wrong element type");
         number = array[pos++];
         return *this;
     }
RamDomain& souffle::tuple::operator[] (size_t idx) inline
direct access to tuple elements via index TODO: this interface should be hidden and only be used by friendly classes such as iterators; users should not use this interface.
Definition at line 166 of file SouffleInterface.h.
{
         return array[idx];
     }
const RamDomain& souffle::tuple::operator[] (size_t idx) const inline
Definition at line 170 of file SouffleInterface.h.
{
         return array[idx];
     }
void souffle::tuple::rewind () inline
reset stream pointer to first element of tuple
Definition at line 177 of file SouffleInterface.h.
Referenced by souffle::RelationWrapper< id, RelType, TupleType, Arity >::iterator_wrapper::operator*(), souffle::RAMIRelInterface::iterator_base::operator*(), and souffle::LVMRelInterface::iterator_base::operator*().
                   {
         pos = 0;
     }
size_t souffle::tuple::size () const inline
return number of elements in the tuple
Definition at line 156 of file SouffleInterface.h.
Referenced by souffle::RelationWrapper< id, RelType, TupleType, Arity >::contains(), and souffle::RelationWrapper< id, RelType, TupleType, Arity >::insert().
{
         return array.size();
     }
Field Documentation
std::vector<RamDomain> souffle::tuple::array private
Definition at line 141 of file SouffleInterface.h.
const RamDomain* souffle::tuple::data = nullptr
allows printing using WriteStream
Definition at line 151 of file SouffleInterface.h.
Referenced by souffle::LVMRelInterface::contains(), souffle::RAMIRelInterface::contains(), souffle::RAMIRelInterface::insert(), and souffle::LVMRelInterface::insert().
size_t souffle::tuple::pos private
Definition at line 142 of file SouffleInterface.h.
const Relation& souffle::tuple::relation private
Definition at line 140 of file SouffleInterface.h.
The documentation for this class was generated from the following file:
SouffleInterface.h