souffle: souffle::Trie< Dim > Class Template Reference
souffle::Trie< Dim > Class Template Reference
The most generic implementation of a Trie forming the top-level of any Trie storing tuples of arity > 1.
#include <Brie.h>
Data Structures
class iterator_core
The iterator core for trie iterators involving this level.
struct nested_trie_cloner
struct nested_trie_merger
struct op_context
Public Types
using element_type = entry_type
using entry_type = typename ram::Tuple< RamDomain, Dim >
using iterator = typename base::template iterator< iterator_core >
Public Types inherited from souffle::detail::TrieBase< Dim, Trie< Dim > >
using entry_type = typename ram::Tuple< RamDomain, Dim >
The type of the stored entries / tuples.
Public Member Functions
iterator begin () const
Obtains an iterator referencing the first element stored within this trie.
void clear ()
Removes all entries within this trie.
bool contains (const entry_type &tuple) const
Determines whether a given tuple is present within the set specified by this trie.
bool contains (const entry_type &tuple, op_context &ctxt) const
Determines whether a given tuple is present within the set specified by this trie.
bool empty () const
Determines whether this trie is empty or not.
iterator end () const
Obtains an iterator referencing the position after the last element stored within this trie.
iterator find (const entry_type &entry) const
iterator find (const entry_type &entry, op_context &ctxt) const
template<unsigned levels>
range< iterator > getBoundaries (const entry_type &entry) const
Obtains a range of elements matching the prefix of the given entry up to levels elements.
template<unsigned levels>
range< iterator > getBoundaries (const entry_type &entry, op_context &ctxt) const
Obtains a range of elements matching the prefix of the given entry up to levels elements.
std::size_t getMemoryUsage () const
Computes the total memory usage of this data structure.
const store_type & getStore () const
Provides a protected access to the internally maintained store.
bool insert (const entry_type &tuple)
Inserts a new entry.
bool insert (const entry_type &tuple, op_context &ctxt)
Inserts a new entry.
void insertAll (const Trie &other)
Inserts all elements stored within the given trie into this trie.
iterator lower_bound (const entry_type &entry) const
Obtains an iterator to the first element not less than the given entry value.
std::vector< range< iterator > > partition (unsigned chunks=500) const
Computes a partition of an approximate number of chunks of the content of this trie.
std::size_t size () const
Determines the number of entries in this trie.
~Trie ()
A simple destructore.
Public Member Functions inherited from souffle::detail::TrieBase< Dim, Trie< Dim > >
bool contains (Values...values) const
A generic function enabling the convenient conduction of a membership check.
const hint_statistics & getHintStatistics () const
bool insert (Values...values)
A generic function enabling the insertion of tuple values in a user-friendly way.
Private Types
using base = typename detail::TrieBase< Dim, Trie< Dim >>
using nested_trie_type = Trie< Dim-1 >
using store_type = SparseArray< nested_trie_type *, 6, nested_trie_merger, nested_trie_cloner >
Private Member Functions
template<unsigned I, typename Tuple >
bool contains_internal (const Tuple &tuple, op_context &ctxt) const
An internal implementation of the contains member function determining whether a given tuple is present within this sub-trie or not.
template<unsigned I, typename Tuple >
iterator_core< I > getBeginCoreIterator (Tuple &entry) const
Creates a core iterator for this trie level and updates component I of the given entry to exhibit the corresponding first value.
template<unsigned I, typename Tuple >
bool insert_internal (const Tuple &tuple, op_context &ctxt)
The internally utilized implementation of the insert operation inserting a given tuple into this sub-trie.
Private Attributes
store_type store
Friends
template<unsigned D>
class Trie
template<unsigned D, typename Derived >
class TrieBase
Additional Inherited Members
Protected Attributes inherited from souffle::detail::TrieBase< Dim, Trie< Dim > >
hint_statistics hint_stats
Detailed Description
template<unsigned Dim>
class souffle::Trie< Dim >
The most generic implementation of a Trie forming the top-level of any Trie storing tuples of arity > 1.
Definition at line 2121 of file Brie.h.
Member Typedef Documentation
template<unsigned Dim> using souffle::Trie< Dim >::base = typename detail::TrieBase<Dim, Trie<Dim>> private
Definition at line 2129 of file Brie.h.
template<unsigned Dim> using souffle::Trie< Dim >::element_type = entry_type
Definition at line 2162 of file Brie.h.
template<unsigned Dim> using souffle::Trie< Dim >::entry_type = typename ram::Tuple<RamDomain, Dim>
Definition at line 2161 of file Brie.h.
template<unsigned Dim> using souffle::Trie< Dim >::iterator = typename base::template iterator<iterator_core>
Definition at line 2244 of file Brie.h.
template<unsigned Dim> using souffle::Trie< Dim >::nested_trie_type = Trie<Dim - 1> private
Definition at line 2132 of file Brie.h.
template<unsigned Dim> using souffle::Trie< Dim >::store_type = SparseArray<nested_trie_type*, 6, nested_trie_merger, nested_trie_cloner> private
Definition at line 2155 of file Brie.h.
Constructor & Destructor Documentation
template<unsigned Dim> souffle::Trie< Dim >::~Trie () inline
A simple destructore.
Definition at line 2271 of file Brie.h.
             {
         for (auto& cur : store) {
             delete cur.second;  // clears all nested tries
         }
     }
Member Function Documentation
template<unsigned Dim> iterator souffle::Trie< Dim >::begin () const inline
Obtains an iterator referencing the first element stored within this trie.
Definition at line 2385 of file Brie.h.
Referenced by souffle::ram::index_utils::TrieIndex< Index >::begin().
{
         auto it = store.begin();
         if (it.isEnd()) return end();
         return iterator(it);
     }
template<unsigned Dim> void souffle::Trie< Dim >::clear () inline
Removes all entries within this trie.
Definition at line 2315 of file Brie.h.
Referenced by souffle::ram::index_utils::TrieIndex< Index >::clear().
                  {
         // delete lower levels
         for (auto& cur : store) {
             delete cur.second;
         }
         // clear store
         store.clear();
     }
template<unsigned Dim> bool souffle::Trie< Dim >::contains (const entry_type & tuple) const inline
Determines whether a given tuple is present within the set specified by this trie.
Parameters
tuple the tuple to be tested
Returns
true if present, false otherwise
Definition at line 2355 of file Brie.h.
Referenced by souffle::ram::index_utils::TrieIndex< Index >::contains().
{
         op_context ctxt;
         return contains(tuple, ctxt);
     }
template<unsigned Dim> bool souffle::Trie< Dim >::contains (const entry_type & tuple, op_context & ctxt) const inline
Determines whether a given tuple is present within the set specified by this trie.
A operation context may be provided to exploit temporal locality.
Parameters
tuple the entry to be added
ctxt the operation context to be utilized
Returns
true if the same tuple hasn't been present before, false otherwise
Definition at line 2369 of file Brie.h.
{
         return contains_internal<0>(tuple, ctxt);
     }
template<unsigned Dim> template<unsigned I, typename Tuple > bool souffle::Trie< Dim >::contains_internal (const Tuple & tuple, op_context & ctxt) const inline private
An internal implementation of the contains member function determining whether a given tuple is present within this sub-trie or not.
Template Parameters
I the component index associated to this level
Tuple the tuple type to be checked
Parameters
tuple the tuple to be checked
ctxt a operation context to exploit temporal locality
Returns
true if this tuple is present, false otherwise
Definition at line 2607 of file Brie.h.
{
         // check context
         if (ctxt.lastNested && ctxt.lastQuery == tuple[I]) {
             base::hint_stats.contains.addHit();
             return ctxt.lastNested->template contains_internal<I + 1>(tuple, ctxt.nestedCtxt);
         } else {
             base::hint_stats.contains.addMiss();
         }
         // lookup next step
         auto next = store.lookup(tuple[I], ctxt.local);
         // clear context if necessary
         if (next != ctxt.lastNested) {
             ctxt.lastQuery = tuple[I];
             ctxt.lastNested = next;
             ctxt.nestedCtxt = typename op_context::nested_ctxt();
         }
         // conduct recursive step
         return next && next->template contains_internal<I + 1>(tuple, ctxt.nestedCtxt);
     }
template<unsigned Dim> bool souffle::Trie< Dim >::empty () const inline
Determines whether this trie is empty or not.
Definition at line 2280 of file Brie.h.
Referenced by souffle::ram::index_utils::TrieIndex< Index >::empty().
{
         return store.empty();
     }
template<unsigned Dim> iterator souffle::Trie< Dim >::end () const inline
Obtains an iterator referencing the position after the last element stored within this trie.
Definition at line 2395 of file Brie.h.
Referenced by souffle::ram::index_utils::TrieIndex< Index >::end().
{
         return iterator();
     }
template<unsigned Dim> iterator souffle::Trie< Dim >::find (const entry_type & entry) const inline
Definition at line 2399 of file Brie.h.
Referenced by souffle::ram::index_utils::TrieIndex< Index >::find().
{
         op_context ctxt;
         return find(entry, ctxt);
     }
template<unsigned Dim> iterator souffle::Trie< Dim >::find (const entry_type & entry, op_context & ctxt) const inline
Definition at line 2404 of file Brie.h.
{
         auto range = getBoundaries<Dim>(entry, ctxt);
         return (!range.empty()) ? range.begin() : end();
     }
template<unsigned Dim> template<unsigned I, typename Tuple > iterator_core<I> souffle::Trie< Dim >::getBeginCoreIterator (Tuple & entry) const inline private
Creates a core iterator for this trie level and updates component I of the given entry to exhibit the corresponding first value.
Template Parameters
I the index of the tuple to be processed by the resulting iterator core
Tuple the type of the tuple to be processed by the resulting iterator core
Parameters
entry a reference to the tuple to be updated to the first value
Returns
the requested iterator core instance
Definition at line 2536 of file Brie.h.
{
         return iterator_core<I>(store.begin(), entry);
     }
template<unsigned Dim> template<unsigned levels> range<iterator> souffle::Trie< Dim >::getBoundaries (const entry_type & entry) const inline
Obtains a range of elements matching the prefix of the given entry up to levels elements.
Template Parameters
levels the length of the requested matching prefix
Parameters
entry the entry to be looking for
Returns
the corresponding range of matching elements
Definition at line 2418 of file Brie.h.
{
         op_context ctxt;
         return getBoundaries<levels>(entry, ctxt);
     }
template<unsigned Dim> template<unsigned levels> range<iterator> souffle::Trie< Dim >::getBoundaries (const entry_type & entry, op_context & ctxt) const inline
Obtains a range of elements matching the prefix of the given entry up to levels elements.
A operation context may be provided to exploit temporal locality.
Template Parameters
levels the length of the requested matching prefix
Parameters
entry the entry to be looking for
ctxt the operation context to be utilized
Returns
the corresponding range of matching elements
Definition at line 2434 of file Brie.h.
{
         // if nothing is bound => just use begin and end
         if (levels == 0) return make_range(begin(), end());
         // check context
         if (ctxt.lastBoundaryLevels == levels) {
             bool fit = true;
             for (unsigned i = 0; i < levels; ++i) {
                 fit = fit && (entry[i] == ctxt.lastBoundaryRequest[i]);
             }
             // if it fits => take it
             if (fit) {
                 base::hint_stats.get_boundaries.addHit();
                 return ctxt.lastBoundaries;
             }
         }
         // the hint has not been a hit
         base::hint_stats.get_boundaries.addMiss();
         // start with two end iterators
         iterator begin{}, end{};
         // adapt them level by level
         auto found = detail::fix_binding<levels, 0, Dim>()(store, begin, end, entry);
         if (!found) return make_range(iterator(), iterator());
         // update context
         ctxt.lastBoundaryLevels = levels;
         ctxt.lastBoundaryRequest = entry;
         ctxt.lastBoundaries = make_range(begin, end);
         // use the result
         return ctxt.lastBoundaries;
     }
template<unsigned Dim> std::size_t souffle::Trie< Dim >::getMemoryUsage () const inline
Computes the total memory usage of this data structure.
Definition at line 2299 of file Brie.h.
{
         // compute the total memory usage of this level
         std::size_t res = sizeof(*this) - sizeof(store) + store.getMemoryUsage();
         // add the memory usage of sub-levels
         for (const auto& cur : store) {
             res += cur.second->getMemoryUsage();
         }
         // done
         return res;
     }
template<unsigned Dim> const store_type& souffle::Trie< Dim >::getStore () const inline
Provides a protected access to the internally maintained store.
Definition at line 2521 of file Brie.h.
{
         return store;
     }
template<unsigned Dim> bool souffle::Trie< Dim >::insert (const entry_type & tuple) inline
Inserts a new entry.
Parameters
tuple the entry to be added
Returns
true if the same tuple hasn't been present before, false otherwise
Definition at line 2331 of file Brie.h.
Referenced by souffle::ram::index_utils::TrieIndex< Index >::insert().
{
         op_context ctxt;
         return insert(tuple, ctxt);
     }
template<unsigned Dim> bool souffle::Trie< Dim >::insert (const entry_type & tuple, op_context & ctxt) inline
Inserts a new entry.
A operation context may be provided to exploit temporal locality.
Parameters
tuple the entry to be added
ctxt the operation context to be utilized
Returns
true if the same tuple hasn't been present before, false otherwise
Definition at line 2344 of file Brie.h.
{
         return insert_internal<0>(tuple, ctxt);
     }
template<unsigned Dim> template<unsigned I, typename Tuple > bool souffle::Trie< Dim >::insert_internal (const Tuple & tuple, op_context & ctxt) inline private
The internally utilized implementation of the insert operation inserting a given tuple into this sub-trie.
Template Parameters
I the component index associated to this level
Tuple the tuple type to be inserted
Parameters
tuple the tuple to be inserted
ctxt a operation context to exploit temporal locality
Returns
true if this tuple wasn't contained before, false otherwise
Definition at line 2551 of file Brie.h.
{
         using value_t = typename store_type::value_type;
         using atomic_value_t = typename store_type::atomic_value_type;
         // check context
         if (ctxt.lastNested && ctxt.lastQuery == tuple[I]) {
             base::hint_stats.inserts.addHit();
             return ctxt.lastNested->template insert_internal<I + 1>(tuple, ctxt.nestedCtxt);
         } else {
             base::hint_stats.inserts.addMiss();
         }
         // lookup nested
         atomic_value_t& next = store.getAtomic(tuple[I], ctxt.local);
         // get pure pointer to next level
         value_t nextPtr = next;
         // conduct a lock-free lazy-creation of nested trees
         if (!nextPtr) {
             // create a new sub-tree
             auto newNested = new nested_trie_type();
             // register new sub-tree atomically
             if (next.compare_exchange_weak(nextPtr, newNested)) {
                 nextPtr = newNested;  // worked
             } else {
                 delete newNested;  // some other thread was faster => use its version
             }
         }
         // make sure a next has been established
         assert(nextPtr);
         // clear context if necessary
         if (nextPtr != ctxt.lastNested) {
             ctxt.lastQuery = tuple[I];
             ctxt.lastNested = nextPtr;
             ctxt.nestedCtxt = typename op_context::nested_ctxt();
         }
         // conduct recursive step
         return nextPtr->template insert_internal<I + 1>(tuple, ctxt.nestedCtxt);
     }
template<unsigned Dim> void souffle::Trie< Dim >::insertAll (const Trie< Dim > & other) inline
Inserts all elements stored within the given trie into this trie.
Parameters
other the elements to be inserted into this trie
Definition at line 2378 of file Brie.h.
Referenced by souffle::ram::index_utils::TrieIndex< Index >::insertAll(), and souffle::Trie< Dim >::nested_trie_merger::operator()().
{
         store.addAll(other.store);
     }
template<unsigned Dim> iterator souffle::Trie< Dim >::lower_bound (const entry_type & entry) const inline
Obtains an iterator to the first element not less than the given entry value.
Parameters
entry the lower bound for this search
Returns
an iterator addressing the first element in this structure not less than the given value
Definition at line 2477 of file Brie.h.
{
         // start with a default-initialized iterator
         iterator res;
         // adapt it level by level
         bool found = detail::fix_lower_bound<0, Dim>()(store, res, entry);
         // use the result
         return found ? res : end();
     }
template<unsigned Dim> std::vector<range<iterator> > souffle::Trie< Dim >::partition (unsigned chunks = 500) const inline
Computes a partition of an approximate number of chunks of the content of this trie.
Thus, the union of the resulting set of disjoint ranges is equivalent to the content of this trie.
Parameters
chunks the number of chunks requested
Returns
a list of sub-ranges forming a partition of the content of this trie
Definition at line 2496 of file Brie.h.
Referenced by souffle::ram::index_utils::TrieIndex< Index >::partition().
{
         std::vector<range<iterator>> res;
         // shortcut for empty trie
         if (this->empty()) return res;
         // use top-level elements for partitioning
         int step = std::max(store.size() / chunks, size_t(1));
         int c = 1;
         auto priv = begin();
         for (auto it = store.begin(); it != store.end(); ++it, c++) {
             if (c % step != 0 || c == 1) continue;
             auto cur = iterator(it);
             res.push_back(make_range(priv, cur));
             priv = cur;
         }
         // add final chunk
         res.push_back(make_range(priv, end()));
         return res;
     }
template<unsigned Dim> std::size_t souffle::Trie< Dim >::size () const inline
Determines the number of entries in this trie.
Definition at line 2287 of file Brie.h.
Referenced by souffle::ram::index_utils::TrieIndex< Index >::size().
{
         // the number of elements is lazy-evaluated
         std::size_t res = 0;
         for (const auto& cur : store) {
             res += cur.second->size();
         }
         return res;
     }
Friends And Related Function Documentation
template<unsigned Dim> template<unsigned D> friend class Trie friend
Definition at line 2123 of file Brie.h.
template<unsigned Dim> template<unsigned D, typename Derived > friend class TrieBase friend
Definition at line 2126 of file Brie.h.
Field Documentation
template<unsigned Dim> store_type souffle::Trie< Dim >::store private
Definition at line 2158 of file Brie.h.
Referenced by souffle::Trie< Dim-1 >::insertAll().
The documentation for this class was generated from the following file:
Brie.h