souffle: souffle::TupleRef Class Reference
souffle::TupleRef Class Reference
A type-erased reference to tuples.
#include <LVMIndex.h>
Public Member Functions
template<std::size_t Arity>
const ram::Tuple< RamDomain, Arity > & asTuple () const
const RamDomain * getBase () const
bool operator== (const TupleRef &other) const
const RamDomain & operator[] (std::size_t i) const
Provides access to tuple components.
std::size_t size () const
Obtains the arity of the referenced tuple.
TupleRef ()=default
TupleRef (const RamDomain *base, std::size_t arity)
Creates a tuple reference from some externally maintained.
template<std::size_t Arity>
TupleRef (const ram::Tuple< RamDomain, Arity > &tuple)
A constructor supporting the implicit conversion of a tuple into a reference.
TupleRef (const DynTuple &tuple)
Private Attributes
std::size_t arity = 0
const RamDomain * base {}
Friends
std::ostream & operator<< (std::ostream &out, TupleRef ref)
Detailed Description
A type-erased reference to tuples.
The reference does not own the referenced data. It is thus very light-weight to create and forward.
Definition at line 61 of file LVMIndex.h.
Constructor & Destructor Documentation
souffle::TupleRef::TupleRef () default
souffle::TupleRef::TupleRef (const RamDomain * base, std::size_t arity) inline
Creates a tuple reference from some externally maintained.
Definition at line 74 of file LVMIndex.h.
 : base(base), arity(arity) {}
template<std::size_t Arity> souffle::TupleRef::TupleRef (const ram::Tuple< RamDomain, Arity > & tuple) inline
A constructor supporting the implicit conversion of a tuple into a reference.
Definition at line 81 of file LVMIndex.h.
 : TupleRef(&tuple[0], Arity) {}
souffle::TupleRef::TupleRef (const DynTuple & tuple) inline
Definition at line 83 of file LVMIndex.h.
 : TupleRef(&tuple[0], tuple.size()) {}
Member Function Documentation
template<std::size_t Arity> const ram::Tuple<RamDomain, Arity>& souffle::TupleRef::asTuple () const inline
Definition at line 86 of file LVMIndex.h.
References base.
Referenced by souffle::GenericIndex< btree_set< ram::Tuple< RamDomain, Arity >, comparator< Arity > > >::contains(), souffle::GenericIndex< btree_set< ram::Tuple< RamDomain, Arity >, comparator< Arity > > >::insert(), and souffle::GenericIndex< btree_set< ram::Tuple< RamDomain, Arity >, comparator< Arity > > >::range().
{
         assert(arity == Arity);
         return *reinterpret_cast<const ram::Tuple<RamDomain, Arity>*>(base);
     }
const RamDomain* souffle::TupleRef::getBase () const inline
Definition at line 101 of file LVMIndex.h.
References base.
{
         return base;
     }
bool souffle::TupleRef::operator== (const TupleRef & other) const inline
Definition at line 112 of file LVMIndex.h.
References arity, arity, base, i, and souffle::operator<<().
{
         if (arity != other.arity) {
             return false;
         }
         for (size_t i = 0; i < arity; ++i) {
             if (base[i] != other[i]) {
                 return false;
             }
         }
         return true;
     }
const RamDomain& souffle::TupleRef::operator[] (std::size_t i) const inline
Provides access to tuple components.
Definition at line 108 of file LVMIndex.h.
References base, and i.
{
         return base[i];
     }
std::size_t souffle::TupleRef::size () const inline
Obtains the arity of the referenced tuple.
Definition at line 94 of file LVMIndex.h.
References arity.
Referenced by souffle::NullaryIndex::contains(), souffle::NullaryIndex::insert(), and souffle::operator<<().
{
         return arity;
     }
Friends And Related Function Documentation
std::ostream& operator<< (std::ostream & out, TupleRef ref) friend
Definition at line 22 of file LVMIndex.cpp.
{
     out << "[";
     for (std::size_t i = 0; i < ref.size(); i++) {
         if (i > 0) {
             out << ',';
         }
         out << ref[i];
     }
     return out << "]";
 }
Field Documentation
std::size_t souffle::TupleRef::arity = 0 private
Definition at line 66 of file LVMIndex.h.
Referenced by operator==().
const RamDomain* souffle::TupleRef::base {} private
Definition at line 63 of file LVMIndex.h.
The documentation for this class was generated from the following file:
LVMIndex.h