souffle: souffle::RamBinRelationStatement Class Reference
souffle::RamBinRelationStatement Class Reference
Abstract class for a binary relation.
#include <RamStatement.h>
Public Member Functions
void apply (const RamNodeMapper &map) override
Apply the mapper to all child nodes.
std::vector< const RamNode * > getChildNodes () const override
Obtain list of all embedded child nodes.
const RamRelation & getFirstRelation () const
Get first relation.
const RamRelation & getSecondRelation () const
Get second relation.
RamBinRelationStatement (std::unique_ptr< RamRelationReference > f, std::unique_ptr< RamRelationReference > s)
Public Member Functions inherited from souffle::RamStatement
RamStatement * clone () const override=0
Create a clone (i.e.
virtual void print (std::ostream &os, int tabpos) const =0
Pretty print with indentation.
void print (std::ostream &os) const override
Print RAM node.
Public Member Functions inherited from souffle::RamNode
bool operator!= (const RamNode &other) const
Inequality check for two RAM nodes.
bool operator== (const RamNode &other) const
Equivalence check for two RAM nodes.
RamNode ()=default
virtual ~RamNode ()=default
Protected Member Functions
bool equal (const RamNode &node) const override
Equality check for two RAM nodes.
Protected Attributes
std::unique_ptr< RamRelationReference > first
first argument of binary statement
std::unique_ptr< RamRelationReference > second
second argument of binary statement
Detailed Description
Abstract class for a binary relation.
Comprises two RamRelations
Definition at line 269 of file RamStatement.h.
Constructor & Destructor Documentation
souffle::RamBinRelationStatement::RamBinRelationStatement (std::unique_ptr< RamRelationReference > f, std::unique_ptr< RamRelationReference > s) inline
Definition at line 271 of file RamStatement.h.
References i.
             : first(std::move(f)), second(std::move(s)) {
         assert(first->get()->getArity() == second->get()->getArity() && "mismatching relations");
         for (size_t i = 0; i < first->get()->getArity(); i++) {
             assert(first->get()->getArgTypeQualifier(i) == second->get()->getArgTypeQualifier(i) &&
                     "mismatching type");
         }
     }
Member Function Documentation
void souffle::RamBinRelationStatement::apply (const RamNodeMapper & mapper) inline override virtual
Apply the mapper to all child nodes.
Reimplemented from souffle::RamNode.
Definition at line 296 of file RamStatement.h.
{
         first = map(std::move(first));
         second = map(std::move(second));
     }
bool souffle::RamBinRelationStatement::equal (const RamNode & other) const inline override protected virtual
Equality check for two RAM nodes.
Default action is that nothing needs to be checked.
Reimplemented from souffle::RamNode.
Reimplemented in souffle::RamSwap, and souffle::RamMerge.
Definition at line 308 of file RamStatement.h.
References getFirstRelation().
Referenced by souffle::RamMerge::equal(), and souffle::RamSwap::equal().
{
         assert(nullptr != dynamic_cast<const RamBinRelationStatement*>(&node));
         const auto& other = static_cast<const RamBinRelationStatement&>(node);
         return getFirstRelation() == other.getFirstRelation() &&
                getSecondRelation() == other.getSecondRelation();
     }
std::vector<const RamNode*> souffle::RamBinRelationStatement::getChildNodes () const inline override virtual
Obtain list of all embedded child nodes.
Reimplemented from souffle::RamNode.
Definition at line 292 of file RamStatement.h.
{
         return {first.get(), second.get()};
     }
const RamRelation& souffle::RamBinRelationStatement::getFirstRelation () const inline
Get first relation.
Definition at line 281 of file RamStatement.h.
Referenced by souffle::Synthesiser::emitCode(), equal(), souffle::RAMI::evalStmt(), and souffle::LVMGenerator::visitSwap().
{
         assert(first != nullptr && "First relation is a null-pointer");
         return *first->get();
     }
const RamRelation& souffle::RamBinRelationStatement::getSecondRelation () const inline
Get second relation.
Definition at line 287 of file RamStatement.h.
Referenced by souffle::Synthesiser::emitCode(), souffle::RAMI::evalStmt(), and souffle::LVMGenerator::visitSwap().
{
         assert(second != nullptr && "Second relation is a null-pointer");
         return *second->get();
     }
Field Documentation
std::unique_ptr<RamRelationReference> souffle::RamBinRelationStatement::first protected
first argument of binary statement
Definition at line 303 of file RamStatement.h.
std::unique_ptr<RamRelationReference> souffle::RamBinRelationStatement::second protected
second argument of binary statement
Definition at line 306 of file RamStatement.h.
The documentation for this class was generated from the following file:
RamStatement.h