souffle: souffle::RamNode Class Reference
souffle::RamNode Class Reference abstract
RamNode is a superclass for all RAM IR classes.
#include <RamNode.h>
Public Member Functions
virtual void apply (const RamNodeMapper &mapper)
Apply the mapper to all child nodes.
virtual RamNode * clone () const =0
Create a clone (i.e.
virtual std::vector< const RamNode * > getChildNodes () const
Obtain list of all embedded child nodes.
bool operator!= (const RamNode &other) const
Inequality check for two RAM nodes.
bool operator== (const RamNode &other) const
Equivalence check for two RAM nodes.
virtual void print (std::ostream &out=std::cout) const =0
Print RAM node.
RamNode ()=default
virtual ~RamNode ()=default
Protected Member Functions
virtual bool equal (const RamNode &other) const
Equality check for two RAM nodes.
Friends
std::ostream & operator<< (std::ostream &out, const RamNode &node)
Print RAM on a stream.
Detailed Description
RamNode is a superclass for all RAM IR classes.
Definition at line 34 of file RamNode.h.
Constructor & Destructor Documentation
souffle::RamNode::RamNode () default
virtual souffle::RamNode::~RamNode () virtual default
Member Function Documentation
virtual void souffle::RamNode::apply (const RamNodeMapper & mapper) inline virtual
Apply the mapper to all child nodes.
Reimplemented in souffle::RamSubroutineReturnValue, souffle::RamProject, souffle::RamStratum, souffle::RamDebugInfo, souffle::RamAbstractConditional, souffle::RamLogTimer, souffle::RamUnpackRecord, souffle::RamLogRelationTimer, souffle::RamIndexAggregate, souffle::RamAggregate, souffle::RamExit, souffle::RamLoop, souffle::RamIndexChoice, souffle::RamListStatement, souffle::RamQuery, souffle::RamChoice, souffle::RamFact, souffle::RamEmptinessCheck, souffle::RamPackRecord, souffle::RamAbstractExistenceCheck, souffle::RamBinRelationStatement, souffle::RamIndexOperation, souffle::RamConstraint, souffle::RamNegation, souffle::RamRelationOperation, souffle::RamProgram, souffle::RamConjunction, souffle::RamNestedOperation, souffle::RamAbstractOperator, and souffle::RamRelationStatement.
Definition at line 65 of file RamNode.h.
Referenced by souffle::RamProgram::clone(), souffle::RamLogSize::equal(), souffle::HoistAggregateTransformer::hoistAggregate(), souffle::HoistConditionsTransformer::hoistConditions(), and souffle::ParallelTransformer::parallelizeOperations().
 {}
virtual RamNode* souffle::RamNode::clone () const pure virtual
Create a clone (i.e.
deep copy) of this node
Implemented in souffle::RamSubroutineReturnValue, souffle::RamProject, souffle::RamLogSize, souffle::RamBreak, souffle::RamStratum, souffle::RamFilter, souffle::RamDebugInfo, souffle::RamLogTimer, souffle::RamUnpackRecord, souffle::RamLogRelationTimer, souffle::RamIndexAggregate, souffle::RamAggregate, souffle::RamExit, souffle::RamLoop, souffle::RamParallelIndexChoice, souffle::RamParallel, souffle::RamSequence, souffle::RamIndexChoice, souffle::RamParallelChoice, souffle::RamQuery, souffle::RamChoice, souffle::RamFact, souffle::RamEmptinessCheck, souffle::RamSubroutineArgument, souffle::RamProvenanceExistenceCheck, souffle::RamParallelIndexScan, souffle::RamSwap, souffle::RamExistenceCheck, souffle::RamPackRecord, souffle::RamIndexScan, souffle::RamMerge, souffle::RamUndefValue, souffle::RamAutoIncrement, souffle::RamNumber, souffle::RamDrop, souffle::RamConstraint, souffle::RamParallelScan, souffle::RamClear, souffle::RamTupleElement, souffle::RamScan, souffle::RamStore, souffle::RamNegation, souffle::RamUserDefinedOperator, souffle::RamRelationReference, souffle::RamLoad, souffle::RamRelation, souffle::RamConjunction, souffle::RamIntrinsicOperator, souffle::RamProgram, souffle::RamCreate, souffle::RamFalse, souffle::RamTrue, souffle::RamStatement, souffle::RamOperation, souffle::RamCondition, and souffle::RamExpression.
Referenced by operator!=().
virtual bool souffle::RamNode::equal (const RamNode & other) const inline protected virtual
Equality check for two RAM nodes.
Default action is that nothing needs to be checked.
Reimplemented in souffle::RamSubroutineReturnValue, souffle::RamProject, souffle::RamLogSize, souffle::RamBreak, souffle::RamStratum, souffle::RamFilter, souffle::RamDebugInfo, souffle::RamAbstractConditional, souffle::RamLogTimer, souffle::RamUnpackRecord, souffle::RamLogRelationTimer, souffle::RamIndexAggregate, souffle::RamAggregate, souffle::RamExit, souffle::RamLoop, souffle::RamParallel, souffle::RamSequence, souffle::RamIndexChoice, souffle::RamListStatement, souffle::RamQuery, souffle::RamChoice, souffle::RamFact, souffle::RamEmptinessCheck, souffle::RamSubroutineArgument, souffle::RamSwap, souffle::RamPackRecord, souffle::RamMerge, souffle::RamAbstractExistenceCheck, souffle::RamIndexOperation, souffle::RamBinRelationStatement, souffle::RamNumber, souffle::RamConstraint, souffle::RamTupleElement, souffle::RamStore, souffle::RamNegation, souffle::RamUserDefinedOperator, souffle::RamRelationOperation, souffle::RamRelationReference, souffle::RamProgram, souffle::RamLoad, souffle::RamConjunction, souffle::RamTupleOperation, souffle::RamIntrinsicOperator, souffle::RamRelation, souffle::RamAbstractLoadStore, souffle::RamNestedOperation, souffle::RamAbstractOperator, and souffle::RamRelationStatement.
Definition at line 92 of file RamNode.h.
Referenced by souffle::RamLogSize::equal(), and operator==().
{
         return true;
     }
virtual std::vector<const RamNode*> souffle::RamNode::getChildNodes () const inline virtual
Obtain list of all embedded child nodes.
Reimplemented in souffle::RamSubroutineReturnValue, souffle::RamProject, souffle::RamStratum, souffle::RamDebugInfo, souffle::RamAbstractConditional, souffle::RamLogTimer, souffle::RamUnpackRecord, souffle::RamLogRelationTimer, souffle::RamIndexAggregate, souffle::RamAggregate, souffle::RamExit, souffle::RamLoop, souffle::RamIndexChoice, souffle::RamListStatement, souffle::RamQuery, souffle::RamChoice, souffle::RamEmptinessCheck, souffle::RamFact, souffle::RamPackRecord, souffle::RamAbstractExistenceCheck, souffle::RamBinRelationStatement, souffle::RamIndexOperation, souffle::RamConstraint, souffle::RamNegation, souffle::RamRelationOperation, souffle::RamTupleOperation, souffle::RamConjunction, souffle::RamNestedOperation, souffle::RamAbstractOperator, souffle::RamRelationStatement, and souffle::RamProgram.
Definition at line 70 of file RamNode.h.
References print().
Referenced by souffle::RamLogSize::equal(), and souffle::visitDepthFirstPreOrder().
{
         return {};
     }
bool souffle::RamNode::operator!= (const RamNode & other) const inline
Inequality check for two RAM nodes.
Definition at line 53 of file RamNode.h.
References clone().
{
         return !(*this == other);
     }
bool souffle::RamNode::operator== (const RamNode & other) const inline
Equivalence check for two RAM nodes.
Definition at line 46 of file RamNode.h.
References equal().
{
         return this == &other || (typeid(*this) == typeid(other) && equal(other));
     }
virtual void souffle::RamNode::print (std::ostream & out = std::cout) const pure virtual
Print RAM node.
Implemented in souffle::RamEmptinessCheck, souffle::RamSubroutineArgument, souffle::RamProvenanceExistenceCheck, souffle::RamExistenceCheck, souffle::RamPackRecord, souffle::RamUndefValue, souffle::RamAutoIncrement, souffle::RamNumber, souffle::RamConstraint, souffle::RamTupleElement, souffle::RamNegation, souffle::RamRelationReference, souffle::RamUserDefinedOperator, souffle::RamConjunction, souffle::RamRelation, souffle::RamIntrinsicOperator, souffle::RamFalse, souffle::RamProgram, souffle::RamTrue, souffle::RamStatement, and souffle::RamOperation.
Referenced by getChildNodes().
Friends And Related Function Documentation
std::ostream& operator<< (std::ostream & out, const RamNode & node) friend
Print RAM on a stream.
Definition at line 82 of file RamNode.h.
{
         node.print(out);
         return out;
     }
The documentation for this class was generated from the following file:
RamNode.h