souffle: souffle::RamChoice Class Reference
souffle::RamChoice Class Reference
Find a tuple in a relation such that a given condition holds.
#include <RamOperation.h>
Public Member Functions
void apply (const RamNodeMapper &map) override
Apply the mapper to all child nodes.
RamChoice * clone () const override
Create a clone (i.e.
std::vector< const RamNode * > getChildNodes () const override
Obtain list of all embedded child nodes.
void print (std::ostream &os, int tabpos) const override
Pretty print with indentation.
RamChoice (std::unique_ptr< RamRelationReference > rel, size_t ident, std::unique_ptr< RamCondition > cond, std::unique_ptr< RamOperation > nested, std::string profileText="")
Public Member Functions inherited from souffle::RamRelationOperation
const RamRelation & getRelation () const
Get search relation.
RamRelationOperation (std::unique_ptr< RamRelationReference > relRef, int ident, std::unique_ptr< RamOperation > nested, std::string profileText="")
Public Member Functions inherited from souffle::RamTupleOperation
int getTupleId () const
Get identifier.
RamTupleOperation (int ident, std::unique_ptr< RamOperation > nested, std::string profileText="")
void setTupleId (int id)
Set identifier.
Public Member Functions inherited from souffle::RamNestedOperation
RamOperation & getOperation () const
Get nested operation.
const std::string & getProfileText () const
Get profile text.
RamNestedOperation (std::unique_ptr< RamOperation > nested, std::string profileText="")
Public Member Functions inherited from souffle::RamOperation
void print (std::ostream &os) const override
Print RAM node.
Public Member Functions inherited from souffle::RamNode
bool operator!= (const RamNode &other) const
Inequality check for two RAM nodes.
bool operator== (const RamNode &other) const
Equivalence check for two RAM nodes.
RamNode ()=default
virtual ~RamNode ()=default
Public Member Functions inherited from souffle::RamAbstractChoice
void apply (const RamNodeMapper &map)
std::vector< const RamNode * > getChildNodes () const
const RamCondition & getCondition () const
Getter for the condition.
RamAbstractChoice (std::unique_ptr< RamCondition > cond)
Protected Member Functions
bool equal (const RamNode &node) const override
Equality check for two RAM nodes.
Protected Member Functions inherited from souffle::RamAbstractChoice
bool equal (const RamNode &node) const
Additional Inherited Members
Protected Attributes inherited from souffle::RamRelationOperation
std::unique_ptr< RamRelationReference > relationRef
Search relation.
Protected Attributes inherited from souffle::RamTupleOperation
int identifier
Identifier for the tuple, corresponding to its position in the loop nest.
Protected Attributes inherited from souffle::RamNestedOperation
std::unique_ptr< RamOperation > nestedOperation
Nested operation.
const std::string profileText
Text used by the profiler.
Protected Attributes inherited from souffle::RamAbstractChoice
std::unique_ptr< RamCondition > condition
Condition for which a tuple in the relation may hold.
Detailed Description
Find a tuple in a relation such that a given condition holds.
Only one tuple is returned (if one exists), even if multiple tuples satisfying the condition exist.
For example:
QUERY
 ...
  CHOICE t1 IN A WHERE (t1.x, t1.y) NOT IN A
    ...
Definition at line 449 of file RamOperation.h.
Constructor & Destructor Documentation
souffle::RamChoice::RamChoice (std::unique_ptr< RamRelationReference > rel, size_t ident, std::unique_ptr< RamCondition > cond, std::unique_ptr< RamOperation > nested, std::string profileText = "") inline
Definition at line 451 of file RamOperation.h.
             : RamRelationOperation(std::move(rel), ident, std::move(nested), std::move(profileText)),
               RamAbstractChoice(std::move(cond)) {}
Member Function Documentation
void souffle::RamChoice::apply (const RamNodeMapper & mapper) inline override virtual
Apply the mapper to all child nodes.
Reimplemented from souffle::RamRelationOperation.
Definition at line 465 of file RamOperation.h.
References souffle::RamRelationOperation::apply(), and souffle::RamAbstractChoice::apply().
{
         RamRelationOperation::apply(map);
         RamAbstractChoice::apply(map);
     }
RamChoice* souffle::RamChoice::clone () const inline override virtual
Create a clone (i.e.
deep copy) of this node
Implements souffle::RamOperation.
Reimplemented in souffle::RamParallelChoice.
Definition at line 470 of file RamOperation.h.
{
         return new RamChoice(std::unique_ptr<RamRelationReference>(relationRef->clone()), getTupleId(),
                 std::unique_ptr<RamCondition>(condition->clone()),
                 std::unique_ptr<RamOperation>(getOperation().clone()), getProfileText());
     }
bool souffle::RamChoice::equal (const RamNode & other) const inline override protected virtual
Equality check for two RAM nodes.
Default action is that nothing needs to be checked.
Reimplemented from souffle::RamRelationOperation.
Definition at line 481 of file RamOperation.h.
References souffle::RamRelationOperation::equal().
{
         assert(nullptr != dynamic_cast<const RamChoice*>(&node));
         const auto& other = static_cast<const RamChoice&>(node);
         return RamRelationOperation::equal(other) && getCondition() == other.getCondition();
     }
std::vector<const RamNode*> souffle::RamChoice::getChildNodes () const inline override virtual
Obtain list of all embedded child nodes.
Reimplemented from souffle::RamRelationOperation.
Definition at line 476 of file RamOperation.h.
References souffle::RamAbstractChoice::getChildNodes().
{
         return {nestedOperation.get(), relationRef.get(), RamAbstractChoice::getChildNodes().at(0)};
     }
void souffle::RamChoice::print (std::ostream & os, int tabpos) const inline override virtual
Pretty print with indentation.
Reimplemented from souffle::RamNestedOperation.
Reimplemented in souffle::RamParallelChoice.
Definition at line 456 of file RamOperation.h.
References souffle::RamNestedOperation::print(), and souffle::times().
{
         os << times(" ", tabpos);
         os << "CHOICE t" << getTupleId();
         os << " IN " << getRelation().getName();
         os << " WHERE " << getCondition();
         os << std::endl;
         RamRelationOperation::print(os, tabpos + 1);
     }
The documentation for this class was generated from the following file:
RamOperation.h