souffle: souffle::RamAbstractChoice Class Reference
souffle::RamAbstractChoice Class Reference
Abstract class for a choice operation.
#include <RamOperation.h>
Public Member Functions
void apply (const RamNodeMapper &map)
std::vector< const RamNode * > getChildNodes () const
const RamCondition & getCondition () const
Getter for the condition.
RamAbstractChoice (std::unique_ptr< RamCondition > cond)
Protected Member Functions
bool equal (const RamNode &node) const
Protected Attributes
std::unique_ptr< RamCondition > condition
Condition for which a tuple in the relation may hold.
Detailed Description
Abstract class for a choice operation.
Finding a single tuple, if it exists, such that a condition holds.
Definition at line 405 of file RamOperation.h.
Constructor & Destructor Documentation
souffle::RamAbstractChoice::RamAbstractChoice (std::unique_ptr< RamCondition > cond) inline
Definition at line 407 of file RamOperation.h.
 : condition(std::move(cond)) {}
Member Function Documentation
void souffle::RamAbstractChoice::apply (const RamNodeMapper & map) inline
Definition at line 415 of file RamOperation.h.
Referenced by souffle::RamChoice::apply(), and souffle::RamIndexChoice::apply().
{
         condition = map(std::move(condition));
     }
bool souffle::RamAbstractChoice::equal (const RamNode & node) const inline protected
Definition at line 427 of file RamOperation.h.
References getCondition().
{
         assert(nullptr != dynamic_cast<const RamAbstractChoice*>(&node));
         const auto& other = dynamic_cast<const RamAbstractChoice*>(&node);
         return getCondition() == other->getCondition();
     }
std::vector<const RamNode*> souffle::RamAbstractChoice::getChildNodes () const inline
Definition at line 419 of file RamOperation.h.
Referenced by souffle::RamChoice::getChildNodes(), and souffle::RamIndexChoice::getChildNodes().
{
         return {condition.get()};
     }
const RamCondition& souffle::RamAbstractChoice::getCondition () const inline
Getter for the condition.
Definition at line 410 of file RamOperation.h.
Referenced by souffle::Synthesiser::emitCode(), equal(), souffle::RAMI::evalOp(), souffle::RamLevelAnalysis::getLevel(), souffle::LVMGenerator::visitChoice(), and souffle::LVMGenerator::visitIndexChoice().
{
         assert(condition != nullptr && "condition of choice is a null-pointer");
         return *condition;
     }
Field Documentation
std::unique_ptr<RamCondition> souffle::RamAbstractChoice::condition protected
Condition for which a tuple in the relation may hold.
Definition at line 425 of file RamOperation.h.
The documentation for this class was generated from the following file:
RamOperation.h