souffle: souffle::RamAbstractLoadStore Class Reference
souffle::RamAbstractLoadStore Class Reference
Abstract class for load/store for a relation.
#include <RamStatement.h>
Public Member Functions
const std::vector< IODirectives > & getIODirectives () const
Get load directives.
RamAbstractLoadStore (std::unique_ptr< RamRelationReference > relRef, std::vector< IODirectives > ioDirectives)
Public Member Functions inherited from souffle::RamRelationStatement
void apply (const RamNodeMapper &map) override
Apply the mapper to all child nodes.
std::vector< const RamNode * > getChildNodes () const override
Obtain list of all embedded child nodes.
const RamRelation & getRelation () const
Get RAM relation.
RamRelationStatement (std::unique_ptr< RamRelationReference > relRef)
Public Member Functions inherited from souffle::RamStatement
RamStatement * clone () const override=0
Create a clone (i.e.
virtual void print (std::ostream &os, int tabpos) const =0
Pretty print with indentation.
void print (std::ostream &os) const override
Print RAM node.
Public Member Functions inherited from souffle::RamNode
bool operator!= (const RamNode &other) const
Inequality check for two RAM nodes.
bool operator== (const RamNode &other) const
Equivalence check for two RAM nodes.
RamNode ()=default
virtual ~RamNode ()=default
Protected Member Functions
bool equal (const RamNode &node) const override
Equality check for two RAM nodes.
Protected Attributes
const std::vector< IODirectives > ioDirectives
Load directives of a relation.
Protected Attributes inherited from souffle::RamRelationStatement
std::unique_ptr< RamRelationReference > relationRef
Relation.
Detailed Description
Abstract class for load/store for a relation.
This class represents read/write actions on IO directives
Definition at line 114 of file RamStatement.h.
Constructor & Destructor Documentation
souffle::RamAbstractLoadStore::RamAbstractLoadStore (std::unique_ptr< RamRelationReference > relRef, std::vector< IODirectives > ioDirectives) inline
Definition at line 116 of file RamStatement.h.
             : RamRelationStatement(std::move(relRef)), ioDirectives(std::move(ioDirectives)) {}
Member Function Documentation
bool souffle::RamAbstractLoadStore::equal (const RamNode & other) const inline override protected virtual
Equality check for two RAM nodes.
Default action is that nothing needs to be checked.
Reimplemented from souffle::RamRelationStatement.
Reimplemented in souffle::RamStore, and souffle::RamLoad.
Definition at line 128 of file RamStatement.h.
References souffle::RamRelationStatement::equal().
Referenced by souffle::RamLoad::equal(), and souffle::RamStore::equal().
{
         assert(nullptr != dynamic_cast<const RamAbstractLoadStore*>(&node));
         const auto& other = static_cast<const RamAbstractLoadStore&>(node);
         return RamRelationStatement::equal(other) && getIODirectives() == other.getIODirectives();
     }
const std::vector<IODirectives>& souffle::RamAbstractLoadStore::getIODirectives () const inline
Get load directives.
Definition at line 120 of file RamStatement.h.
Referenced by souffle::Synthesiser::emitCode(), souffle::RAMI::evalStmt(), souffle::Synthesiser::generateCode(), souffle::LVMGenerator::visitLoad(), and souffle::LVMGenerator::visitStore().
{
         return ioDirectives;
     }
Field Documentation
const std::vector<IODirectives> souffle::RamAbstractLoadStore::ioDirectives protected
Load directives of a relation.
Definition at line 126 of file RamStatement.h.
The documentation for this class was generated from the following file:
RamStatement.h