souffle: souffle::HoistAggregateTransformer Class Reference
souffle::HoistAggregateTransformer Class Reference
#include <RamTransforms.h>
Public Member Functions
std::string getName () const override
get name of the transformer flag reporting whether the RAM program has changed
bool hoistAggregate (RamProgram &program)
Apply hoistAggregate to the whole program.
Public Member Functions inherited from souffle::RamTransformer
bool apply (RamTranslationUnit &translationUnit)
apply the transformer to a translation unit translationUnit that will be transformed.
RamTransformer ()=default
virtual ~RamTransformer ()=default
Protected Member Functions
bool transform (RamTranslationUnit &translationUnit) override
transform the translation unit / used by apply translationUnit that will be transformed.
Protected Attributes
RamLevelAnalysis * rla {nullptr}
Detailed Description
Definition at line 461 of file RamTransforms.h.
Member Function Documentation
std::string souffle::HoistAggregateTransformer::getName () const inline override virtual
get name of the transformer flag reporting whether the RAM program has changed
Get name of transformer
Implements souffle::RamTransformer.
Definition at line 463 of file RamTransforms.h.
{
         return "HoistAggregateTransformer";
     }
bool souffle::HoistAggregateTransformer::hoistAggregate (RamProgram & program)
Apply hoistAggregate to the whole program.
Parameters
RAM program
Returns
A flag indicating whether the RAM program has been changed.
Pushes an Aggregate up the loop nest if possible
Definition at line 560 of file RamTransforms.cpp.
References souffle::RamTransformer::apply(), souffle::RamNode::apply(), souffle::RamNestedOperation::apply(), i, souffle::makeLambdaRamMapper(), and souffle::visitDepthFirst().
{
     // flag to determine whether the RAM program has changed
     bool changed = false;
     // hoist aggregate if doesn't depend on anything
     visitDepthFirst(program, [&](const RamQuery& query) {
         int currLevel = -1;
         int oldLevel = -1;
         bool hoist = false;
         bool newIndex = false;
         // Fields for new aggregate
         AggregateFunction newFun;
         const RamRelation* newRef;
         RamExpression* newExp;
         RamCondition* newCond;
         std::vector<RamExpression*> newPattern;
         // Tracking aggregates seen to determine whether to
         // hoist or not
         std::vector<int> aggIds;
         // Removing an aggregate that can be hoisted if it exists
         std::function<std::unique_ptr<RamNode>(std::unique_ptr<RamNode>)> aggRemover =
                 [&](std::unique_ptr<RamNode> node) -> std::unique_ptr<RamNode> {
             // Checking that there exists an aggregate to hoist
             // If so, remove the aggregate from the loop nest
             if (const RamAggregate* agg = dynamic_cast<RamAggregate*>(node.get())) {
                 aggIds.push_back(agg->getTupleId());
                 // assuming that RamTupleOperations have tupleIds 0, 1, 2, ...
                 if (!hoist && rla->getLevel(agg) < agg->getTupleId() - 1) {
                     // If all tuple ops between the rla->getLevel(agg) and agg
                     // are aggregates, then we do not transform
                     bool allAggragates = true;
                     for (int i = rla->getLevel(agg) + 1; i <= agg->getTupleId(); i++) {
                         if (!(std::find(aggIds.begin(), aggIds.end(), i) != aggIds.end())) {
                             currLevel = i - 1;
                             allAggragates = false;
                             break;
                         }
                     }
                     if (!allAggragates) {
                         hoist = true;
                         changed = true;
                         oldLevel = agg->getTupleId();
                         // Copying fields
                         newFun = agg->getFunction();
                         newRef = &agg->getRelation();
                         newExp = dynamic_cast<RamExpression*>(agg->getExpression().clone());
                         newCond = dynamic_cast<RamCondition*>(agg->getCondition().clone());
                         node->apply(makeLambdaRamMapper(aggRemover));
                         return std::unique_ptr<RamOperation>(agg->getOperation().clone());
                     }
                 }
             } else if (const RamIndexAggregate* agg = dynamic_cast<RamIndexAggregate*>(node.get())) {
                 aggIds.push_back(agg->getTupleId());
                 if (!hoist && rla->getLevel(agg) < agg->getTupleId() - 1) {
                     // If all tuple ops above agg in the loop nest are also aggregates
                     // then we do not transform
                     bool allAggragates = true;
                     for (int i = rla->getLevel(agg) + 1; i <= agg->getTupleId(); i++) {
                         if (!(std::find(aggIds.begin(), aggIds.end(), i) != aggIds.end())) {
                             currLevel = i - 1;
                             allAggragates = false;
                             break;
                         }
                     }
                     if (!allAggragates) {
                         hoist = true;
                         changed = true;
                         newIndex = true;
                         oldLevel = agg->getTupleId();
                         // Copying fields
                         newFun = agg->getFunction();
                         newRef = &agg->getRelation();
                         newExp = dynamic_cast<RamExpression*>(agg->getExpression().clone());
                         newCond = dynamic_cast<RamCondition*>(agg->getCondition().clone());
                         newPattern = agg->getRangePattern();
                     }
                 }
             }
             node->apply(makeLambdaRamMapper(aggRemover));
             return node;
         };
         const_cast<RamQuery*>(&query)->apply(makeLambdaRamMapper(aggRemover));
         bool added = false;
         // Adding back the aggregate if one was removed before
         std::function<std::unique_ptr<RamNode>(std::unique_ptr<RamNode>)> aggAdder =
                 [&](std::unique_ptr<RamNode> node) -> std::unique_ptr<RamNode> {
             if (auto* search = dynamic_cast<RamTupleOperation*>(node.get())) {
                 if (!added && search->getTupleId() == currLevel - 1) {
                     added = true;
                     auto* op = dynamic_cast<RamNestedOperation*>(search);
                     // Finding the operation right before the RamTupleOperation
                     // with tupleId = aggregate's tupleId - 1
                     while (dynamic_cast<RamTupleOperation*>(&op->getOperation()) != nullptr) {
                         op = dynamic_cast<RamNestedOperation*>(&op->getOperation());
                     }
                     if (newIndex) {
                         // RamIndexAggregate
                         std::vector<std::unique_ptr<RamExpression>> queryPattern;
                         for (const RamExpression* cur : newPattern) {
                             if (nullptr != cur) {
                                 queryPattern.push_back(std::unique_ptr<RamExpression>(cur->clone()));
                             } else {
                                 queryPattern.push_back(nullptr);
                             }
                         }
                         node->apply(makeLambdaRamMapper(aggAdder));
                         return std::make_unique<RamIndexAggregate>(
                                 std::unique_ptr<RamOperation>(op->getOperation().clone()), newFun,
                                 std::make_unique<RamRelationReference>(newRef),
                                 std::unique_ptr<RamExpression>(newExp),
                                 std::unique_ptr<RamCondition>(newCond), std::move(queryPattern), oldLevel);
                     } else {
                         // RamAggregate
                         node->apply(makeLambdaRamMapper(aggAdder));
                         return std::make_unique<RamAggregate>(
                                 std::unique_ptr<RamOperation>(op->getOperation().clone()), newFun,
                                 std::make_unique<RamRelationReference>(newRef),
                                 std::unique_ptr<RamExpression>(newExp),
                                 std::unique_ptr<RamCondition>(newCond), oldLevel);
                     }
                 }
             }
             node->apply(makeLambdaRamMapper(aggAdder));
             return node;
         };
         std::function<std::unique_ptr<RamNode>(std::unique_ptr<RamNode>)> aggTopAdder =
                 [&](std::unique_ptr<RamNode> node) -> std::unique_ptr<RamNode> {
             if (nullptr != dynamic_cast<RamOperation*>(node.get())) {
                 if (newIndex) {
                     // RamIndexAggregate
                     std::vector<std::unique_ptr<RamExpression>> queryPattern;
                     for (const RamExpression* cur : newPattern) {
                         if (nullptr != cur) {
                             queryPattern.push_back(std::unique_ptr<RamExpression>(cur->clone()));
                         } else {
                             queryPattern.push_back(nullptr);
                         }
                     }
                     return std::make_unique<RamIndexAggregate>(
                             std::unique_ptr<RamOperation>(dynamic_cast<RamOperation*>(node.release())),
                             newFun, std::make_unique<RamRelationReference>(newRef),
                             std::unique_ptr<RamExpression>(newExp), std::unique_ptr<RamCondition>(newCond),
                             std::move(queryPattern), oldLevel);
                 } else {
                     // RamAggregate
                     return std::make_unique<RamAggregate>(
                             std::unique_ptr<RamOperation>(dynamic_cast<RamOperation*>(node.release())),
                             newFun, std::make_unique<RamRelationReference>(newRef),
                             std::unique_ptr<RamExpression>(newExp), std::unique_ptr<RamCondition>(newCond),
                             oldLevel);
                 }
             }
             return node;
         };
         if (hoist) {
             if (currLevel < 1) {
                 // insert at the top of the loop nest
                 const_cast<RamQuery*>(&query)->apply(makeLambdaRamMapper(aggTopAdder));
             } else {
                 const_cast<RamQuery*>(&query)->apply(makeLambdaRamMapper(aggAdder));
             }
         }
     });
     return changed;
 }
bool souffle::HoistAggregateTransformer::transform (RamTranslationUnit & translationUnit) inline override protected virtual
transform the translation unit / used by apply translationUnit that will be transformed.
flag reporting whether the RAM program has changed
Implements souffle::RamTransformer.
Definition at line 478 of file RamTransforms.h.
References souffle::RamTranslationUnit::getAnalysis(), and souffle::RamTranslationUnit::getProgram().
{
         rla = translationUnit.getAnalysis<RamLevelAnalysis>();
         return hoistAggregate(*translationUnit.getProgram());
     }
Field Documentation
RamLevelAnalysis* souffle::HoistAggregateTransformer::rla {nullptr} protected
Definition at line 477 of file RamTransforms.h.
The documentation for this class was generated from the following files:
RamTransforms.h
RamTransforms.cpp