souffle: souffle::RAMIRelInterface Class Reference
souffle::RAMIRelInterface Class Reference
Wrapper class for interpreter relations.
#include <RAMIProgInterface.h>
Data Structures
class iterator_base
Iterator wrapper class.
Public Member Functions
iterator begin () const override
Iterator to first tuple.
bool contains (const tuple &t) const override
Check whether tuple exists.
iterator end () const override
Iterator to last tuple.
size_t getArity () const override
Get arity.
const char * getAttrName (size_t idx) const override
Get attribute name.
const char * getAttrType (size_t idx) const override
Get attribute type.
std::string getName () const override
Get name.
SymbolTable & getSymbolTable () const override
Get symbol table.
void insert (const tuple &t) override
Insert tuple.
void purge () override
Eliminate all the tuples in relation.
RAMIRelInterface (RAMIRelation &r, SymbolTable &s, std::string n, std::vector< std::string > t, std::vector< std::string > an, uint32_t i)
std::size_t size () const override
Get number of tuples in relation.
~RAMIRelInterface () override=default
Public Member Functions inherited from souffle::Relation
std::string getSignature ()
virtual ~Relation ()=default
Private Attributes
std::vector< std::string > attrNames
Attribute Names.
uint32_t id
Unique id for wrapper.
std::string name
Name of relation.
RAMIRelation & relation
Wrapped interpreter relation.
SymbolTable & symTable
Symbol table.
std::vector< std::string > types
Attribute type.
Detailed Description
Wrapper class for interpreter relations.
Definition at line 31 of file RAMIProgInterface.h.
Constructor & Destructor Documentation
souffle::RAMIRelInterface::RAMIRelInterface (RAMIRelation & r, SymbolTable & s, std::string n, std::vector< std::string > t, std::vector< std::string > an, uint32_t i) inline
Definition at line 33 of file RAMIProgInterface.h.
References ~RAMIRelInterface().
             : relation(r), symTable(s), name(std::move(n)), types(std::move(t)), attrNames(std::move(an)),
               id(i) {}
souffle::RAMIRelInterface::~RAMIRelInterface () override default
Referenced by RAMIRelInterface().
Member Function Documentation
iterator souffle::RAMIRelInterface::begin () const inline override virtual
Iterator to first tuple.
Implements souffle::Relation.
Definition at line 50 of file RAMIProgInterface.h.
References souffle::RAMIRelation::begin(), and relation.
{
         return RAMIRelInterface::iterator(new RAMIRelInterface::iterator_base(id, this, relation.begin()));
     }
bool souffle::RAMIRelInterface::contains (const tuple & t) const inline override virtual
Check whether tuple exists.
Implements souffle::Relation.
Definition at line 45 of file RAMIProgInterface.h.
References souffle::tuple::data, souffle::RAMIRelation::exists(), and relation.
{
         return relation.exists(t.data);
     }
iterator souffle::RAMIRelInterface::end () const inline override virtual
Iterator to last tuple.
Implements souffle::Relation.
Definition at line 55 of file RAMIProgInterface.h.
References souffle::RAMIRelation::end(), and relation.
{
         return RAMIRelInterface::iterator(new RAMIRelInterface::iterator_base(id, this, relation.end()));
     }
size_t souffle::RAMIRelInterface::getArity () const inline override virtual
Get arity.
Implements souffle::Relation.
Definition at line 65 of file RAMIProgInterface.h.
References souffle::RAMIRelation::getArity(), and relation.
Referenced by getAttrName(), getAttrType(), and souffle::RAMIRelInterface::iterator_base::operator*().
{
         return relation.getArity();
     }
const char* souffle::RAMIRelInterface::getAttrName (size_t idx) const inline override virtual
Get attribute name.
Implements souffle::Relation.
Definition at line 81 of file RAMIProgInterface.h.
References attrNames, and getArity().
{
         assert(idx < getArity() && "exceeded tuple size");
         return attrNames[idx].c_str();
     }
const char* souffle::RAMIRelInterface::getAttrType (size_t idx) const inline override virtual
Get attribute type.
Implements souffle::Relation.
Definition at line 75 of file RAMIProgInterface.h.
References getArity(), and types.
Referenced by souffle::RAMIRelInterface::iterator_base::operator*().
{
         assert(idx < getArity() && "exceeded tuple size");
         return types[idx].c_str();
     }
std::string souffle::RAMIRelInterface::getName () const inline override virtual
Get name.
Implements souffle::Relation.
Definition at line 60 of file RAMIProgInterface.h.
References name.
{
         return name;
     }
SymbolTable& souffle::RAMIRelInterface::getSymbolTable () const inline override virtual
Get symbol table.
Implements souffle::Relation.
Definition at line 70 of file RAMIProgInterface.h.
References symTable.
Referenced by souffle::RAMIRelInterface::iterator_base::operator*().
{
         return symTable;
     }
void souffle::RAMIRelInterface::insert (const tuple & t) inline override virtual
Insert tuple.
Implements souffle::Relation.
Definition at line 40 of file RAMIProgInterface.h.
References souffle::tuple::data, souffle::RAMIRelation::insert(), and relation.
{
         relation.insert(t.data);
     }
void souffle::RAMIRelInterface::purge () inline override virtual
Eliminate all the tuples in relation.
Implements souffle::Relation.
Definition at line 92 of file RAMIProgInterface.h.
References souffle::RAMIRelation::purge(), and relation.
{
         relation.purge();
     }
std::size_t souffle::RAMIRelInterface::size () const inline override virtual
Get number of tuples in relation.
Implements souffle::Relation.
Definition at line 87 of file RAMIProgInterface.h.
References relation, and souffle::RAMIRelation::size().
{
         return relation.size();
     }
Field Documentation
std::vector<std::string> souffle::RAMIRelInterface::attrNames private
Attribute Names.
Definition at line 165 of file RAMIProgInterface.h.
Referenced by getAttrName(), and souffle::RAMIProgInterface::RAMIProgInterface().
uint32_t souffle::RAMIRelInterface::id private
Unique id for wrapper.
Definition at line 168 of file RAMIProgInterface.h.
std::string souffle::RAMIRelInterface::name private
Name of relation.
Definition at line 159 of file RAMIProgInterface.h.
Referenced by getName(), and souffle::RAMIProgInterface::RAMIProgInterface().
RAMIRelation& souffle::RAMIRelInterface::relation private
Wrapped interpreter relation.
Definition at line 153 of file RAMIProgInterface.h.
Referenced by begin(), contains(), end(), getArity(), insert(), purge(), and size().
SymbolTable& souffle::RAMIRelInterface::symTable private
Symbol table.
Definition at line 156 of file RAMIProgInterface.h.
Referenced by getSymbolTable(), and souffle::RAMIProgInterface::getSymbolTable().
std::vector<std::string> souffle::RAMIRelInterface::types private
Attribute type.
Definition at line 162 of file RAMIProgInterface.h.
Referenced by getAttrType(), and souffle::RAMIProgInterface::RAMIProgInterface().
The documentation for this class was generated from the following file:
RAMIProgInterface.h