souffle: souffle::LVMIndex Class Reference
souffle::LVMIndex Class Reference abstract
An index is an abstraction of a data structure.
#include <LVMIndex.h>
Public Member Functions
virtual void clear ()=0
Clears the content of this index, turning it empty.
virtual bool contains (const TupleRef &tuple) const =0
Tests whether the given tuple is present in this index or not.
virtual bool empty () const =0
Tests whether this index is empty or not.
virtual size_t getArity () const =0
Obtains the arity of the given index.
virtual bool insert (const TupleRef &tuple)=0
Inserts a tuple into this index.
virtual void insert (const LVMIndex &src)=0
Inserts all elements of the given index.
virtual Stream range (const TupleRef &low, const TupleRef &high) const =0
Returns a stream covering the elements.
virtual Stream scan () const =0
Returns a stream covering the entire index content.
virtual std::size_t size () const =0
Obtains the number of elements stored in this index.
virtual ~LVMIndex ()=default
Detailed Description
An index is an abstraction of a data structure.
Definition at line 321 of file LVMIndex.h.
Constructor & Destructor Documentation
virtual souffle::LVMIndex::~LVMIndex () virtual default
Member Function Documentation
virtual void souffle::LVMIndex::clear () pure virtual
Clears the content of this index, turning it empty.
Implemented in souffle::IndirectIndex, souffle::GenericIndex< Structure >, souffle::GenericIndex< Trie< Arity > >, souffle::GenericIndex< btree_set< ram::Tuple< RamDomain, Arity >, comparator< Arity > > >, and souffle::NullaryIndex.
virtual bool souffle::LVMIndex::contains (const TupleRef & tuple) const pure virtual
Tests whether the given tuple is present in this index or not.
Implemented in souffle::IndirectIndex, souffle::GenericIndex< Structure >, souffle::GenericIndex< Trie< Arity > >, souffle::GenericIndex< btree_set< ram::Tuple< RamDomain, Arity >, comparator< Arity > > >, and souffle::NullaryIndex.
Referenced by souffle::LVMRelation::contains(), souffle::LVMRelation::exists(), and souffle::LVMIndirectRelation::insert().
virtual bool souffle::LVMIndex::empty () const pure virtual
Tests whether this index is empty or not.
Implemented in souffle::IndirectIndex, souffle::GenericIndex< Structure >, souffle::GenericIndex< Trie< Arity > >, souffle::GenericIndex< btree_set< ram::Tuple< RamDomain, Arity >, comparator< Arity > > >, and souffle::NullaryIndex.
Referenced by souffle::LVMRelation::empty(), and souffle::NullaryIndex::insert().
virtual size_t souffle::LVMIndex::getArity () const pure virtual
Obtains the arity of the given index.
Implemented in souffle::IndirectIndex, souffle::GenericIndex< Structure >, souffle::GenericIndex< Trie< Arity > >, souffle::GenericIndex< btree_set< ram::Tuple< RamDomain, Arity >, comparator< Arity > > >, and souffle::NullaryIndex.
Referenced by souffle::NullaryIndex::insert().
virtual bool souffle::LVMIndex::insert (const TupleRef & tuple) pure virtual
Inserts a tuple into this index.
Implemented in souffle::IndirectIndex, souffle::GenericIndex< Structure >, souffle::GenericIndex< Trie< Arity > >, souffle::GenericIndex< btree_set< ram::Tuple< RamDomain, Arity >, comparator< Arity > > >, and souffle::NullaryIndex.
Referenced by souffle::LVMRelation::insert().
virtual void souffle::LVMIndex::insert (const LVMIndex & src) pure virtual
Inserts all elements of the given index.
Implemented in souffle::IndirectIndex, souffle::GenericIndex< Structure >, souffle::GenericIndex< Trie< Arity > >, souffle::GenericIndex< btree_set< ram::Tuple< RamDomain, Arity >, comparator< Arity > > >, and souffle::NullaryIndex.
virtual Stream souffle::LVMIndex::range (const TupleRef & low, const TupleRef & high) const pure virtual
Returns a stream covering the elements.
Implemented in souffle::IndirectIndex, souffle::GenericIndex< Structure >, souffle::GenericIndex< Trie< Arity > >, souffle::GenericIndex< btree_set< ram::Tuple< RamDomain, Arity >, comparator< Arity > > >, and souffle::NullaryIndex.
virtual Stream souffle::LVMIndex::scan () const pure virtual
Returns a stream covering the entire index content.
Implemented in souffle::IndirectIndex, souffle::GenericIndex< Structure >, souffle::GenericIndex< Trie< Arity > >, souffle::GenericIndex< btree_set< ram::Tuple< RamDomain, Arity >, comparator< Arity > > >, and souffle::NullaryIndex.
Referenced by souffle::GenericIndex< btree_set< ram::Tuple< RamDomain, Arity >, comparator< Arity > > >::insert(), souffle::IndirectIndex::insert(), and souffle::LVMRelation::scan().
virtual std::size_t souffle::LVMIndex::size () const pure virtual
Obtains the number of elements stored in this index.
Implemented in souffle::IndirectIndex, souffle::GenericIndex< Structure >, souffle::GenericIndex< Trie< Arity > >, souffle::GenericIndex< btree_set< ram::Tuple< RamDomain, Arity >, comparator< Arity > > >, and souffle::NullaryIndex.
Referenced by souffle::LVMRelation::size().
The documentation for this class was generated from the following file:
LVMIndex.h