souffle: souffle::TupleIdTransformer Class Reference
souffle::TupleIdTransformer Class Reference
Ordering tupleIds in RamTupleOperation operations correctly.
#include <RamTransforms.h>
Public Member Functions
std::string getName () const override
get name of the transformer flag reporting whether the RAM program has changed
bool reorderOperations (RamProgram &program)
Apply tupleId reordering to the whole program.
Public Member Functions inherited from souffle::RamTransformer
bool apply (RamTranslationUnit &translationUnit)
apply the transformer to a translation unit translationUnit that will be transformed.
RamTransformer ()=default
virtual ~RamTransformer ()=default
Protected Member Functions
bool transform (RamTranslationUnit &translationUnit) override
transform the translation unit / used by apply translationUnit that will be transformed.
Detailed Description
Ordering tupleIds in RamTupleOperation operations correctly.
Transformations, like MakeIndex and IfConversion do not ensure that RamTupleOperations maintain an appropriate order with respect to their tupleId's
For example: SEARCH ... (tupleId = 2) ... SEARCH ... (tupleId = 1) ...
Will be converted to SEARCH ... (tupleId = 0) ... SEARCH ... (tupleId = 1) ...
Definition at line 431 of file RamTransforms.h.
Member Function Documentation
std::string souffle::TupleIdTransformer::getName () const inline override virtual
get name of the transformer flag reporting whether the RAM program has changed
Get name of transformer
Implements souffle::RamTransformer.
Definition at line 433 of file RamTransforms.h.
{
         return "TupleIdTransformer";
     }
bool souffle::TupleIdTransformer::reorderOperations (RamProgram & program)
Apply tupleId reordering to the whole program.
Parameters
RAM program
Returns
A flag indicating whether the RAM program has been changed.
Search for RamTupleOperations and RamTupleElements and rewrite their tupleIds
Definition at line 524 of file RamTransforms.cpp.
References souffle::RamTransformer::apply(), souffle::RamTupleOperation::getTupleId(), souffle::makeLambdaRamMapper(), and souffle::visitDepthFirst().
{
     // flag to determine whether the RAM program has changed
     bool changed = false;
     visitDepthFirst(program, [&](const RamQuery& query) {
         // Maps old tupleIds to new tupleIds
         std::map<int, int> reorder;
         int ctr = 0;
         visitDepthFirst(query, [&](const RamTupleOperation& search) {
             if (ctr != search.getTupleId()) {
                 changed = true;
             }
             reorder[search.getTupleId()] = ctr;
             const_cast<RamTupleOperation*>(&search)->setTupleId(ctr);
             ctr++;
         });
         std::function<std::unique_ptr<RamNode>(std::unique_ptr<RamNode>)> elementRewriter =
                 [&](std::unique_ptr<RamNode> node) -> std::unique_ptr<RamNode> {
             if (auto* element = dynamic_cast<RamTupleElement*>(node.get())) {
                 if (reorder[element->getTupleId()] != element->getTupleId()) {
                     changed = true;
                     node = std::make_unique<RamTupleElement>(
                             reorder[element->getTupleId()], element->getElement());
                 }
             }
             node->apply(makeLambdaRamMapper(elementRewriter));
             return node;
         };
         const_cast<RamQuery*>(&query)->apply(makeLambdaRamMapper(elementRewriter));
     });
     return changed;
 }
bool souffle::TupleIdTransformer::transform (RamTranslationUnit & translationUnit) inline override protected virtual
transform the translation unit / used by apply translationUnit that will be transformed.
flag reporting whether the RAM program has changed
Implements souffle::RamTransformer.
Definition at line 447 of file RamTransforms.h.
References souffle::RamTranslationUnit::getProgram().
{
         return reorderOperations(*translationUnit.getProgram());
     }
The documentation for this class was generated from the following files:
RamTransforms.h
RamTransforms.cpp