souffle: souffle::MaxMatching Class Reference
souffle::MaxMatching Class Reference
Computes a maximum matching with Hopcroft-Karp algorithm
#include <RamIndexAnalysis.h>
Public Types
using Matchings = std::map< SearchSignature, SearchSignature, std::greater< SearchSignature >>
Matching represent a solution of the matching, i.e., which node in the bi-partite graph maps to another node.
using Nodes = std::set< SearchSignature, std::greater< SearchSignature >>
Public Member Functions
void addEdge (SearchSignature u, SearchSignature v)
add an edge to the bi-partite graph
int getNumMatchings () const
get number of matches in the solution
const Matchings & solve ()
solve the maximum matching problem
Protected Member Functions
bool bfSearch ()
perform a breadth first search in the graph
bool dfSearch (SearchSignature u)
perform a depth first search in the graph
int getDistance (SearchSignature v)
get distance of a node
SearchSignature getMatch (SearchSignature v)
get match for a search signature
Private Types
using Distance = std::map< SearchSignature, int >
distance function of nodes
using Edges = std::set< SearchSignature >
Edges in the bi-partite graph.
using Graph = std::map< SearchSignature, Edges >
Bi-partite graph of instance.
Private Attributes
Distance distance
Graph graph
Matchings match
Detailed Description
Computes a maximum matching with Hopcroft-Karp algorithm
This class is a helper class for RamIndexAnalysis.
This implements a standard maximum matching algorithm for a bi-partite graph also known as a marriage problem. Given a set of edges in a bi-partite graph select a subset of edges that each node in the bi-partite graph has at most one adjacent edge associated with.
The nodes of the bi-partite graph represent index-signatures stemming from RAM operations and RAM existence checks for a relation. A relation between two nodes represent whether an index operation subsumes another operation.
Source: http://en.wikipedia.org/wiki/Hopcroft%E2%80%93Karp_algorithm#Pseudocode
Definition at line 63 of file RamIndexAnalysis.h.
Member Typedef Documentation
using souffle::MaxMatching::Distance = std::map<SearchSignature, int> private
distance function of nodes
Definition at line 132 of file RamIndexAnalysis.h.
using souffle::MaxMatching::Edges = std::set<SearchSignature> private
Edges in the bi-partite graph.
Definition at line 124 of file RamIndexAnalysis.h.
using souffle::MaxMatching::Graph = std::map<SearchSignature, Edges> private
Bi-partite graph of instance.
Definition at line 128 of file RamIndexAnalysis.h.
using souffle::MaxMatching::Matchings = std::map<SearchSignature, SearchSignature, std::greater<SearchSignature>>
Matching represent a solution of the matching, i.e., which node in the bi-partite graph maps to another node.
If no map exist for a node, there is no adjacent edge exists for that node.
Definition at line 73 of file RamIndexAnalysis.h.
using souffle::MaxMatching::Nodes = std::set<SearchSignature, std::greater<SearchSignature>>
Definition at line 66 of file RamIndexAnalysis.h.
Member Function Documentation
void souffle::MaxMatching::addEdge (SearchSignature u, SearchSignature v)
add an edge to the bi-partite graph
Parameters
u search signature
v subsuming search signature
Definition at line 31 of file RamIndexAnalysis.cpp.
References graph.
Referenced by getNumMatchings().
{
     if (graph.find(u) == graph.end()) {
         Edges vals;
         vals.insert(v);
         graph.insert(make_pair(u, vals));
     } else {
         graph[u].insert(v);
     }
 }
bool souffle::MaxMatching::bfSearch () protected
perform a breadth first search in the graph
Definition at line 57 of file RamIndexAnalysis.cpp.
References distance, getDistance(), getMatch(), graph, RIA_INF, and RIA_NIL.
Referenced by getNumMatchings(), and solve().
{
     SearchSignature u;
     std::queue<SearchSignature> bfQueue;
     // Build layers
     for (auto& it : graph) {
         if (getMatch(it.first) == RIA_NIL) {
             distance[it.first] = 0;
             bfQueue.push(it.first);
         } else {
             distance[it.first] = RIA_INF;
         }
     }
     distance[RIA_NIL] = RIA_INF;
     while (!bfQueue.empty()) {
         u = bfQueue.front();
         bfQueue.pop();
         assert(u != RIA_NIL);
         const Edges& children = graph[u];
         for (auto it : children) {
             SearchSignature mv = getMatch(it);
             if (getDistance(mv) == RIA_INF) {
                 distance[mv] = getDistance(u) + 1;
                 if (mv != RIA_NIL) {
                     bfQueue.push(mv);
                 }
             }
         }
     }
     return (getDistance(0) != RIA_INF);
 }
bool souffle::MaxMatching::dfSearch (SearchSignature u) protected
perform a depth first search in the graph
Parameters
u search signature
Definition at line 88 of file RamIndexAnalysis.cpp.
References distance, getDistance(), getMatch(), graph, match, and RIA_INF.
Referenced by getNumMatchings(), and solve().
{
     if (u != 0) {
         Edges& children = graph[u];
         for (auto v : children) {
             if (getDistance(getMatch(v)) == getDistance(u) + 1) {
                 if (dfSearch(getMatch(v))) {
                     match[u] = v;
                     match[v] = u;
                     return true;
                 }
             }
         }
         distance[u] = RIA_INF;
         return false;
     }
     return true;
 }
int souffle::MaxMatching::getDistance (SearchSignature v) protected
get distance of a node
Definition at line 49 of file RamIndexAnalysis.cpp.
References distance, and RIA_INF.
Referenced by bfSearch(), dfSearch(), and getNumMatchings().
{
     auto it = distance.find(v);
     if (it == distance.end()) {
         return RIA_INF;
     }
     return it->second;
 }
SearchSignature souffle::MaxMatching::getMatch (SearchSignature v) protected
get match for a search signature
Parameters
v search signature
Definition at line 41 of file RamIndexAnalysis.cpp.
References match, and RIA_NIL.
Referenced by bfSearch(), dfSearch(), getNumMatchings(), and solve().
{
     auto it = match.find(v);
     if (it == match.end()) {
         return RIA_NIL;
     }
     return it->second;
 }
int souffle::MaxMatching::getNumMatchings () const inline
get number of matches in the solution
Returns
number of matches
Definition at line 86 of file RamIndexAnalysis.h.
References addEdge(), bfSearch(), dfSearch(), getDistance(), getMatch(), and match.
{
         return match.size() / 2;
     }
const MaxMatching::Matchings & souffle::MaxMatching::solve ()
solve the maximum matching problem
Returns
returns the matching
Definition at line 107 of file RamIndexAnalysis.cpp.
References bfSearch(), dfSearch(), getMatch(), graph, match, and RIA_NIL.
Referenced by souffle::MinIndexSelection::isSubset().
{
     while (bfSearch()) {
         for (auto& it : graph) {
             if (getMatch(it.first) == RIA_NIL) {
                 dfSearch(it.first);
             }
         }
     }
     return match;
 }
Field Documentation
Distance souffle::MaxMatching::distance private
Definition at line 136 of file RamIndexAnalysis.h.
Referenced by bfSearch(), dfSearch(), and getDistance().
Graph souffle::MaxMatching::graph private
Definition at line 135 of file RamIndexAnalysis.h.
Referenced by addEdge(), bfSearch(), dfSearch(), and solve().
Matchings souffle::MaxMatching::match private
Definition at line 134 of file RamIndexAnalysis.h.
Referenced by dfSearch(), getMatch(), getNumMatchings(), souffle::MinIndexSelection::insertIndex(), and solve().
The documentation for this class was generated from the following files:
RamIndexAnalysis.h
RamIndexAnalysis.cpp