souffle: souffle::RAMIRelation Class Reference
souffle::RAMIRelation Class Reference
RAMI Relation.
#include <RAMIRelation.h>
Data Structures
class iterator
Iterator for relation.
Public Member Functions
iterator begin () const
get iterator begin of relation
bool empty () const
Check whether relation is empty.
iterator end () const
get iterator begin of relation
bool exists (const RamDomain *tuple) const
check whether a tuple exists in the relation
virtual std::vector< RamDomain * > extend (const RamDomain *tuple)
Extend tuple.
virtual void extend (const RAMIRelation &rel)
Extend relation.
size_t getArity () const
Get arity of relation.
std::vector< std::string > & getAttributeTypeQualifiers ()
Get AttributeType for the relation.
RAMIIndex * getIndex (const SearchSignature &col) const
get index for a given search signature.
RAMIIndex * getIndexByPos (int idx) const
get index for a given order.
size_t getLevel ()
const std::string & getName () const
std::string getName ()
SearchSignature getTotalIndexKey () const
Obtains a full index-key for this relation.
virtual void insert (const RamDomain *tuple)
Insert tuple.
void insert (const RAMIRelation &other)
Merge another relation into this relation.
void purge ()
Purge table.
RAMIRelation (size_t relArity, const MinIndexSelection *orderSet, std::string relName)
RAMIRelation (const RAMIRelation &other)=delete
void setAttributes (const std::vector< std::string > attributeTypes)
Set AttributeType for the relation.
void setLevel (size_t level)
size_t size () const
Gets the number of contained tuples.
virtual ~RAMIRelation ()=default
Private Types
using LexOrder = std::vector< int >
Private Attributes
const size_t arity
Arity of relation.
std::vector< std::string > attributeTypeQualifiers
Type of attributes.
std::deque< std::unique_ptr< RamDomain[]> > blockList
std::vector< RAMIIndex > indices
List of indices.
size_t level = 0
Stratum level information.
Lock lock
Lock for parallel execution.
size_t num_tuples = 0
Number of tuples in relation.
const MinIndexSelection * orderSet
IndexSet.
const std::string relName
Relation name.
Static Private Attributes
static const int BLOCK_SIZE = 1024
Size of blocks containing tuples.
Detailed Description
RAMI Relation.
Definition at line 36 of file RAMIRelation.h.
Member Typedef Documentation
using souffle::RAMIRelation::LexOrder = std::vector<int> private
Definition at line 37 of file RAMIRelation.h.
Constructor & Destructor Documentation
souffle::RAMIRelation::RAMIRelation (size_t relArity, const MinIndexSelection * orderSet, std::string relName) inline
Definition at line 40 of file RAMIRelation.h.
References souffle::MinIndexSelection::getAllOrders(), indices, and ~RAMIRelation().
             : arity(relArity), orderSet(orderSet), relName(std::move(relName)) {
         // Create all necessary indices based on orderSet
         for (auto& order : orderSet->getAllOrders()) {
             indices.push_back(RAMIIndex(order));
         }
     }
souffle::RAMIRelation::RAMIRelation (const RAMIRelation & other) delete
virtual souffle::RAMIRelation::~RAMIRelation () virtual default
Referenced by RAMIRelation().
Member Function Documentation
iterator souffle::RAMIRelation::begin () const inline
get iterator begin of relation
Definition at line 223 of file RAMIRelation.h.
References empty(), end(), and souffle::RAMIRelation::iterator::iterator().
Referenced by souffle::RAMIRelInterface::begin().
{
         // check for emptiness
         if (empty()) {
             return end();
         }
         return iterator(this);
     }
bool souffle::RAMIRelation::empty () const inline
Check whether relation is empty.
Definition at line 76 of file RAMIRelation.h.
References num_tuples.
Referenced by begin().
{
         return num_tuples == 0;
     }
iterator souffle::RAMIRelation::end () const inline
get iterator begin of relation
Definition at line 233 of file RAMIRelation.h.
References souffle::RAMIRelation::iterator::iterator().
Referenced by begin(), and souffle::RAMIRelInterface::end().
{
         return iterator();
     }
bool souffle::RAMIRelation::exists (const RamDomain * tuple) const inline
check whether a tuple exists in the relation
Definition at line 159 of file RAMIRelation.h.
References souffle::RAMIIndex::exists(), getIndex(), and getTotalIndexKey().
Referenced by souffle::RAMIRelInterface::contains(), souffle::RAMI::evalCond(), and insert().
{
         RAMIIndex* index = getIndex(getTotalIndexKey());
         return index->exists(tuple);
     }
virtual std::vector<RamDomain*> souffle::RAMIRelation::extend (const RamDomain * tuple) inline virtual
Extend tuple.
Reimplemented in souffle::RAMIEqRelation.
Definition at line 238 of file RAMIRelation.h.
Referenced by souffle::RAMI::evalStmt(), souffle::RAMIEqRelation::extend(), and souffle::RAMIEqRelation::insert().
{
         std::vector<RamDomain*> newTuples;
         // A standard relation does not generate extra new knowledge on insertion.
         newTuples.push_back(new RamDomain[2]{tuple[0], tuple[1]});
         return newTuples;
     }
virtual void souffle::RAMIRelation::extend (const RAMIRelation & rel) inline virtual
Extend relation.
Reimplemented in souffle::RAMIEqRelation.
Definition at line 248 of file RAMIRelation.h.
 {}
size_t souffle::RAMIRelation::getArity () const inline
Get arity of relation.
Definition at line 71 of file RAMIRelation.h.
References arity.
Referenced by souffle::RAMI::evalCond(), souffle::RAMI::evalOp(), souffle::RAMIRelInterface::getArity(), getTotalIndexKey(), and insert().
{
         return arity;
     }
std::vector<std::string>& souffle::RAMIRelation::getAttributeTypeQualifiers () inline
Get AttributeType for the relation.
Definition at line 58 of file RAMIRelation.h.
References attributeTypeQualifiers.
{
         return attributeTypeQualifiers;
     }
RAMIIndex* souffle::RAMIRelation::getIndex (const SearchSignature & col) const inline
get index for a given search signature.
Order are encoded as bits for each column
Definition at line 140 of file RAMIRelation.h.
References arity, getIndexByPos(), souffle::MinIndexSelection::getLexOrderNum(), getTotalIndexKey(), and orderSet.
Referenced by souffle::RAMI::evalCond(), souffle::RAMI::evalOp(), and exists().
{
         // Special case in provenance program, a 0 searchSignature is considered as a full search
         if (col == 0 && arity != 0) {
             return getIndex(getTotalIndexKey());
         }
         return getIndexByPos(orderSet->getLexOrderNum(col));
     }
RAMIIndex* souffle::RAMIRelation::getIndexByPos (int idx) const inline
get index for a given order.
Order are encoded as bits for each column
Definition at line 149 of file RAMIRelation.h.
References indices.
Referenced by getIndex().
{
         return &indices[idx];
     }
size_t souffle::RAMIRelation::getLevel () inline
Definition at line 168 of file RAMIRelation.h.
References level.
                       {
         return this->level;
     }
const std::string& souffle::RAMIRelation::getName () const inline
Definition at line 62 of file RAMIRelation.h.
References relName.
{
         return relName;
     }
std::string souffle::RAMIRelation::getName () inline
Definition at line 66 of file RAMIRelation.h.
References relName.
{
         return relName;
     }
SearchSignature souffle::RAMIRelation::getTotalIndexKey () const inline
Obtains a full index-key for this relation.
Definition at line 154 of file RAMIRelation.h.
References getArity().
Referenced by exists(), and getIndex().
{
         return (1 << (getArity())) - 1;
     }
virtual void souffle::RAMIRelation::insert (const RamDomain * tuple) inline virtual
Insert tuple.
Reimplemented in souffle::RAMIEqRelation.
Definition at line 86 of file RAMIRelation.h.
References arity, BLOCK_SIZE, blockList, exists(), i, indices, and num_tuples.
Referenced by souffle::RAMI::evalOp(), souffle::RAMI::evalStmt(), souffle::RAMIEqRelation::extend(), souffle::RAMIRelInterface::insert(), insert(), and souffle::RAMIEqRelation::insert().
{
         assert(tuple);
         // make existence check
         if (exists(tuple)) {
             return;
         }
         // check for null-arity
         if (arity == 0) {
             indices[0].insert(tuple);
             num_tuples = 1;
             return;
         }
         int blockIndex = num_tuples / (BLOCK_SIZE / arity);
         int tupleIndex = (num_tuples % (BLOCK_SIZE / arity)) * arity;
         if (tupleIndex == 0) {
             blockList.push_back(std::make_unique<RamDomain[]>(BLOCK_SIZE));
         }
         RamDomain* newTuple = &blockList[blockIndex][tupleIndex];
         for (size_t i = 0; i < arity; ++i) {
             newTuple[i] = tuple[i];
         }
         // update all indexes with new tuple
         for (auto& cur : indices) {
             cur.insert(newTuple);
         }
         // increment relation size
         num_tuples++;
     }
void souffle::RAMIRelation::insert (const RAMIRelation & other) inline
Merge another relation into this relation.
Definition at line 123 of file RAMIRelation.h.
References getArity(), and insert().
{
         assert(getArity() == other.getArity());
         for (const auto& cur : other) {
             insert(cur);
         }
     }
void souffle::RAMIRelation::purge () inline
Purge table.
Definition at line 131 of file RAMIRelation.h.
References blockList, indices, and num_tuples.
Referenced by souffle::RAMI::evalStmt(), and souffle::RAMIRelInterface::purge().
                  {
         blockList.clear();
         for (auto& cur : indices) {
             cur.purge();
         }
         num_tuples = 0;
     }
void souffle::RAMIRelation::setAttributes (const std::vector< std::string > attributeTypes) inline
Set AttributeType for the relation.
Definition at line 53 of file RAMIRelation.h.
References attributeTypeQualifiers.
{
         attributeTypeQualifiers = attributeTypes;
     }
void souffle::RAMIRelation::setLevel (size_t level) inline
Definition at line 164 of file RAMIRelation.h.
References level.
{
         this->level = level;
     }
size_t souffle::RAMIRelation::size () const inline
Gets the number of contained tuples.
Definition at line 81 of file RAMIRelation.h.
References num_tuples.
Referenced by souffle::RAMI::evalStmt(), and souffle::RAMIRelInterface::size().
{
         return num_tuples;
     }
Field Documentation
const size_t souffle::RAMIRelation::arity private
Arity of relation.
Definition at line 252 of file RAMIRelation.h.
Referenced by getArity(), getIndex(), insert(), and souffle::RAMIRelation::iterator::operator++().
std::vector<std::string> souffle::RAMIRelation::attributeTypeQualifiers private
Type of attributes.
Definition at line 272 of file RAMIRelation.h.
Referenced by getAttributeTypeQualifiers(), and setAttributes().
const int souffle::RAMIRelation::BLOCK_SIZE = 1024 static private
Size of blocks containing tuples.
Definition at line 255 of file RAMIRelation.h.
Referenced by insert(), and souffle::RAMIRelation::iterator::operator++().
std::deque<std::unique_ptr<RamDomain[]> > souffle::RAMIRelation::blockList private
Definition at line 260 of file RAMIRelation.h.
Referenced by insert(), souffle::RAMIRelation::iterator::operator++(), and purge().
std::vector<RAMIIndex> souffle::RAMIRelation::indices mutable private
List of indices.
Definition at line 263 of file RAMIRelation.h.
Referenced by getIndexByPos(), insert(), purge(), and RAMIRelation().
size_t souffle::RAMIRelation::level = 0 private
Stratum level information.
Definition at line 275 of file RAMIRelation.h.
Referenced by getLevel(), and setLevel().
Lock souffle::RAMIRelation::lock mutable private
Lock for parallel execution.
Definition at line 269 of file RAMIRelation.h.
size_t souffle::RAMIRelation::num_tuples = 0 private
Number of tuples in relation.
Definition at line 258 of file RAMIRelation.h.
Referenced by empty(), insert(), souffle::RAMIRelation::iterator::operator++(), purge(), and size().
const MinIndexSelection* souffle::RAMIRelation::orderSet private
IndexSet.
Definition at line 266 of file RAMIRelation.h.
Referenced by getIndex().
const std::string souffle::RAMIRelation::relName private
Relation name.
Definition at line 278 of file RAMIRelation.h.
Referenced by getName().
The documentation for this class was generated from the following file:
RAMIRelation.h