souffle: souffle::HoistConditionsTransformer Class Reference
souffle::HoistConditionsTransformer Class Reference
Hosts conditions in a loop-nest to the most-outer/semantically-correct loop.
#include <RamTransforms.h>
Public Member Functions
std::string getName () const override
get name of the transformer flag reporting whether the RAM program has changed
bool hoistConditions (RamProgram &program)
Hoist filter operations.
Public Member Functions inherited from souffle::RamTransformer
bool apply (RamTranslationUnit &translationUnit)
apply the transformer to a translation unit translationUnit that will be transformed.
RamTransformer ()=default
virtual ~RamTransformer ()=default
Protected Member Functions
bool transform (RamTranslationUnit &translationUnit) override
transform the translation unit / used by apply translationUnit that will be transformed.
Protected Attributes
RamLevelAnalysis * rla {nullptr}
Detailed Description
Hosts conditions in a loop-nest to the most-outer/semantically-correct loop.
Hoists the conditions to the earliest point in the loop nest where their evaluation is still semantically correct.
The transformations assumes that filter operations are stored verbose, i.e. a conjunction is expressed by two consecutive filter operations. For example ..
QUERY
 ...
  IF C1 /\ C2 then
   ...
should be rewritten / or produced by the translator as
QUERY
 ...
  IF C1
   IF C2
    ...
otherwise the levelling becomes imprecise, i.e., for both conditions the most outer-level is sought rather than considered separately.
If there are transformers prior to hoistConditions() that introduce conjunction, another transformer is required that splits the filter operations. However, at the moment this is not necessary because the translator delivers already the right RAM format.
TODO: break-up conditions while transforming so that this requirement is removed.
Definition at line 154 of file RamTransforms.h.
Member Function Documentation
std::string souffle::HoistConditionsTransformer::getName () const inline override virtual
get name of the transformer flag reporting whether the RAM program has changed
Get name of transformer
Implements souffle::RamTransformer.
Definition at line 156 of file RamTransforms.h.
{
         return "HoistConditionsTransformer";
     }
bool souffle::HoistConditionsTransformer::hoistConditions (RamProgram & program)
Hoist filter operations.
Parameters
program that is transformed
Returns
Flag showing whether the program has been changed by the transformation
There are two types of conditions in filter operations. The first type depends on tuples of RamTupleOperation operations. The second type are independent of tuple access. Both types of conditions will be hoisted to the most out-scope such that the program is still valid.
Definition at line 108 of file RamTransforms.cpp.
References souffle::RamTransformer::apply(), souffle::RamNode::apply(), souffle::RamCondition::clone(), souffle::RamTupleOperation::getTupleId(), souffle::makeLambdaRamMapper(), and souffle::visitDepthFirst().
{
     // flag to determine whether the RAM program has changed
     bool changed = false;
     // helper for collecting conditions from filter operations
     auto addCondition = [](std::unique_ptr<RamCondition> condition,
                                 RamCondition* c) -> std::unique_ptr<RamCondition> {
         if (condition == nullptr) {
             return std::unique_ptr<RamCondition>(c);
         } else {
             return std::make_unique<RamConjunction>(std::move(condition), std::unique_ptr<RamCondition>(c));
         }
     };
     // insert a new filter
     auto insertFilter = [](RamOperation* op, std::unique_ptr<RamCondition>& condition) {
         op->apply(makeLambdaRamMapper([&](std::unique_ptr<RamNode> node) -> std::unique_ptr<RamNode> {
             if (nullptr != dynamic_cast<RamOperation*>(node.get())) {
                 return std::make_unique<RamFilter>(std::move(condition),
                         std::unique_ptr<RamOperation>(dynamic_cast<RamOperation*>(node.release())));
             }
             return node;
         }));
     };
     // hoist conditions to the most outer scope if they
     // don't depend on RamTupleOperations
     visitDepthFirst(program, [&](const RamQuery& query) {
         std::unique_ptr<RamCondition> newCondition;
         std::function<std::unique_ptr<RamNode>(std::unique_ptr<RamNode>)> filterRewriter =
                 [&](std::unique_ptr<RamNode> node) -> std::unique_ptr<RamNode> {
             if (auto* filter = dynamic_cast<RamFilter*>(node.get())) {
                 const RamCondition& condition = filter->getCondition();
                 // if filter condition is independent of any RamTupleOperation,
                 // delete the filter operation and collect condition
                 if (rla->getLevel(&condition) == -1) {
                     changed = true;
                     newCondition = addCondition(std::move(newCondition), condition.clone());
                     node->apply(makeLambdaRamMapper(filterRewriter));
                     return std::unique_ptr<RamOperation>(filter->getOperation().clone());
                 }
             }
             node->apply(makeLambdaRamMapper(filterRewriter));
             return node;
         };
         const_cast<RamQuery*>(&query)->apply(makeLambdaRamMapper(filterRewriter));
         if (newCondition != nullptr) {
             // insert new filter operation at outer-most level of the query
             changed = true;
             insertFilter((RamOperation*)&query, newCondition);
         }
     });
     // hoist conditions for each RamTupleOperation operation
     visitDepthFirst(program, [&](const RamTupleOperation& search) {
         std::unique_ptr<RamCondition> newCondition;
         std::function<std::unique_ptr<RamNode>(std::unique_ptr<RamNode>)> filterRewriter =
                 [&](std::unique_ptr<RamNode> node) -> std::unique_ptr<RamNode> {
             if (auto* filter = dynamic_cast<RamFilter*>(node.get())) {
                 const RamCondition& condition = filter->getCondition();
                 // if filter condition matches level of RamTupleOperation,
                 // delete the filter operation and collect condition
                 if (rla->getLevel(&condition) == search.getTupleId()) {
                     changed = true;
                     newCondition = addCondition(std::move(newCondition), condition.clone());
                     node->apply(makeLambdaRamMapper(filterRewriter));
                     return std::unique_ptr<RamOperation>(filter->getOperation().clone());
                 }
             }
             node->apply(makeLambdaRamMapper(filterRewriter));
             return node;
         };
         const_cast<RamTupleOperation*>(&search)->apply(makeLambdaRamMapper(filterRewriter));
         if (newCondition != nullptr) {
             // insert new filter operation after the search operation
             changed = true;
             insertFilter((RamOperation*)&search, newCondition);
         }
     });
     return changed;
 }
bool souffle::HoistConditionsTransformer::transform (RamTranslationUnit & translationUnit) inline override protected virtual
transform the translation unit / used by apply translationUnit that will be transformed.
flag reporting whether the RAM program has changed
Implements souffle::RamTransformer.
Definition at line 176 of file RamTransforms.h.
References souffle::RamTranslationUnit::getAnalysis(), and souffle::RamTranslationUnit::getProgram().
{
         rla = translationUnit.getAnalysis<RamLevelAnalysis>();
         return hoistConditions(*translationUnit.getProgram());
     }
Field Documentation
RamLevelAnalysis* souffle::HoistConditionsTransformer::rla {nullptr} protected
Definition at line 174 of file RamTransforms.h.
The documentation for this class was generated from the following files:
RamTransforms.h
RamTransforms.cpp