souffle: souffle::RamSubroutineArgument Class Reference
souffle::RamSubroutineArgument Class Reference
Access argument of a subroutine.
#include <RamExpression.h>
Public Member Functions
RamSubroutineArgument * clone () const override
Create a clone (i.e.
size_t getArgument () const
Get argument.
void print (std::ostream &os) const override
Print RAM node.
RamSubroutineArgument (size_t number)
Public Member Functions inherited from souffle::RamNode
virtual void apply (const RamNodeMapper &mapper)
Apply the mapper to all child nodes.
virtual std::vector< const RamNode * > getChildNodes () const
Obtain list of all embedded child nodes.
bool operator!= (const RamNode &other) const
Inequality check for two RAM nodes.
bool operator== (const RamNode &other) const
Equivalence check for two RAM nodes.
RamNode ()=default
virtual ~RamNode ()=default
Protected Member Functions
bool equal (const RamNode &node) const override
Equality check for two RAM nodes.
Protected Attributes
const size_t number
Argument number.
Detailed Description
Access argument of a subroutine.
Arguments are number from zero 0 to n-1 where n is the number of arguments of the subroutine.
Definition at line 383 of file RamExpression.h.
Constructor & Destructor Documentation
souffle::RamSubroutineArgument::RamSubroutineArgument (size_t number) inline
Definition at line 385 of file RamExpression.h.
 : number(number) {}
Member Function Documentation
RamSubroutineArgument* souffle::RamSubroutineArgument::clone () const inline override virtual
Create a clone (i.e.
deep copy) of this node
Implements souffle::RamExpression.
Definition at line 396 of file RamExpression.h.
{
         return new RamSubroutineArgument(number);
     }
bool souffle::RamSubroutineArgument::equal (const RamNode & other) const inline override protected virtual
Equality check for two RAM nodes.
Default action is that nothing needs to be checked.
Reimplemented from souffle::RamNode.
Definition at line 404 of file RamExpression.h.
References getArgument().
{
         assert(nullptr != dynamic_cast<const RamSubroutineArgument*>(&node));
         const auto& other = static_cast<const RamSubroutineArgument&>(node);
         return getArgument() == other.getArgument();
     }
size_t souffle::RamSubroutineArgument::getArgument () const inline
Get argument.
Definition at line 388 of file RamExpression.h.
Referenced by souffle::Synthesiser::emitCode(), equal(), souffle::RAMI::evalExpr(), and souffle::LVMGenerator::visitSubroutineArgument().
{
         return number;
     }
void souffle::RamSubroutineArgument::print (std::ostream & out) const inline override virtual
Print RAM node.
Implements souffle::RamNode.
Definition at line 392 of file RamExpression.h.
{
         os << "argument(" << number << ")";
     }
Field Documentation
const size_t souffle::RamSubroutineArgument::number protected
Argument number.
Definition at line 402 of file RamExpression.h.
The documentation for this class was generated from the following file:
RamExpression.h