souffle: souffle::CollapseFiltersTransformer Class Reference
souffle::CollapseFiltersTransformer Class Reference
Transforms consecutive filters into a single filter containing a conjunction.
#include <RamTransforms.h>
Public Member Functions
bool collapseFilters (RamProgram &program)
Collapse consecutive filter operations.
std::string getName () const override
get name of the transformer flag reporting whether the RAM program has changed
Public Member Functions inherited from souffle::RamTransformer
bool apply (RamTranslationUnit &translationUnit)
apply the transformer to a translation unit translationUnit that will be transformed.
RamTransformer ()=default
virtual ~RamTransformer ()=default
Protected Member Functions
bool transform (RamTranslationUnit &translationUnit) override
transform the translation unit / used by apply translationUnit that will be transformed.
Detailed Description
Transforms consecutive filters into a single filter containing a conjunction.
For example ..
QUERY
 ...
  IF C1
   IF C2
    ...
will be rewritten to
QUERY
 ...
  IF C1 /\ C2 then
   ...
Definition at line 96 of file RamTransforms.h.
Member Function Documentation
bool souffle::CollapseFiltersTransformer::collapseFilters (RamProgram & program)
Collapse consecutive filter operations.
Parameters
program Program that is transformed
Returns
Flag showing whether the program has been changed by the transformation
Definition at line 70 of file RamTransforms.cpp.
References souffle::RamTransformer::apply(), souffle::RamAbstractConditional::apply(), souffle::RamOperation::clone(), souffle::RamNestedOperation::getOperation(), souffle::RamNestedOperation::getProfileText(), souffle::makeLambdaRamMapper(), souffle::toCondition(), and souffle::visitDepthFirst().
{
     // flag to determine whether the RAM program has changed
     bool changed = false;
     visitDepthFirst(program, [&](const RamQuery& query) {
         std::function<std::unique_ptr<RamNode>(std::unique_ptr<RamNode>)> filterRewriter =
                 [&](std::unique_ptr<RamNode> node) -> std::unique_ptr<RamNode> {
             if (const RamFilter* filter = dynamic_cast<RamFilter*>(node.get())) {
                 // true if two consecutive filters in loop nest found
                 bool canCollapse = false;
                 // storing conditions for collapsing
                 std::vector<const RamCondition*> conditions;
                 const RamFilter* prevFilter = filter;
                 conditions.emplace_back(&filter->getCondition());
                 while (auto* nextFilter = dynamic_cast<RamFilter*>(&prevFilter->getOperation())) {
                     canCollapse = true;
                     conditions.emplace_back(&nextFilter->getCondition());
                     prevFilter = nextFilter;
                 }
                 if (canCollapse) {
                     changed = true;
                     node = std::make_unique<RamFilter>(toCondition(conditions),
                             std::unique_ptr<RamOperation>(
                                     dynamic_cast<RamOperation*>(prevFilter->getOperation().clone())),
                             prevFilter->getProfileText());
                 }
             }
             node->apply(makeLambdaRamMapper(filterRewriter));
             return node;
         };
         const_cast<RamQuery*>(&query)->apply(makeLambdaRamMapper(filterRewriter));
     });
     return changed;
 }
std::string souffle::CollapseFiltersTransformer::getName () const inline override virtual
get name of the transformer flag reporting whether the RAM program has changed
Get name of transformer
Implements souffle::RamTransformer.
Definition at line 98 of file RamTransforms.h.
{
         return "CollapseFiltersTransformer";
     }
bool souffle::CollapseFiltersTransformer::transform (RamTranslationUnit & translationUnit) inline override protected virtual
transform the translation unit / used by apply translationUnit that will be transformed.
flag reporting whether the RAM program has changed
Implements souffle::RamTransformer.
Definition at line 110 of file RamTransforms.h.
References souffle::RamTranslationUnit::getProgram().
{
         return collapseFilters(*translationUnit.getProgram());
     }
The documentation for this class was generated from the following files:
RamTransforms.h
RamTransforms.cpp