souffle: souffle::RelationEncoder Class Reference
souffle::RelationEncoder Class Reference
RelationEncoder create and encode a LVMRelation into a index position for fast lookup.
#include <LVMGenerator.h>
Public Member Functions
LVMRelation * decodeRelation (size_t relId) const
Decode relationId, return relationName.
size_t encodeRelation (const RamRelation &rel)
Encode a relation into a index Id and return the encoding result.
std::vector< std::unique_ptr< LVMRelation > > & getRelationMap ()
size_t getSize () const
Get total number of relations.
std::unique_ptr< LVMRelation > & operator[] (size_t idx)
RelationEncoder (RamIndexAnalysis *isa, RamTranslationUnit &tUnit)
Data Fields
RamIndexAnalysis * isa
Private Member Functions
std::unique_ptr< LVMRelation > createRelation (const RamRelation &rel)
Create relation with corresponding index type.
Private Attributes
std::vector< std::unique_ptr< LVMRelation > > relationMap
Index to concrete relation mapping.
std::map< std::string, size_t > relNameToIndex
RelName to index mapping.
Static Private Attributes
static constexpr size_t MAX_DIRECT_INDEX_SIZE = 12
Detailed Description
RelationEncoder create and encode a LVMRelation into a index position for fast lookup.
Definition at line 27 of file LVMGenerator.h.
Constructor & Destructor Documentation
souffle::RelationEncoder::RelationEncoder (RamIndexAnalysis * isa, RamTranslationUnit & tUnit) inline
Definition at line 29 of file LVMGenerator.h.
References encodeRelation(), souffle::RamProgram::getAllRelations(), and souffle::RamTranslationUnit::getProgram().
                                                                       : isa(isa) {
         for (const auto& pair : tUnit.getProgram()->getAllRelations()) {
             encodeRelation(*pair.second);
         }
     }
Member Function Documentation
std::unique_ptr<LVMRelation> souffle::RelationEncoder::createRelation (const RamRelation & rel) inline private
Create relation with corresponding index type.
Definition at line 79 of file LVMGenerator.h.
References souffle::BRIE, souffle::BTREE, souffle::createBrieIndex(), souffle::DEFAULT, souffle::EQREL, souffle::RamRelation::getArity(), souffle::RamRelation::getAttributeTypeQualifiers(), souffle::RamIndexAnalysis::getIndexes(), souffle::RamRelation::getName(), souffle::RamRelation::getRepresentation(), and MAX_DIRECT_INDEX_SIZE.
Referenced by encodeRelation().
{
         const MinIndexSelection& orderSet = isa->getIndexes(rel);
         if (rel.getArity() > MAX_DIRECT_INDEX_SIZE) {
             return std::make_unique<LVMIndirectRelation>(
                     rel.getArity(), rel.getName(), rel.getAttributeTypeQualifiers(), orderSet);
         }
         switch (rel.getRepresentation()) {
             case RelationRepresentation::BTREE:
                 return std::make_unique<LVMRelation>(
                         rel.getArity(), rel.getName(), rel.getAttributeTypeQualifiers(), orderSet);
             case RelationRepresentation::BRIE:
                 return std::make_unique<LVMRelation>(rel.getArity(), rel.getName(),
                         rel.getAttributeTypeQualifiers(), orderSet, createBrieIndex);
             case RelationRepresentation::EQREL:
                 return std::make_unique<LVMEqRelation>(
                         rel.getArity(), rel.getName(), rel.getAttributeTypeQualifiers(), orderSet);
             case RelationRepresentation::DEFAULT:
                 return std::make_unique<LVMRelation>(
                         rel.getArity(), rel.getName(), rel.getAttributeTypeQualifiers(), orderSet);
             default:
                 break;
         }
         return nullptr;
     }
LVMRelation* souffle::RelationEncoder::decodeRelation (size_t relId) const inline
Decode relationId, return relationName.
Definition at line 50 of file LVMGenerator.h.
References relationMap.
{
         return relationMap[relId].get();
     }
size_t souffle::RelationEncoder::encodeRelation (const RamRelation & rel) inline
Encode a relation into a index Id and return the encoding result.
Definition at line 36 of file LVMGenerator.h.
References createRelation(), souffle::RamRelation::getName(), relationMap, and relNameToIndex.
Referenced by RelationEncoder().
{
         const std::string& relationName = rel.getName();
         auto iter = relNameToIndex.find(relationName);
         // Create and give relation a new index if it is not in the environment yet
         if (iter == relNameToIndex.end()) {
             relNameToIndex.insert(std::make_pair(relationName, relNameToIndex.size()));
             relationMap.push_back(createRelation(rel));
             return relNameToIndex.size() - 1;
         } else {
             return iter->second;
         }
     }
std::vector<std::unique_ptr<LVMRelation> >& souffle::RelationEncoder::getRelationMap () inline
Definition at line 63 of file LVMGenerator.h.
References relationMap.
Referenced by souffle::LVM::execute(), and souffle::LVMInterface::getRelationMap().
{
         return relationMap;
     }
size_t souffle::RelationEncoder::getSize () const inline
Get total number of relations.
Definition at line 55 of file LVMGenerator.h.
References relationMap.
{
         return relationMap.size();
     }
std::unique_ptr<LVMRelation>& souffle::RelationEncoder::operator[] (size_t idx) inline
Definition at line 59 of file LVMGenerator.h.
References relationMap.
{
         return relationMap[idx];
     }
Field Documentation
RamIndexAnalysis* souffle::RelationEncoder::isa
Definition at line 67 of file LVMGenerator.h.
Referenced by souffle::LVMGenerator::getIndexPos().
constexpr size_t souffle::RelationEncoder::MAX_DIRECT_INDEX_SIZE = 12 static private
Definition at line 70 of file LVMGenerator.h.
Referenced by createRelation().
std::vector<std::unique_ptr<LVMRelation> > souffle::RelationEncoder::relationMap private
Index to concrete relation mapping.
Definition at line 76 of file LVMGenerator.h.
Referenced by decodeRelation(), encodeRelation(), getRelationMap(), getSize(), and operator[]().
std::map<std::string, size_t> souffle::RelationEncoder::relNameToIndex private
RelName to index mapping.
Definition at line 73 of file LVMGenerator.h.
Referenced by encodeRelation().
The documentation for this class was generated from the following file:
LVMGenerator.h