souffle: souffle::RAMIProgInterface Class Reference
souffle::RAMIProgInterface Class Reference
Implementation of SouffleProgram interface for an interpreter instance.
#include <RAMIProgInterface.h>
Public Member Functions
void dumpInputs (std::ostream &) override
Dump inputs: not implemented.
void dumpOutputs (std::ostream &) override
Dump outputs: not implemented.
void executeSubroutine (std::string name, const std::vector< RamDomain > &args, std::vector< RamDomain > &ret, std::vector< bool > &err) override
Run subroutine.
SymbolTable & getSymbolTable () override
Get symbol table.
void loadAll (std::string) override
Load input data: not implemented.
void printAll (std::string) override
Print output data: not implemented.
RAMIProgInterface (RAMIInterface &interp)
void run (size_t) override
Run program instance: not implemented.
void runAll (std::string, std::string, size_t) override
Load data, run program instance, store data: not implemented.
~RAMIProgInterface () override
Public Member Functions inherited from souffle::SouffleProgram
std::vector< Relation * > getAllRelations () const
std::vector< Relation * > getInputRelations () const
std::vector< Relation * > getInternalRelations () const
std::vector< Relation * > getOutputRelations () const
Relation * getRelation (const std::string &name) const
void purgeInputRelations ()
void purgeInternalRelations ()
void purgeOutputRelations ()
virtual ~SouffleProgram ()=default
Private Attributes
RAMIInterface & exec
std::vector< RAMIRelInterface * > interfaces
const RamProgram & prog
SymbolTable & symTable
Additional Inherited Members
Protected Member Functions inherited from souffle::SouffleProgram
void addRelation (const std::string &name, Relation *rel, bool isInput, bool isOutput)
Detailed Description
Implementation of SouffleProgram interface for an interpreter instance.
Definition at line 174 of file RAMIProgInterface.h.
Constructor & Destructor Documentation
souffle::RAMIProgInterface::RAMIProgInterface (RAMIInterface & interp) inline
Definition at line 176 of file RAMIProgInterface.h.
References souffle::RAMIRelInterface::attrNames, souffle::RamRelation::getArg(), souffle::RamRelation::getArgTypeQualifier(), souffle::RamRelation::getArity(), souffle::RamRelation::getName(), souffle::RamRelationStatement::getRelation(), i, n, souffle::RAMIRelInterface::name, souffle::RAMIRelInterface::types, and souffle::visitDepthFirst().
             : prog(*interp.getTranslationUnit().getProgram()), exec(interp),
               symTable(interp.getTranslationUnit().getSymbolTable()) {
         uint32_t id = 0;
         // Retrieve AST Relations and store them in a map
         std::map<std::string, const RamRelation*> map;
         visitDepthFirst(prog, [&](const RamRelation& rel) { map[rel.getName()] = &rel; });
         // Build wrapper relations for Souffle's interface
         for (auto& rel_pair : exec.getRelationMap()) {
             auto& name = rel_pair.first;
             auto& interpreterRel = *rel_pair.second;
             assert(map[name]);
             const RamRelation& rel = *map[name];
             // construct types and names vectors
             std::vector<std::string> types;
             std::vector<std::string> attrNames;
             for (size_t i = 0; i < rel.getArity(); i++) {
                 std::string t = rel.getArgTypeQualifier(i);
                 types.push_back(t);
                 std::string n = rel.getArg(i);
                 attrNames.push_back(n);
             }
             auto* interface =
                     new RAMIRelInterface(interpreterRel, symTable, rel.getName(), types, attrNames, id);
             interfaces.push_back(interface);
             bool input;
             bool output;
             visitDepthFirst(prog, [&](const RamStore& store) {
                 if (store.getRelation() == rel) {
                     output = true;
                 }
             });
             visitDepthFirst(prog, [&](const RamLoad& load) {
                 if (load.getRelation() == rel) {
                     input = true;
                 }
             });
             addRelation(rel.getName(), interface, input, output);
             id++;
         }
     }
souffle::RAMIProgInterface::~RAMIProgInterface () inline override
Definition at line 221 of file RAMIProgInterface.h.
{
         for (auto* interface : interfaces) {
             delete interface;
         }
     }
Member Function Documentation
void souffle::RAMIProgInterface::dumpInputs (std::ostream &) inline override virtual
Dump inputs: not implemented.
Implements souffle::SouffleProgram.
Definition at line 240 of file RAMIProgInterface.h.
 {}
void souffle::RAMIProgInterface::dumpOutputs (std::ostream &) inline override virtual
Dump outputs: not implemented.
Implements souffle::SouffleProgram.
Definition at line 243 of file RAMIProgInterface.h.
 {}
void souffle::RAMIProgInterface::executeSubroutine (std::string name, const std::vector< RamDomain > & args, std::vector< RamDomain > & ret, std::vector< bool > & err) inline override virtual
Run subroutine.
Reimplemented from souffle::SouffleProgram.
Definition at line 246 of file RAMIProgInterface.h.
{
         exec.executeSubroutine(name, args, ret, err);
     }
SymbolTable& souffle::RAMIProgInterface::getSymbolTable () inline override virtual
Get symbol table.
Implements souffle::SouffleProgram.
Definition at line 252 of file RAMIProgInterface.h.
References souffle::RAMIRelInterface::symTable.
{
         return symTable;
     }
void souffle::RAMIProgInterface::loadAll (std::string) inline override virtual
Load input data: not implemented.
Implements souffle::SouffleProgram.
Definition at line 234 of file RAMIProgInterface.h.
 {}
void souffle::RAMIProgInterface::printAll (std::string) inline override virtual
Print output data: not implemented.
Implements souffle::SouffleProgram.
Definition at line 237 of file RAMIProgInterface.h.
 {}
void souffle::RAMIProgInterface::run (size_t) inline override virtual
Run program instance: not implemented.
Reimplemented from souffle::SouffleProgram.
Definition at line 228 of file RAMIProgInterface.h.
 {}
void souffle::RAMIProgInterface::runAll (std::string , std::string , size_t) inline override virtual
Load data, run program instance, store data: not implemented.
Implements souffle::SouffleProgram.
Definition at line 231 of file RAMIProgInterface.h.
 {}
Field Documentation
RAMIInterface& souffle::RAMIProgInterface::exec private
Definition at line 258 of file RAMIProgInterface.h.
std::vector<RAMIRelInterface*> souffle::RAMIProgInterface::interfaces private
Definition at line 260 of file RAMIProgInterface.h.
const RamProgram& souffle::RAMIProgInterface::prog private
Definition at line 257 of file RAMIProgInterface.h.
SymbolTable& souffle::RAMIProgInterface::symTable private
Definition at line 259 of file RAMIProgInterface.h.
The documentation for this class was generated from the following file:
RAMIProgInterface.h