souffle: souffle::RamUnpackRecord Class Reference
souffle::RamUnpackRecord Class Reference
Record lookup.
#include <RamOperation.h>
Public Member Functions
void apply (const RamNodeMapper &map) override
Apply the mapper to all child nodes.
RamUnpackRecord * clone () const override
Create a clone (i.e.
std::size_t getArity () const
Get arity of record.
std::vector< const RamNode * > getChildNodes () const override
Obtain list of all embedded child nodes.
const RamExpression & getExpression () const
Get record expression.
void print (std::ostream &os, int tabpos) const override
Pretty print with indentation.
RamUnpackRecord (std::unique_ptr< RamOperation > nested, int ident, std::unique_ptr< RamExpression > expr, size_t arity)
Public Member Functions inherited from souffle::RamTupleOperation
int getTupleId () const
Get identifier.
RamTupleOperation (int ident, std::unique_ptr< RamOperation > nested, std::string profileText="")
void setTupleId (int id)
Set identifier.
Public Member Functions inherited from souffle::RamNestedOperation
RamOperation & getOperation () const
Get nested operation.
const std::string & getProfileText () const
Get profile text.
RamNestedOperation (std::unique_ptr< RamOperation > nested, std::string profileText="")
Public Member Functions inherited from souffle::RamOperation
void print (std::ostream &os) const override
Print RAM node.
Public Member Functions inherited from souffle::RamNode
bool operator!= (const RamNode &other) const
Inequality check for two RAM nodes.
bool operator== (const RamNode &other) const
Equivalence check for two RAM nodes.
RamNode ()=default
virtual ~RamNode ()=default
Protected Member Functions
bool equal (const RamNode &node) const override
Equality check for two RAM nodes.
Protected Attributes
const size_t arity
Arity of the unpacked tuple.
std::unique_ptr< RamExpression > expression
Expression for record reference.
Protected Attributes inherited from souffle::RamTupleOperation
int identifier
Identifier for the tuple, corresponding to its position in the loop nest.
Protected Attributes inherited from souffle::RamNestedOperation
std::unique_ptr< RamOperation > nestedOperation
Nested operation.
const std::string profileText
Text used by the profiler.
Detailed Description
Record lookup.
Looks up a record with respect to an expression
For example:
UNPACK t0.0 INTO t1
Definition at line 839 of file RamOperation.h.
Constructor & Destructor Documentation
souffle::RamUnpackRecord::RamUnpackRecord (std::unique_ptr< RamOperation > nested, int ident, std::unique_ptr< RamExpression > expr, size_t arity) inline
Definition at line 841 of file RamOperation.h.
             : RamTupleOperation(ident, std::move(nested)), expression(std::move(expr)), arity(arity) {}
Member Function Documentation
void souffle::RamUnpackRecord::apply (const RamNodeMapper & mapper) inline override virtual
Apply the mapper to all child nodes.
Reimplemented from souffle::RamNestedOperation.
Definition at line 872 of file RamOperation.h.
References souffle::RamNestedOperation::apply().
{
         RamTupleOperation::apply(map);
         expression = map(std::move(expression));
     }
RamUnpackRecord* souffle::RamUnpackRecord::clone () const inline override virtual
Create a clone (i.e.
deep copy) of this node
Implements souffle::RamOperation.
Definition at line 867 of file RamOperation.h.
References arity, and souffle::RamOperation::clone().
{
         return new RamUnpackRecord(std::unique_ptr<RamOperation>(getOperation().clone()), getTupleId(),
                 std::unique_ptr<RamExpression>(getExpression().clone()), arity);
     }
bool souffle::RamUnpackRecord::equal (const RamNode & other) const inline override protected virtual
Equality check for two RAM nodes.
Default action is that nothing needs to be checked.
Reimplemented from souffle::RamTupleOperation.
Definition at line 884 of file RamOperation.h.
References souffle::RamTupleOperation::equal().
{
         assert(nullptr != dynamic_cast<const RamUnpackRecord*>(&node));
         const auto& other = static_cast<const RamUnpackRecord&>(node);
         return RamTupleOperation::equal(other) && getExpression() == other.getExpression() &&
                getArity() == other.getArity();
     }
std::size_t souffle::RamUnpackRecord::getArity () const inline
Get arity of record.
Definition at line 852 of file RamOperation.h.
References arity.
Referenced by souffle::Synthesiser::emitCode(), souffle::RAMI::evalOp(), and souffle::LVMGenerator::visitUnpackRecord().
{
         return arity;
     }
std::vector<const RamNode*> souffle::RamUnpackRecord::getChildNodes () const inline override virtual
Obtain list of all embedded child nodes.
Reimplemented from souffle::RamTupleOperation.
Definition at line 856 of file RamOperation.h.
References souffle::RamTupleOperation::getChildNodes().
{
         auto res = RamTupleOperation::getChildNodes();
         res.push_back(expression.get());
         return res;
     }
const RamExpression& souffle::RamUnpackRecord::getExpression () const inline
Get record expression.
Definition at line 846 of file RamOperation.h.
Referenced by souffle::Synthesiser::emitCode(), souffle::RAMI::evalOp(), souffle::RamLevelAnalysis::getLevel(), and souffle::LVMGenerator::visitUnpackRecord().
{
         assert(expression != nullptr && "Expression of unpack-record is a null-pointer");
         return *expression;
     }
void souffle::RamUnpackRecord::print (std::ostream & os, int tabpos) const inline override virtual
Pretty print with indentation.
Reimplemented from souffle::RamNestedOperation.
Definition at line 862 of file RamOperation.h.
References souffle::RamNestedOperation::print(), and souffle::times().
{
         os << times(" ", tabpos) << "UNPACK " << getExpression() << " INTO t" << getTupleId() << std::endl;
         RamTupleOperation::print(os, tabpos + 1);
     }
Field Documentation
const size_t souffle::RamUnpackRecord::arity protected
Arity of the unpacked tuple.
Definition at line 882 of file RamOperation.h.
std::unique_ptr<RamExpression> souffle::RamUnpackRecord::expression protected
Expression for record reference.
Definition at line 879 of file RamOperation.h.
The documentation for this class was generated from the following file:
RamOperation.h