souffle: souffle::MinIndexSelection Class Reference
souffle::MinIndexSelection Class Reference
computes the minimal index cover for a relation in a RAM Program.
#include <RamIndexAnalysis.h>
Public Types
using Chain = std::set< SearchSignature >
using ChainOrderMap = std::vector< Chain >
using LexOrder = std::vector< int >
using OrderCollection = std::vector< LexOrder >
using SearchSet = std::set< SearchSignature >
Public Member Functions
void addSearch (SearchSignature cols)
Add new key to an Index Set
const ChainOrderMap getAllChains () const
Get all chains
const OrderCollection getAllOrders () const
Get all indexes
const LexOrder getLexOrder (SearchSignature cols) const
Get index for a search
const int getLexOrderNum (SearchSignature cols) const
Get index for a search
const SearchSet & getSearches () const
Get searches
void insertDefaultTotalIndex (size_t arity)
insert a total order index
bool isSubset (SearchSignature cols) const
check whether number of bits in k is not equal to number of columns in lexicographical order
MinIndexSelection ()=default
void solve ()
map the keys in the key set to lexicographical order
~MinIndexSelection ()=default
Static Public Member Functions
static SearchSignature toA (SearchSignature b)
convert from a representation of B vertices to A vertices
static SearchSignature toB (SearchSignature a)
convert from a representation of A vertices to B vertices
Protected Member Functions
Chain getChain (const SearchSignature umn, const MaxMatching::Matchings &match)
get a chain from a matching
const ChainOrderMap getChainsFromMatching (const MaxMatching::Matchings &match, const SearchSet &nodes)
get all chains from the matching
const SearchSet getUnmatchedKeys (const MaxMatching::Matchings &match, const SearchSet &nodes)
get all nodes which are unmatched from A-> B
void insertIndex (LexOrder &ids, SearchSignature delta)
insert an index based on the delta
int map (SearchSignature cols) const
maps search columns to an lexicographical order (labeled by a number)
Static Protected Member Functions
static size_t card (SearchSignature cols)
count the number of bits in key
static bool isStrictSubset (SearchSignature a, SearchSignature b)
determine if key a is a strict subset of key b
Protected Attributes
ChainOrderMap chainToOrder
MaxMatching matching
OrderCollection orders
SearchSet searches
Detailed Description
computes the minimal index cover for a relation in a RAM Program.
If the indexes of a relation can cover several searches, the minimal set of indexes is computed by Dilworth's problem. See
"Automatic Index Selection for Large-Scale Datalog Computation" http://www.vldb.org/pvldb/vol12/p141-subotic.pdf
Definition at line 152 of file RamIndexAnalysis.h.
Member Typedef Documentation
using souffle::MinIndexSelection::Chain = std::set<SearchSignature>
Definition at line 156 of file RamIndexAnalysis.h.
using souffle::MinIndexSelection::ChainOrderMap = std::vector<Chain>
Definition at line 157 of file RamIndexAnalysis.h.
using souffle::MinIndexSelection::LexOrder = std::vector<int>
Definition at line 154 of file RamIndexAnalysis.h.
using souffle::MinIndexSelection::OrderCollection = std::vector<LexOrder>
Definition at line 155 of file RamIndexAnalysis.h.
using souffle::MinIndexSelection::SearchSet = std::set<SearchSignature>
Definition at line 158 of file RamIndexAnalysis.h.
Constructor & Destructor Documentation
souffle::MinIndexSelection::MinIndexSelection () default
souffle::MinIndexSelection::~MinIndexSelection () default
Member Function Documentation
void souffle::MinIndexSelection::addSearch (SearchSignature cols) inline
Add new key to an Index Set
Definition at line 164 of file RamIndexAnalysis.h.
Referenced by souffle::RamIndexAnalysis::run().
{
         if (cols != 0) {
             searches.insert(cols);
         }
     }
static size_t souffle::MinIndexSelection::card (SearchSignature cols) inline static protected
count the number of bits in key
Definition at line 242 of file RamIndexAnalysis.h.
References i.
{
         size_t sz = 0, idx = 1;
         for (size_t i = 0; i < sizeof(SearchSignature) * 8; i++) {
             if (idx & cols) {
                 sz++;
             }
             idx *= 2;
         }
         return sz;
     }
const ChainOrderMap souffle::MinIndexSelection::getAllChains () const inline
Get all chains
Definition at line 192 of file RamIndexAnalysis.h.
{
         return chainToOrder;
     }
const OrderCollection souffle::MinIndexSelection::getAllOrders () const inline
Get all indexes
Definition at line 187 of file RamIndexAnalysis.h.
Referenced by souffle::SynthesiserDirectRelation::computeIndices(), souffle::SynthesiserIndirectRelation::computeIndices(), souffle::SynthesiserBrieRelation::computeIndices(), souffle::SynthesiserDirectRelation::generateTypeStruct(), souffle::SynthesiserIndirectRelation::generateTypeStruct(), souffle::SynthesiserBrieRelation::generateTypeStruct(), souffle::LVMRelation::LVMRelation(), souffle::RamIndexAnalysis::print(), souffle::RAMIRelation::RAMIRelation(), and souffle::RamIndexAnalysis::run().
{
         return orders;
     }
MinIndexSelection::Chain souffle::MinIndexSelection::getChain (const SearchSignature umn, const MaxMatching::Matchings & match) protected
get a chain from a matching
Parameters
Starting node of a chain
Matching
Returns
A minimal chain given an unmapped node from set A we follow it from set B until it cannot be matched from B if not matched from B then umn is a chain.
Definition at line 208 of file RamIndexAnalysis.cpp.
{
     SearchSignature start = umn;  // start at an unmateched node
     Chain chain;
     // given an unmapped node from set A we follow it from set B until it cannot be matched from B
     //  if not mateched from B then umn is a chain
     //
     // Assume : no circular mappings, i.e. a in A -> b in B -> ........ -> a in A is not allowed.
     // Given this, the loop will terminate
     while (true) {
         auto mit = match.find(toB(start));  // we start from B side
         chain.insert(start);
         if (mit == match.end()) {
             return chain;
         }
         SearchSignature a = mit->second;
         chain.insert(a);
         start = a;
     }
 }
const MinIndexSelection::ChainOrderMap souffle::MinIndexSelection::getChainsFromMatching (const MaxMatching::Matchings & match, const SearchSet & nodes) protected
get all chains from the matching
Definition at line 231 of file RamIndexAnalysis.cpp.
{
     assert(!nodes.empty());
     // Get all unmatched nodes from A
     const SearchSet& umKeys = getUnmatchedKeys(match, nodes);
     // Case: if no unmatched nodes then we have an anti-chain
     if (umKeys.empty()) {
         for (auto node : nodes) {
             std::set<SearchSignature> a;
             a.insert(node);
             chainToOrder.push_back(a);
             return chainToOrder;
         }
     }
     assert(!umKeys.empty());
     // A worklist of used nodes
     SearchSet usedKeys;
     // Case: nodes < umKeys or if nodes == umKeys then anti chain - this is handled by this loop
     for (auto umKey : umKeys) {
         Chain c = getChain(umKey, match);
         assert(!c.empty());
         chainToOrder.push_back(c);
     }
     assert(!chainToOrder.empty());
     return chainToOrder;
 }
const LexOrder souffle::MinIndexSelection::getLexOrder (SearchSignature cols) const inline
Get index for a search
Definition at line 176 of file RamIndexAnalysis.h.
Referenced by souffle::SynthesiserDirectRelation::generateTypeStruct(), souffle::SynthesiserIndirectRelation::generateTypeStruct(), and souffle::SynthesiserBrieRelation::generateTypeStruct().
{
         int idx = map(cols);
         return orders[idx];
     }
const int souffle::MinIndexSelection::getLexOrderNum (SearchSignature cols) const inline
Get index for a search
Definition at line 182 of file RamIndexAnalysis.h.
Referenced by souffle::RAMIRelation::getIndex(), and souffle::LVMGenerator::getIndexPos().
{
         return map(cols);
     }
const SearchSet& souffle::MinIndexSelection::getSearches () const inline
Get searches
Definition at line 171 of file RamIndexAnalysis.h.
Referenced by souffle::RamIndexAnalysis::print(), and souffle::RamIndexAnalysis::run().
{
         return searches;
     }
const SearchSet souffle::MinIndexSelection::getUnmatchedKeys (const MaxMatching::Matchings & match, const SearchSet & nodes) inline protected
get all nodes which are unmatched from A-> B
Definition at line 302 of file RamIndexAnalysis.h.
{
         SearchSet unmatched;
         // For all nodes n such that n is not in match
         for (auto node : nodes) {
             if (match.find(node) == match.end()) {
                 unmatched.insert(node);
             }
         }
         return unmatched;
     }
void souffle::MinIndexSelection::insertDefaultTotalIndex (size_t arity) inline
insert a total order index
Parameters
size of the index
Definition at line 223 of file RamIndexAnalysis.h.
References arity, and i.
Referenced by souffle::RamIndexAnalysis::run().
{
         Chain chain = std::set<SearchSignature>();
         SearchSignature fullIndexKey = (1 << arity) - 1;
         chain.insert(fullIndexKey);
         chainToOrder.push_back(std::move(chain));
         LexOrder totalOrder;
         for (size_t i = 0; i < arity; ++i) {
             totalOrder.push_back(i);
         }
         orders.push_back(std::move(totalOrder));
     }
void souffle::MinIndexSelection::insertIndex (LexOrder & ids, SearchSignature delta) inline protected
insert an index based on the delta
Definition at line 274 of file RamIndexAnalysis.h.
References souffle::MaxMatching::match.
{
         int pos = 0;
         SearchSignature mask = 0;
         while (mask < delta) {
             mask = SearchSignature(1 << (pos));
             SearchSignature result = (delta) & (mask);
             if (result) {
                 ids.push_back(pos);
             }
             pos++;
         }
     }
static bool souffle::MinIndexSelection::isStrictSubset (SearchSignature a, SearchSignature b) inline static protected
determine if key a is a strict subset of key b
Definition at line 268 of file RamIndexAnalysis.h.
References b.
{
         auto tt = static_cast<SearchSignature>(std::numeric_limits<SearchSignature>::max());
         return (~(a) | (b)) == tt && a != b;
     }
bool souffle::MinIndexSelection::isSubset (SearchSignature cols) const inline
check whether number of bits in k is not equal to number of columns in lexicographical order
Definition at line 198 of file RamIndexAnalysis.h.
References souffle::MaxMatching::solve().
{
         int idx = map(cols);
         return card(cols) < orders[idx].size();
     }
int souffle::MinIndexSelection::map (SearchSignature cols) const inline protected
maps search columns to an lexicographical order (labeled by a number)
Definition at line 254 of file RamIndexAnalysis.h.
References i.
{
         assert(orders.size() == chainToOrder.size() && "Order and Chain Sizes do not match!!");
         int i = 0;
         for (auto it = chainToOrder.begin(); it != chainToOrder.end(); ++it, ++i) {
             if (it->find(cols) != it->end()) {
                 assert((size_t)i < orders.size());
                 return i;
             }
         }
         std::cerr << "Cannot find matching lexicographical order" << std::endl;
         abort();
     }
void souffle::MinIndexSelection::solve ()
map the keys in the key set to lexicographical order
Definition at line 118 of file RamIndexAnalysis.cpp.
References i, k, and l.
Referenced by souffle::RamIndexAnalysis::run().
{
     // map the keys in the key set to lexicographical order
     if (searches.empty()) {
         return;
     }
     // check whether one of the naive indexers should be used
     // two conditions: either set by environment or relation is a hash map
     static const char ENV_NAIVE_INDEX[] = "SOUFFLE_USE_NAIVE_INDEX";
     if (std::getenv(ENV_NAIVE_INDEX)) {
         static bool first = true;
         // print a warning - only the first time
         if (first) {
             std::cout << "WARNING: auto index selection disabled, naive indexes are utilized!!\n";
             first = false;
         }
         // every search pattern gets its naive index
         for (SearchSignature cur : searches) {
             // obtain order
             LexOrder order;
             SearchSignature mask = cur;
             for (int i = 0; mask != 0; i++) {
                 if (!(1 << i & mask)) {
                     continue;
                 }
                 order.push_back(i);
                 // clear bit
                 mask &= ~(1 << i);
             }
             // add new order
             orders.push_back(order);
             // register pseudo chain
             chainToOrder.push_back(Chain());
             chainToOrder.back().insert(cur);
         }
         return;
     }
     // Construct the matching poblem
     for (auto search : searches) {
         // For this node check if other nodes are strict subsets
         for (auto itt : searches) {
             if (isStrictSubset(search, itt)) {
                 matching.addEdge(search, toB(itt));
             }
         }
     }
     // Perform the Hopcroft-Karp on the graph and receive matchings (mapped A->B and B->A)
     // Assume: alg.calculate is not called on an empty graph
     assert(!searches.empty());
     const MaxMatching::Matchings& matchings = matching.solve();
     // Extract the chains given the nodes and matchings
     const ChainOrderMap chains = getChainsFromMatching(matchings, searches);
     // Should never get no chains back as we never call calculate on an empty graph
     assert(!chains.empty());
     for (const auto& chain : chains) {
         std::vector<int> ids;
         SearchSignature initDelta = *(chain.begin());
         insertIndex(ids, initDelta);
         for (auto iit = chain.begin(); next(iit) != chain.end(); ++iit) {
             SearchSignature delta = *(next(iit)) - *iit;
             insertIndex(ids, delta);
         }
         assert(!ids.empty());
         orders.push_back(ids);
     }
     // Construct the matching poblem
     for (auto search : searches) {
         int idx = map(search);
         size_t l = card(search);
         SearchSignature k = 0;
         for (size_t i = 0; i < l; i++) {
             k = k + (1 << (orders[idx][i]));
         }
         assert(k == search && "incorrect lexicographical order");
     }
 }
static SearchSignature souffle::MinIndexSelection::toA (SearchSignature b) inline static
convert from a representation of B vertices to A vertices
Definition at line 214 of file RamIndexAnalysis.h.
{
         SearchSignature msb = 1;
         msb <<= (4 * 8 - 1);
         return (b xor msb);
     }
static SearchSignature souffle::MinIndexSelection::toB (SearchSignature a) inline static
convert from a representation of A vertices to B vertices
Definition at line 207 of file RamIndexAnalysis.h.
{
         SearchSignature msb = 1;
         msb <<= (4 * 8 - 1);
         return (a | msb);
     }
Field Documentation
ChainOrderMap souffle::MinIndexSelection::chainToOrder protected
Definition at line 238 of file RamIndexAnalysis.h.
MaxMatching souffle::MinIndexSelection::matching protected
Definition at line 239 of file RamIndexAnalysis.h.
OrderCollection souffle::MinIndexSelection::orders protected
Definition at line 237 of file RamIndexAnalysis.h.
SearchSet souffle::MinIndexSelection::searches protected
Definition at line 236 of file RamIndexAnalysis.h.
The documentation for this class was generated from the following files:
RamIndexAnalysis.h
RamIndexAnalysis.cpp