souffle: souffle::RamConstraint Class Reference
souffle::RamConstraint Class Reference
Evaluates a binary constraint with respect to two RamExpressions.
#include <RamCondition.h>
Public Member Functions
void apply (const RamNodeMapper &map) override
Apply the mapper to all child nodes.
RamConstraint * clone () const override
Create a clone (i.e.
std::vector< const RamNode * > getChildNodes () const override
Obtain list of all embedded child nodes.
const RamExpression & getLHS () const
Get left-hand side.
BinaryConstraintOp getOperator () const
Get operator symbol.
const RamExpression & getRHS () const
Get right-hand side.
void print (std::ostream &os) const override
Print RAM node.
RamConstraint (BinaryConstraintOp op, std::unique_ptr< RamExpression > l, std::unique_ptr< RamExpression > r)
Public Member Functions inherited from souffle::RamNode
bool operator!= (const RamNode &other) const
Inequality check for two RAM nodes.
bool operator== (const RamNode &other) const
Equivalence check for two RAM nodes.
RamNode ()=default
virtual ~RamNode ()=default
Protected Member Functions
bool equal (const RamNode &node) const override
Equality check for two RAM nodes.
Protected Attributes
std::unique_ptr< RamExpression > lhs
Left-hand side of constraint.
BinaryConstraintOp op
Operator.
std::unique_ptr< RamExpression > rhs
Right-hand side of constraint.
Detailed Description
Evaluates a binary constraint with respect to two RamExpressions.
Condition is true if the constraint (a logical operator such as "<") holds between the two operands
The following example checks the equality of the two given tuple elements:
t0.1 = t1.0
Definition at line 214 of file RamCondition.h.
Constructor & Destructor Documentation
souffle::RamConstraint::RamConstraint (BinaryConstraintOp op, std::unique_ptr< RamExpression > l, std::unique_ptr< RamExpression > r) inline
Definition at line 216 of file RamCondition.h.
             : op(op), lhs(std::move(l)), rhs(std::move(r)) {}
Member Function Documentation
void souffle::RamConstraint::apply (const RamNodeMapper & mapper) inline override virtual
Apply the mapper to all child nodes.
Reimplemented from souffle::RamNode.
Definition at line 253 of file RamCondition.h.
References lhs, and rhs.
{
         lhs = map(std::move(lhs));
         rhs = map(std::move(rhs));
     }
RamConstraint* souffle::RamConstraint::clone () const inline override virtual
Create a clone (i.e.
deep copy) of this node
Implements souffle::RamCondition.
Definition at line 248 of file RamCondition.h.
References lhs, and rhs.
{
         return new RamConstraint(op, std::unique_ptr<RamExpression>(lhs->clone()),
                 std::unique_ptr<RamExpression>(rhs->clone()));
     }
bool souffle::RamConstraint::equal (const RamNode & other) const inline override protected virtual
Equality check for two RAM nodes.
Default action is that nothing needs to be checked.
Reimplemented from souffle::RamNode.
Definition at line 268 of file RamCondition.h.
References getOperator().
{
         assert(nullptr != dynamic_cast<const RamConstraint*>(&node));
         const auto& other = static_cast<const RamConstraint&>(node);
         return getOperator() == other.getOperator() && getLHS() == other.getLHS() &&
                getRHS() == other.getRHS();
     }
std::vector<const RamNode*> souffle::RamConstraint::getChildNodes () const inline override virtual
Obtain list of all embedded child nodes.
Reimplemented from souffle::RamNode.
Definition at line 244 of file RamCondition.h.
References lhs, and rhs.
{
         return {lhs.get(), rhs.get()};
     }
const RamExpression& souffle::RamConstraint::getLHS () const inline
Get left-hand side.
Definition at line 228 of file RamCondition.h.
References lhs.
Referenced by souffle::Synthesiser::emitCode(), souffle::RAMI::evalCond(), souffle::RamLevelAnalysis::getLevel(), and souffle::LVMGenerator::visitConstraint().
{
         assert(lhs != nullptr && "left-hand side of constraint is a null-pointer");
         return *lhs;
     }
BinaryConstraintOp souffle::RamConstraint::getOperator () const inline
Get operator symbol.
Definition at line 240 of file RamCondition.h.
Referenced by souffle::Synthesiser::emitCode(), equal(), souffle::RAMI::evalCond(), and souffle::LVMGenerator::visitConstraint().
{
         return op;
     }
const RamExpression& souffle::RamConstraint::getRHS () const inline
Get right-hand side.
Definition at line 234 of file RamCondition.h.
References rhs.
Referenced by souffle::Synthesiser::emitCode(), souffle::RAMI::evalCond(), souffle::RamLevelAnalysis::getLevel(), and souffle::LVMGenerator::visitConstraint().
{
         assert(rhs != nullptr && "right-hand side of constraint is a null-pointer");
         return *rhs;
     }
void souffle::RamConstraint::print (std::ostream & out) const inline override virtual
Print RAM node.
Implements souffle::RamNode.
Definition at line 219 of file RamCondition.h.
References lhs, rhs, and souffle::toBinaryConstraintSymbol().
{
         os << "(";
         lhs->print(os);
         os << " " << toBinaryConstraintSymbol(op) << " ";
         rhs->print(os);
         os << ")";
     }
Field Documentation
std::unique_ptr<RamExpression> souffle::RamConstraint::lhs protected
Left-hand side of constraint.
Definition at line 263 of file RamCondition.h.
BinaryConstraintOp souffle::RamConstraint::op protected
Operator.
Definition at line 260 of file RamCondition.h.
std::unique_ptr<RamExpression> souffle::RamConstraint::rhs protected
Right-hand side of constraint.
Definition at line 266 of file RamCondition.h.
The documentation for this class was generated from the following file:
RamCondition.h