souffle: souffle::RamProgram Class Reference
souffle::RamProgram Class Reference
RAM program relation declaration and functions.
#include <RamProgram.h>
Public Member Functions
void addRelation (std::unique_ptr< RamRelation > rel)
Add relation.
void addSubroutine (std::string name, std::unique_ptr< RamStatement > subroutine)
Add subroutine.
void apply (const RamNodeMapper &map) override
Apply the mapper to all child nodes.
RamProgram * clone () const override
Create a clone (i.e.
const std::map< std::string, std::unique_ptr< RamRelation > > & getAllRelations () const
Get relations map.
std::vector< const RamNode * > getChildNodes () const override
Obtain list of all embedded child nodes.
RamStatement * getMain () const
Get main program.
const RamRelation * getRelation (const std::string &name) const
Get relation.
const RamStatement & getSubroutine (const std::string &name) const
Get subroutine.
const std::map< std::string, RamStatement * > getSubroutines () const
Get subroutines.
void print (std::ostream &out) const override
Print RAM node.
RamProgram ()=default
RamProgram (std::unique_ptr< RamStatement > main)
void setMain (std::unique_ptr< RamStatement > stmt)
Set a statement to main.
Public Member Functions inherited from souffle::RamNode
bool operator!= (const RamNode &other) const
Inequality check for two RAM nodes.
bool operator== (const RamNode &other) const
Equivalence check for two RAM nodes.
RamNode ()=default
virtual ~RamNode ()=default
Protected Member Functions
bool equal (const RamNode &node) const override
Equality check for two RAM nodes.
Protected Attributes
std::unique_ptr< RamStatement > main
Main program.
std::map< std::string, std::unique_ptr< RamRelation > > relations
Relations of RAM program.
std::map< std::string, std::unique_ptr< RamStatement > > subroutines
Subroutines for querying computed relations.
Detailed Description
RAM program relation declaration and functions.
A typical example:
PROGRAM
  DECLARATION
    A(x:i:number)
  END DECLARATION
  BEGIN MAIN
    ...
  END MAIN
END PROGRAM
Definition at line 40 of file RamProgram.h.
Constructor & Destructor Documentation
souffle::RamProgram::RamProgram () default
Referenced by clone().
souffle::RamProgram::RamProgram (std::unique_ptr< RamStatement > main) inline
Definition at line 43 of file RamProgram.h.
 : RamNode(), main(std::move(main)) {}
Member Function Documentation
void souffle::RamProgram::addRelation (std::unique_ptr< RamRelation > rel) inline
Add relation.
Definition at line 89 of file RamProgram.h.
References relations.
{
         relations.insert(std::make_pair(rel->getName(), std::move(rel)));
     }
void souffle::RamProgram::addSubroutine (std::string name, std::unique_ptr< RamStatement > subroutine) inline
Add subroutine.
Definition at line 109 of file RamProgram.h.
References subroutines.
{
         subroutines.insert(std::make_pair(name, std::move(subroutine)));
     }
void souffle::RamProgram::apply (const RamNodeMapper & mapper) inline override virtual
Apply the mapper to all child nodes.
Reimplemented from souffle::RamNode.
Definition at line 151 of file RamProgram.h.
References main, relations, and subroutines.
{
         main = map(std::move(main));
         for (auto& cur : relations) {
             cur.second = map(std::move(cur.second));
         }
         for (auto& cur : subroutines) {
             cur.second = map(std::move(cur.second));
         }
     }
RamProgram* souffle::RamProgram::clone () const inline override virtual
Create a clone (i.e.
deep copy) of this node
Implements souffle::RamNode.
Definition at line 127 of file RamProgram.h.
References souffle::RamNode::apply(), souffle::RamRelation::clone(), main, souffle::makeLambdaRamMapper(), RamProgram(), relations, and subroutines.
{
         std::map<const RamRelation*, const RamRelation*> refMap;
         auto* res = new RamProgram(std::unique_ptr<RamStatement>(main->clone()));
         for (auto& cur : relations) {
             RamRelation* newRel = cur.second->clone();
             refMap[cur.second.get()] = newRel;
             res->addRelation(std::unique_ptr<RamRelation>(newRel));
         }
         for (auto& cur : subroutines) {
             res->addSubroutine(cur.first, std::unique_ptr<RamStatement>(cur.second->clone()));
         }
         res->apply(makeLambdaRamMapper([&](std::unique_ptr<RamNode> node) -> std::unique_ptr<RamNode> {
             // check whether it is a unnamed variable
             if (const RamRelationReference* relRef = dynamic_cast<RamRelationReference*>(node.get())) {
                 const RamRelation* rel = refMap[relRef->get()];
                 assert(rel != nullptr && "dangling RAM relation reference");
                 return std::make_unique<RamRelationReference>(rel);
             } else {
                 return node;
             }
         }));
         return res;
     }
bool souffle::RamProgram::equal (const RamNode & other) const inline override protected virtual
Equality check for two RAM nodes.
Default action is that nothing needs to be checked.
Reimplemented from souffle::RamNode.
Definition at line 171 of file RamProgram.h.
References getMain(), getRelation(), and getSubroutine().
{
         assert(nullptr != dynamic_cast<const RamProgram*>(&node));
         const auto& other = static_cast<const RamProgram&>(node);
         if (relations.size() != other.relations.size() || subroutines.size() != other.subroutines.size()) {
             return false;
         }
         for (auto& cur : subroutines) {
             if (other.getSubroutine(cur.first) != getSubroutine(cur.first)) {
                 return false;
             }
         }
         for (auto& cur : relations) {
             if (other.getRelation(cur.first) != getRelation(cur.first)) {
                 return false;
             }
         }
         return getMain() == other.getMain();
     }
const std::map<std::string, std::unique_ptr<RamRelation> >& souffle::RamProgram::getAllRelations () const inline
Get relations map.
Definition at line 104 of file RamProgram.h.
References relations.
Referenced by souffle::RelationEncoder::RelationEncoder().
{
         return this->relations;
     }
std::vector<const RamNode*> souffle::RamProgram::getChildNodes () const inline override virtual
Obtain list of all embedded child nodes.
Reimplemented from souffle::RamNode.
Definition at line 45 of file RamProgram.h.
References main, relations, and subroutines.
{
         std::vector<const RamNode*> children;
         children = main->getChildNodes();
         for (auto& r : relations) {
             children.push_back(r.second.get());
         }
         for (auto& s : subroutines) {
             children.push_back(s.second.get());
         }
         return children;
     }
RamStatement* souffle::RamProgram::getMain () const inline
Get main program.
Definition at line 83 of file RamProgram.h.
References main.
Referenced by equal(), souffle::RAMI::executeMain(), souffle::LVM::executeMain(), souffle::Synthesiser::generateCode(), and souffle::LVM::printMain().
{
         assert(main && "Program has no main routine");
         return main.get();
     }
const RamRelation* souffle::RamProgram::getRelation (const std::string & name) const inline
Get relation.
Definition at line 94 of file RamProgram.h.
References relations.
Referenced by equal().
{
         auto it = relations.find(name);
         if (it != relations.end()) {
             return it->second.get();
         } else {
             return nullptr;
         }
     }
const RamStatement& souffle::RamProgram::getSubroutine (const std::string & name) const inline
Get subroutine.
Definition at line 123 of file RamProgram.h.
References subroutines.
Referenced by equal(), souffle::RAMI::executeSubroutine(), and souffle::LVM::executeSubroutine().
{
         return *subroutines.at(name);
     }
const std::map<std::string, RamStatement*> souffle::RamProgram::getSubroutines () const inline
Get subroutines.
Definition at line 114 of file RamProgram.h.
References subroutines.
Referenced by souffle::Synthesiser::generateCode().
{
         std::map<std::string, RamStatement*> subroutineRefs;
         for (auto& s : subroutines) {
             subroutineRefs.insert({s.first, s.second.get()});
         }
         return subroutineRefs;
     }
void souffle::RamProgram::print (std::ostream & out) const inline override virtual
Print RAM node.
Implements souffle::RamNode.
Definition at line 57 of file RamProgram.h.
References main, relations, and subroutines.
{
         out << "PROGRAM" << std::endl;
         out << " DECLARATION" << std::endl;
         for (const auto& rel : relations) {
             out << "  ";
             rel.second->print(out);
             out << std::endl;
         }
         out << " END DECLARATION" << std::endl;
         for (const auto& subroutine : subroutines) {
             out << " SUBROUTINE " << subroutine.first << std::endl;
             subroutine.second->print(out, 2);
             out << " END SUBROUTINE" << std::endl;
         }
         out << " BEGIN MAIN" << std::endl;
         main->print(out, 2);
         out << " END MAIN" << std::endl;
         out << "END PROGRAM" << std::endl;
     }
void souffle::RamProgram::setMain (std::unique_ptr< RamStatement > stmt) inline
Set a statement to main.
Definition at line 78 of file RamProgram.h.
References main.
{
         main = std::move(stmt);
     }
Field Documentation
std::unique_ptr<RamStatement> souffle::RamProgram::main protected
Main program.
Definition at line 166 of file RamProgram.h.
Referenced by apply(), clone(), getChildNodes(), getMain(), print(), and setMain().
std::map<std::string, std::unique_ptr<RamRelation> > souffle::RamProgram::relations protected
Relations of RAM program.
Definition at line 163 of file RamProgram.h.
Referenced by addRelation(), apply(), clone(), getAllRelations(), getChildNodes(), getRelation(), and print().
std::map<std::string, std::unique_ptr<RamStatement> > souffle::RamProgram::subroutines protected
Subroutines for querying computed relations.
Definition at line 169 of file RamProgram.h.
Referenced by addSubroutine(), apply(), clone(), getChildNodes(), getSubroutine(), getSubroutines(), and print().
The documentation for this class was generated from the following file:
RamProgram.h