souffle: souffle::RamTupleOperation Class Reference
souffle::RamTupleOperation Class Reference
Abstract class for relation searches and lookups.
#include <RamOperation.h>
Public Member Functions
std::vector< const RamNode * > getChildNodes () const override
Obtain list of all embedded child nodes.
int getTupleId () const
Get identifier.
RamTupleOperation (int ident, std::unique_ptr< RamOperation > nested, std::string profileText="")
void setTupleId (int id)
Set identifier.
Public Member Functions inherited from souffle::RamNestedOperation
void apply (const RamNodeMapper &map) override
Apply the mapper to all child nodes.
RamOperation & getOperation () const
Get nested operation.
const std::string & getProfileText () const
Get profile text.
void print (std::ostream &os, int tabpos) const override
Pretty print with indentation.
RamNestedOperation (std::unique_ptr< RamOperation > nested, std::string profileText="")
Public Member Functions inherited from souffle::RamOperation
RamOperation * clone () const override=0
Create a clone (i.e.
void print (std::ostream &os) const override
Print RAM node.
Public Member Functions inherited from souffle::RamNode
bool operator!= (const RamNode &other) const
Inequality check for two RAM nodes.
bool operator== (const RamNode &other) const
Equivalence check for two RAM nodes.
RamNode ()=default
virtual ~RamNode ()=default
Protected Member Functions
bool equal (const RamNode &node) const override
Equality check for two RAM nodes.
Protected Attributes
int identifier
Identifier for the tuple, corresponding to its position in the loop nest.
Protected Attributes inherited from souffle::RamNestedOperation
std::unique_ptr< RamOperation > nestedOperation
Nested operation.
const std::string profileText
Text used by the profiler.
Detailed Description
Abstract class for relation searches and lookups.
Definition at line 116 of file RamOperation.h.
Constructor & Destructor Documentation
souffle::RamTupleOperation::RamTupleOperation (int ident, std::unique_ptr< RamOperation > nested, std::string profileText = "") inline
Definition at line 118 of file RamOperation.h.
             : RamNestedOperation(std::move(nested), std::move(profileText)), identifier(ident) {}
Member Function Documentation
bool souffle::RamTupleOperation::equal (const RamNode & other) const inline override protected virtual
Equality check for two RAM nodes.
Default action is that nothing needs to be checked.
Reimplemented from souffle::RamNestedOperation.
Reimplemented in souffle::RamUnpackRecord, souffle::RamIndexAggregate, souffle::RamAggregate, souffle::RamIndexChoice, souffle::RamChoice, souffle::RamIndexOperation, and souffle::RamRelationOperation.
Definition at line 142 of file RamOperation.h.
References souffle::RamNestedOperation::equal().
Referenced by souffle::RamRelationOperation::equal(), and souffle::RamUnpackRecord::equal().
{
         assert(nullptr != dynamic_cast<const RamTupleOperation*>(&node));
         const auto& other = static_cast<const RamTupleOperation&>(node);
         return RamNestedOperation::equal(other) && getTupleId() == other.getTupleId();
     }
std::vector<const RamNode*> souffle::RamTupleOperation::getChildNodes () const inline override virtual
Obtain list of all embedded child nodes.
Reimplemented from souffle::RamNestedOperation.
Reimplemented in souffle::RamUnpackRecord, souffle::RamIndexAggregate, souffle::RamAggregate, souffle::RamIndexChoice, souffle::RamChoice, souffle::RamIndexOperation, and souffle::RamRelationOperation.
Definition at line 131 of file RamOperation.h.
References souffle::RamNestedOperation::getChildNodes().
Referenced by souffle::RamRelationOperation::getChildNodes(), and souffle::RamUnpackRecord::getChildNodes().
{
         return RamNestedOperation::getChildNodes();
     }
int souffle::RamTupleOperation::getTupleId () const inline
Get identifier.
Definition at line 122 of file RamOperation.h.
References souffle::identifier().
Referenced by souffle::Synthesiser::emitCode(), souffle::RAMI::evalOp(), souffle::HoistConditionsTransformer::hoistConditions(), souffle::TupleIdTransformer::reorderOperations(), souffle::MakeIndexTransformer::rewriteAggregate(), souffle::MakeIndexTransformer::rewriteIndexScan(), souffle::IfConversionTransformer::rewriteIndexScan(), souffle::ChoiceConversionTransformer::rewriteIndexScan(), souffle::MakeIndexTransformer::rewriteScan(), souffle::ChoiceConversionTransformer::rewriteScan(), souffle::LVMGenerator::visitAggregate(), souffle::LVMGenerator::visitChoice(), souffle::LVMGenerator::visitIndexAggregate(), souffle::LVMGenerator::visitIndexChoice(), souffle::LVMGenerator::visitIndexScan(), souffle::LVMGenerator::visitScan(), and souffle::LVMGenerator::visitUnpackRecord().
{
         return identifier;
     }
void souffle::RamTupleOperation::setTupleId (int id) inline
Set identifier.
Definition at line 127 of file RamOperation.h.
References souffle::identifier().
{
         identifier = id;
     }
Field Documentation
int souffle::RamTupleOperation::identifier protected
Identifier for the tuple, corresponding to its position in the loop nest.
Definition at line 140 of file RamOperation.h.
The documentation for this class was generated from the following file:
RamOperation.h