souffle: souffle::RamAbstractLog Class Reference
souffle::RamAbstractLog Class Reference
Abstract class for logging.
#include <RamStatement.h>
Public Member Functions
void apply (const RamNodeMapper &map)
std::vector< const RamNode * > getChildNodes () const
const std::string & getMessage () const
Get logging message.
const RamStatement & getStatement () const
Get logging statement.
RamAbstractLog (std::unique_ptr< RamStatement > stmt, std::string msg)
Protected Member Functions
bool equal (const RamNode &node) const
Protected Attributes
std::string message
logging message
std::unique_ptr< RamStatement > statement
logging statement
Detailed Description
Abstract class for logging.
Comprises a RamStatement and the message (string) to be logged
Definition at line 748 of file RamStatement.h.
Constructor & Destructor Documentation
souffle::RamAbstractLog::RamAbstractLog (std::unique_ptr< RamStatement > stmt, std::string msg) inline
Definition at line 750 of file RamStatement.h.
             : statement(std::move(stmt)), message(std::move(msg)) {
         assert(statement);
     }
Member Function Documentation
void souffle::RamAbstractLog::apply (const RamNodeMapper & map) inline
Definition at line 770 of file RamStatement.h.
Referenced by souffle::RamLogRelationTimer::apply(), souffle::RamLogTimer::apply(), and souffle::RamDebugInfo::apply().
{
         statement = map(std::move(statement));
     }
bool souffle::RamAbstractLog::equal (const RamNode & node) const inline protected
Definition at line 781 of file RamStatement.h.
References getStatement().
Referenced by souffle::RamLogRelationTimer::equal(), souffle::RamLogTimer::equal(), and souffle::RamDebugInfo::equal().
{
         assert(nullptr != dynamic_cast<const RamAbstractLog*>(&node));
         const auto& other = dynamic_cast<const RamAbstractLog*>(&node);
         return getStatement() == other->getStatement() && getMessage() == other->getMessage();
     }
std::vector<const RamNode*> souffle::RamAbstractLog::getChildNodes () const inline
Definition at line 755 of file RamStatement.h.
Referenced by souffle::RamLogRelationTimer::getChildNodes(), souffle::RamLogTimer::getChildNodes(), and souffle::RamDebugInfo::getChildNodes().
{
         return {statement.get()};
     }
const std::string& souffle::RamAbstractLog::getMessage () const inline
Get logging message.
Definition at line 760 of file RamStatement.h.
Referenced by souffle::Synthesiser::emitCode(), souffle::RAMI::evalStmt(), souffle::LVMGenerator::visitDebugInfo(), souffle::LVMGenerator::visitLogRelationTimer(), and souffle::LVMGenerator::visitLogTimer().
{
         return message;
     }
const RamStatement& souffle::RamAbstractLog::getStatement () const inline
Get logging statement.
Definition at line 765 of file RamStatement.h.
Referenced by souffle::Synthesiser::emitCode(), equal(), souffle::RAMI::evalStmt(), souffle::LVMGenerator::visitDebugInfo(), souffle::LVMGenerator::visitLogRelationTimer(), and souffle::LVMGenerator::visitLogTimer().
{
         assert(statement);
         return *statement;
     }
Field Documentation
std::string souffle::RamAbstractLog::message protected
logging message
Definition at line 779 of file RamStatement.h.
std::unique_ptr<RamStatement> souffle::RamAbstractLog::statement protected
logging statement
Definition at line 776 of file RamStatement.h.
The documentation for this class was generated from the following file:
RamStatement.h