souffle: souffle::LVMInterface Class Reference
souffle::LVMInterface Class Reference abstract
Interpreter Interface.
#include <LVMInterface.h>
Public Member Functions
virtual void executeMain ()=0
Interface for executing the main program.
virtual void executeSubroutine (const std::string &name, const std::vector< RamDomain > &arguments, std::vector< RamDomain > &returnValues, std::vector< bool > &returnErrors)=0
Execute the subroutine.
RamTranslationUnit & getTranslationUnit ()
Get translation unit.
LVMInterface (RamTranslationUnit &tUnit)
virtual ~LVMInterface ()=default
Protected Types
using relation_map = std::vector< std::unique_ptr< LVMRelation >>
relation environment type
Protected Member Functions
void * getMethodHandle (const std::string &method)
relation_map & getRelationMap ()
Get relation map.
SymbolTable & getSymbolTable ()
Get symbol table.
const std::vector< void * > & loadDLL ()
Load dll.
Protected Attributes
std::vector< void * > dll
Dynamic library for user-defined functors.
RamIndexAnalysis * isa
IndexAnalysis.
friend LVMProgInterface
RelationEncoder relationEncoder
Relation Encode.
RamTranslationUnit & translationUnit
RAM translation Unit.
Detailed Description
Interpreter Interface.
Definition at line 45 of file LVMInterface.h.
Member Typedef Documentation
using souffle::LVMInterface::relation_map = std::vector<std::unique_ptr<LVMRelation>> protected
relation environment type
Definition at line 130 of file LVMInterface.h.
Constructor & Destructor Documentation
souffle::LVMInterface::LVMInterface (RamTranslationUnit & tUnit) inline
Definition at line 47 of file LVMInterface.h.
References ~LVMInterface().
             : translationUnit(tUnit), isa(tUnit.getAnalysis<RamIndexAnalysis>()),
               relationEncoder(isa, translationUnit) {}
virtual souffle::LVMInterface::~LVMInterface () virtual default
Referenced by LVMInterface().
Member Function Documentation
virtual void souffle::LVMInterface::executeMain () pure virtual
Interface for executing the main program.
Implemented in souffle::LVM.
Referenced by getTranslationUnit().
virtual void souffle::LVMInterface::executeSubroutine (const std::string & name, const std::vector< RamDomain > & arguments, std::vector< RamDomain > & returnValues, std::vector< bool > & returnErrors) pure virtual
Execute the subroutine.
Implemented in souffle::LVM.
Referenced by getTranslationUnit().
void* souffle::LVMInterface::getMethodHandle (const std::string & method) inline protected
Definition at line 111 of file LVMInterface.h.
References loadDLL().
Referenced by souffle::LVM::execute().
{
         // load DLLs (if not done yet)
         for (void* libHandle : loadDLL()) {
             auto* methodHandle = dlsym(libHandle, method.c_str());
             if (methodHandle != nullptr) {
                 return methodHandle;
             }
         }
         return nullptr;
     }
relation_map& souffle::LVMInterface::getRelationMap () inline protected
Get relation map.
Definition at line 133 of file LVMInterface.h.
References souffle::RelationEncoder::getRelationMap(), and relationEncoder.
{
         return relationEncoder.getRelationMap();
     }
SymbolTable& souffle::LVMInterface::getSymbolTable () inline protected
Get symbol table.
Definition at line 125 of file LVMInterface.h.
References souffle::RamTranslationUnit::getSymbolTable(), and translationUnit.
{
         return translationUnit.getSymbolTable();
     }
RamTranslationUnit& souffle::LVMInterface::getTranslationUnit () inline
Get translation unit.
Definition at line 54 of file LVMInterface.h.
References executeMain(), executeSubroutine(), and translationUnit.
{
         return translationUnit;
     }
const std::vector<void*>& souffle::LVMInterface::loadDLL () inline protected
Load dll.
Definition at line 67 of file LVMInterface.h.
References souffle::Global::config(), dll, and souffle::splitString().
Referenced by getMethodHandle().
{
         if (!dll.empty()) {
             return dll;
         }
         if (!Global::config().has("libraries")) {
             Global::config().set("libraries", "functors");
         }
         if (!Global::config().has("library-dir")) {
             Global::config().set("library-dir", ".");
         }
         for (const std::string& library : splitString(Global::config().get("libraries"), ' ')) {
             // The library may be blank
             if (library.empty()) {
                 continue;
             }
             auto paths = splitString(Global::config().get("library-dir"), ' ');
             // Set up our paths to have a library appended
             for (std::string& path : paths) {
                 if (path.back() != '/') {
                     path += '/';
                 }
             }
             if (library.find('/') != std::string::npos) {
                 paths.clear();
             }
             paths.push_back("");
             void* tmp = nullptr;
             for (const std::string& path : paths) {
                 std::string fullpath = path + "lib" + library + ".so";
                 tmp = dlopen(fullpath.c_str(), RTLD_LAZY);
                 if (tmp != nullptr) {
                     dll.push_back(tmp);
                     break;
                 }
             }
         }
         return dll;
     }
Field Documentation
std::vector<void*> souffle::LVMInterface::dll protected
Dynamic library for user-defined functors.
Definition at line 144 of file LVMInterface.h.
Referenced by loadDLL().
RamIndexAnalysis* souffle::LVMInterface::isa protected
IndexAnalysis.
Definition at line 141 of file LVMInterface.h.
friend souffle::LVMInterface::LVMProgInterface protected
Definition at line 122 of file LVMInterface.h.
RelationEncoder souffle::LVMInterface::relationEncoder protected
Relation Encode.
Definition at line 147 of file LVMInterface.h.
Referenced by souffle::LVM::dropRelation(), souffle::LVM::execute(), souffle::LVM::executeMain(), souffle::LVM::executeSubroutine(), souffle::LVM::getRelation(), getRelationMap(), souffle::LVM::printMain(), and souffle::LVM::swapRelation().
RamTranslationUnit& souffle::LVMInterface::translationUnit protected
RAM translation Unit.
Definition at line 138 of file LVMInterface.h.
Referenced by souffle::LVM::executeMain(), souffle::LVM::executeSubroutine(), souffle::LVM::getSymbolTable(), getSymbolTable(), getTranslationUnit(), and souffle::LVM::printMain().
The documentation for this class was generated from the following file:
LVMInterface.h