souffle: souffle::LVMIndirectRelation Class Reference
souffle::LVMIndirectRelation Class Reference
Interpreter Indirect Relation.
#include <LVMRelation.h>
Public Member Functions
bool insert (const TupleRef &tuple) override
Insert tuple.
bool insert (const RamDomain *tuple) override
Add the given tuple to this relation.
LVMIndirectRelation (size_t arity, const std::string &relName, const std::vector< std::string > &attributeTypes, const MinIndexSelection &orderSet)
void purge () override
Clear all indexes.
Public Member Functions inherited from souffle::LVMRelation
Iterator begin () const
bool contains (const TupleRef &tuple) const
Tests whether this relation contains the given tuple.
bool empty () const
Check if the relation is empty.
Iterator end () const
bool exists (const TupleRef &tuple) const
Check if a tuple exists in realtion.
virtual void extend (const LVMRelation &rel)
Extend another relation.
size_t getArity () const
Return arity.
const std::vector< std::string > & getAttributeTypeQualifiers () const
Return the attribute types.
size_t getLevel () const
Return the level of the relation.
const std::string & getName () const
Return the relation name.
void insert (const LVMRelation &other)
Add all entries of the given relation to this relation.
LVMRelation (std::size_t arity, const std::string &name, const std::vector< std::string > &attributeTypes, const MinIndexSelection &orderSet, IndexFactory factory=&createBTreeIndex)
Creates a relation, build all necessary indexes.
LVMRelation (LVMRelation &other)=delete
Stream range (const size_t &indexPos, const TupleRef &low, const TupleRef &high) const
Obtains a stream covering the interval between the two given entries.
void removeIndex (const size_t &indexPos)
Drops an index from the maintained indexes.
Stream scan () const
Obtains a stream to scan the entire relation.
void setLevel (size_t level)
Set level.
size_t size () const
Return number of tuples in relation (full-order)
void swap (LVMRelation &other)
Swaps the content of this and the given relation, including the installed indexes.
virtual ~LVMRelation ()=default
Private Attributes
std::deque< std::unique_ptr< RamDomain[]> > blockList
size_t num_tuples = 0
Static Private Attributes
static const int BLOCK_SIZE = 1024
Size of blocks containing tuples.
Additional Inherited Members
Protected Attributes inherited from souffle::LVMRelation
size_t arity
std::vector< std::string > attributeTypes
std::vector< std::unique_ptr< LVMIndex > > indexes
size_t level = 0
LVMIndex * main
std::string relName
Detailed Description
Interpreter Indirect Relation.
Definition at line 216 of file LVMRelation.h.
Constructor & Destructor Documentation
souffle::LVMIndirectRelation::LVMIndirectRelation (size_t arity, const std::string & relName, const std::vector< std::string > & attributeTypes, const MinIndexSelection & orderSet)
Definition at line 188 of file LVMRelation.cpp.
         : LVMRelation(arity, name, attributeTypes, orderSet, createIndirectIndex) {}
Member Function Documentation
bool souffle::LVMIndirectRelation::insert (const TupleRef & tuple) override virtual
Insert tuple.
Reimplemented from souffle::LVMRelation.
Definition at line 192 of file LVMRelation.cpp.
References souffle::LVMRelation::arity, BLOCK_SIZE, blockList, souffle::LVMIndex::contains(), i, souffle::LVMRelation::indexes, souffle::LVMRelation::main, and num_tuples.
Referenced by insert().
{
     if (main->contains(tuple)) {
         return false;
     }
     int blockIndex = num_tuples / (BLOCK_SIZE / arity);
     int tupleIndex = (num_tuples % (BLOCK_SIZE / arity)) * arity;
     if (tupleIndex == 0) {
         blockList.push_back(std::make_unique<RamDomain[]>(BLOCK_SIZE));
     }
     RamDomain* newTuple = &blockList[blockIndex][tupleIndex];
     for (size_t i = 0; i < arity; ++i) {
         newTuple[i] = tuple[i];
     }
     // update all indexes with new tuple
     for (auto& cur : indexes) {
         cur->insert(TupleRef(newTuple, arity));
     }
     // increment relation size
     num_tuples++;
     return true;
 }
bool souffle::LVMIndirectRelation::insert (const RamDomain * tuple) override virtual
Add the given tuple to this relation.
Reimplemented from souffle::LVMRelation.
Definition at line 220 of file LVMRelation.cpp.
References souffle::LVMRelation::arity, and insert().
{
     return this->insert(TupleRef(tuple, arity));
 }
void souffle::LVMIndirectRelation::purge () override virtual
Clear all indexes.
Reimplemented from souffle::LVMRelation.
Definition at line 224 of file LVMRelation.cpp.
References blockList, souffle::LVMRelation::indexes, and num_tuples.
{
     blockList.clear();
     for (auto& cur : indexes) {
         cur->clear();
     }
     num_tuples = 0;
 }
Field Documentation
const int souffle::LVMIndirectRelation::BLOCK_SIZE = 1024 static private
Size of blocks containing tuples.
Definition at line 230 of file LVMRelation.h.
Referenced by insert().
std::deque<std::unique_ptr<RamDomain[]> > souffle::LVMIndirectRelation::blockList private
Definition at line 232 of file LVMRelation.h.
Referenced by insert(), and purge().
size_t souffle::LVMIndirectRelation::num_tuples = 0 private
Definition at line 234 of file LVMRelation.h.
Referenced by insert(), and purge().
The documentation for this class was generated from the following files:
LVMRelation.h
LVMRelation.cpp