souffle: souffle::RamIndexAnalysis Class Reference
souffle::RamIndexAnalysis Class Reference
#include <RamIndexAnalysis.h>
Public Member Functions
MinIndexSelection & getIndexes (const RamRelation &rel)
get the minimal index cover for a relation
MinIndexSelection & getIndexes (const std::string &relName)
get the minimal index cover for a relation
SearchSignature getSearchSignature (const RamIndexOperation *search) const
Get index signature for an Ram IndexOperation operation
SearchSignature getSearchSignature (const RamExistenceCheck *existCheck) const
Get the index signature for an existence check
SearchSignature getSearchSignature (const RamProvenanceExistenceCheck *existCheck) const
Get the index signature for a provenance existence check
SearchSignature getSearchSignature (const RamRelation *ramRel) const
Get the default index signature for a relation (the total-order index)
bool isTotalSignature (const RamAbstractExistenceCheck *existCheck) const
index signature of existence check resembles a total index
void print (std::ostream &os) const override
Print the analysis result in HTML format.
void run (const RamTranslationUnit &translationUnit) override
Run analysis for a RAM translation unit.
Public Member Functions inherited from souffle::RamAnalysis
virtual ~RamAnalysis ()=default
Static Public Attributes
static constexpr const char * name = "index-analysis"
Private Attributes
std::map< const RamRelation *, MinIndexSelection > minIndexCover
minimal index cover for relations, i.e., maps a relation to a set of indexes
Detailed Description
Definition at line 319 of file RamIndexAnalysis.h.
Member Function Documentation
MinIndexSelection & souffle::RamIndexAnalysis::getIndexes (const RamRelation & rel)
get the minimal index cover for a relation
Parameters
relation
Returns
set of indexes of the minimal index cover
Definition at line 332 of file RamIndexAnalysis.cpp.
Referenced by souffle::RelationEncoder::createRelation(), souffle::RAMI::evalStmt(), and souffle::LVMGenerator::getIndexPos().
{
     auto pos = minIndexCover.find(&rel);
     if (pos != minIndexCover.end()) {
         return pos->second;
     } else {
         auto ret = minIndexCover.insert(std::make_pair(&rel, MinIndexSelection()));
         assert(ret.second);
         return ret.first->second;
     }
 }
MinIndexSelection& souffle::RamIndexAnalysis::getIndexes (const std::string & relName)
get the minimal index cover for a relation
Parameters
relation name
Returns
set of indexes of the minimal index cover
SearchSignature souffle::RamIndexAnalysis::getSearchSignature (const RamIndexOperation * search) const
Get index signature for an Ram IndexOperation operation
Parameters
Index-relation-search operation
Returns
Index signature of operation
Definition at line 377 of file RamIndexAnalysis.cpp.
References souffle::RamIndexOperation::getRangePattern(), i, and souffle::isRamUndefValue().
Referenced by souffle::Synthesiser::emitCode(), souffle::RAMI::evalCond(), souffle::RAMI::evalOp(), and souffle::LVMGenerator::getIndexPos().
{
     SearchSignature keys = 0;
     std::vector<RamExpression*> rangePattern = search->getRangePattern();
     for (int i = 0; i < (int)rangePattern.size(); i++) {
         if (!isRamUndefValue(rangePattern[i])) {
             keys |= (1 << i);
         }
     }
     return keys;
 }
SearchSignature souffle::RamIndexAnalysis::getSearchSignature (const RamExistenceCheck * existCheck) const
Get the index signature for an existence check
Parameters
Existence check
Returns
index signature of existence check
Definition at line 401 of file RamIndexAnalysis.cpp.
References souffle::RamAbstractExistenceCheck::getValues(), i, and souffle::isRamUndefValue().
{
     const auto values = existCheck->getValues();
     SearchSignature res = 0;
     for (int i = 0; i < (int)values.size(); i++) {
         if (!isRamUndefValue(values[i])) {
             res |= (1 << i);
         }
     }
     return res;
 }
SearchSignature souffle::RamIndexAnalysis::getSearchSignature (const RamProvenanceExistenceCheck * existCheck) const
Get the index signature for a provenance existence check
Parameters
Provenance-existence check
Returns
index signature of provenance-existence check
Definition at line 388 of file RamIndexAnalysis.cpp.
References souffle::RamAbstractExistenceCheck::getValues(), i, and souffle::isRamUndefValue().
{
     const auto values = provExistCheck->getValues();
     SearchSignature res = 0;
     // values.size() - 1 because we discard the height annotation
     for (int i = 0; i < (int)values.size() - 1; i++) {
         if (!isRamUndefValue(values[i])) {
             res |= (1 << i);
         }
     }
     return res;
 }
SearchSignature souffle::RamIndexAnalysis::getSearchSignature (const RamRelation * ramRel) const
Get the default index signature for a relation (the total-order index)
Parameters
RamCreate node
Returns
total full-signature of the relation
Definition at line 412 of file RamIndexAnalysis.cpp.
References souffle::RamRelation::getArity().
{
     SearchSignature res = (1 << ramRel->getArity()) - 1;
     return res;
 }
bool souffle::RamIndexAnalysis::isTotalSignature (const RamAbstractExistenceCheck * existCheck) const
index signature of existence check resembles a total index
Parameters
(provenance) existence check
isTotalSignature returns true if all elements of a tuple are used for the the existence check.
Definition at line 417 of file RamIndexAnalysis.cpp.
References souffle::RamAbstractExistenceCheck::getValues(), and souffle::isRamUndefValue().
Referenced by souffle::Synthesiser::emitCode(), and souffle::RAMI::evalCond().
{
     for (const auto& cur : existCheck->getValues()) {
         if (isRamUndefValue(cur)) {
             return false;
         }
     }
     return true;
 }
void souffle::RamIndexAnalysis::print (std::ostream & os) const override virtual
Print the analysis result in HTML format.
Reimplemented from souffle::RamAnalysis.
Definition at line 343 of file RamIndexAnalysis.cpp.
References souffle::MinIndexSelection::getAllOrders(), souffle::RamRelation::getArg(), souffle::RamRelation::getArity(), souffle::RamRelation::getName(), souffle::MinIndexSelection::getSearches(), and i.
{
     os << "------ Auto-Index-Generation Report -------\n";
     for (auto& cur : minIndexCover) {
         const RamRelation& rel = *cur.first;
         const MinIndexSelection& indexes = cur.second;
         const std::string& relName = rel.getName();
         /* Print searches */
         os << "Relation " << relName << "\n";
         os << "\tNumber of Search Patterns: " << indexes.getSearches().size() << "\n";
         /* print searches */
         for (auto& cols : indexes.getSearches()) {
             os << "\t\t";
             for (uint32_t i = 0; i < rel.getArity(); i++) {
                 if ((1UL << i) & cols) {
                     os << rel.getArg(i) << " ";
                 }
             }
             os << "\n";
         }
         os << "\tNumber of Indexes: " << indexes.getAllOrders().size() << "\n";
         for (auto& order : indexes.getAllOrders()) {
             os << "\t\t";
             for (auto& i : order) {
                 os << rel.getArg(i) << " ";
             }
             os << "\n";
         }
     }
     os << "------ End of Auto-Index-Generation Report -------\n";
 }
void souffle::RamIndexAnalysis::run (const RamTranslationUnit & translationUnit) override virtual
Run analysis for a RAM translation unit.
Implements souffle::RamAnalysis.
Definition at line 265 of file RamIndexAnalysis.cpp.
References souffle::MinIndexSelection::addSearch(), souffle::MinIndexSelection::getAllOrders(), souffle::RamTranslationUnit::getProgram(), souffle::MinIndexSelection::getSearches(), souffle::MinIndexSelection::insertDefaultTotalIndex(), souffle::MinIndexSelection::solve(), and souffle::visitDepthFirst().
{
     // After complete:
     // 1. All relations should have at least one index (for full-order search).
     // 2. Two relations involved in a swap operation will have same set of indices.
     // 3. A 0-arity relation will have only one index where LexOrder is defined as empty. A comparator using
     // an empty order should regard all elements as equal and therefore only allow one arbitrary tuple to be
     // inserted.
     //
     // TODO:
     // 0-arity relation in a provenance program still need to be revisited.
     // visit all nodes to collect searches of each relation
     visitDepthFirst(*translationUnit.getProgram(), [&](const RamNode& node) {
         if (const auto* indexSearch = dynamic_cast<const RamIndexOperation*>(&node)) {
             MinIndexSelection& indexes = getIndexes(indexSearch->getRelation());
             indexes.addSearch(getSearchSignature(indexSearch));
         } else if (const auto* exists = dynamic_cast<const RamExistenceCheck*>(&node)) {
             MinIndexSelection& indexes = getIndexes(exists->getRelation());
             indexes.addSearch(getSearchSignature(exists));
         } else if (const auto* provExists = dynamic_cast<const RamProvenanceExistenceCheck*>(&node)) {
             MinIndexSelection& indexes = getIndexes(provExists->getRelation());
             indexes.addSearch(getSearchSignature(provExists));
         } else if (const auto* ramRel = dynamic_cast<const RamRelation*>(&node)) {
             MinIndexSelection& indexes = getIndexes(*ramRel);
             indexes.addSearch(getSearchSignature(ramRel));
         }
     });
     // A swap happen between rel A and rel B indicates A should include all indices of B, vice versa.
     visitDepthFirst(*translationUnit.getProgram(), [&](const RamSwap& swap) {
         // Note: this naive approach will not work if there exists chain or cyclic swapping.
         // e.g.  swap(relA, relB) swap(relB, relC) swap(relC, relA)
         // One need to keep merging the search set until a fixed point where no more index is introduced
         // in any of the relation in a complete iteration.
         //
         // Currently RAM does not have such situation.
         const RamRelation& relA = swap.getFirstRelation();
         const RamRelation& relB = swap.getSecondRelation();
         MinIndexSelection& indexesA = getIndexes(relA);
         MinIndexSelection& indexesB = getIndexes(relB);
         // Add all searchSignature of A into B
         for (const auto& signature : indexesA.getSearches()) {
             indexesB.addSearch(signature);
         }
         // Add all searchSignature of B into A
         for (const auto& signature : indexesB.getSearches()) {
             indexesA.addSearch(signature);
         }
     });
     // find optimal indexes for relations
     for (auto& cur : minIndexCover) {
         MinIndexSelection& indexes = cur.second;
         indexes.solve();
     }
     // Only case where indexSet is still empty is when relation has arity == 0
     for (auto& cur : minIndexCover) {
         MinIndexSelection& indexes = cur.second;
         if (indexes.getAllOrders().empty()) {
             indexes.insertDefaultTotalIndex(0);
         }
     }
 }
Field Documentation
std::map<const RamRelation*, MinIndexSelection> souffle::RamIndexAnalysis::minIndexCover private
minimal index cover for relations, i.e., maps a relation to a set of indexes
Definition at line 382 of file RamIndexAnalysis.h.
constexpr const char* souffle::RamIndexAnalysis::name = "index-analysis" static
Definition at line 321 of file RamIndexAnalysis.h.
The documentation for this class was generated from the following files:
RamIndexAnalysis.h
RamIndexAnalysis.cpp