souffle: souffle::LVMRelInterface Class Reference
souffle::LVMRelInterface Class Reference
Wrapper class for interpreter relations.
#include <LVMProgInterface.h>
Data Structures
class iterator_base
Iterator wrapper class.
Public Member Functions
iterator begin () const override
Iterator to first tuple.
bool contains (const tuple &t) const override
Check whether tuple exists.
iterator end () const override
Iterator to last tuple.
size_t getArity () const override
Get arity.
const char * getAttrName (size_t idx) const override
Get attribute name.
const char * getAttrType (size_t idx) const override
Get attribute type.
std::string getName () const override
Get name.
SymbolTable & getSymbolTable () const override
Get symbol table.
void insert (const tuple &t) override
Insert tuple.
LVMRelInterface (LVMRelation &r, SymbolTable &s, std::string n, std::vector< std::string > t, std::vector< std::string > an, uint32_t i)
void purge () override
Eliminate all the tuples in relation.
std::size_t size () const override
Get number of tuples in relation.
~LVMRelInterface () override=default
Public Member Functions inherited from souffle::Relation
std::string getSignature ()
virtual ~Relation ()=default
Private Attributes
std::vector< std::string > attrNames
Attribute Names.
uint32_t id
Unique id for wrapper.
std::string name
Name of relation.
LVMRelation & relation
Wrapped interpreter relation.
SymbolTable & symTable
Symbol table.
std::vector< std::string > types
Attribute type.
Detailed Description
Wrapper class for interpreter relations.
Definition at line 31 of file LVMProgInterface.h.
Constructor & Destructor Documentation
souffle::LVMRelInterface::LVMRelInterface (LVMRelation & r, SymbolTable & s, std::string n, std::vector< std::string > t, std::vector< std::string > an, uint32_t i) inline
Definition at line 33 of file LVMProgInterface.h.
References ~LVMRelInterface().
             : relation(r), symTable(s), name(std::move(n)), types(std::move(t)), attrNames(std::move(an)),
               id(i) {}
souffle::LVMRelInterface::~LVMRelInterface () override default
Referenced by LVMRelInterface().
Member Function Documentation
iterator souffle::LVMRelInterface::begin () const inline override virtual
Iterator to first tuple.
Implements souffle::Relation.
Definition at line 50 of file LVMProgInterface.h.
References souffle::LVMRelation::begin(), and relation.
{
         return LVMRelInterface::iterator(new LVMRelInterface::iterator_base(id, this, relation.begin()));
     }
bool souffle::LVMRelInterface::contains (const tuple & t) const inline override virtual
Check whether tuple exists.
Implements souffle::Relation.
Definition at line 45 of file LVMProgInterface.h.
References souffle::tuple::data, souffle::LVMRelation::exists(), souffle::LVMRelation::getArity(), and relation.
{
         return relation.exists(TupleRef(t.data, relation.getArity()));
     }
iterator souffle::LVMRelInterface::end () const inline override virtual
Iterator to last tuple.
Implements souffle::Relation.
Definition at line 55 of file LVMProgInterface.h.
References souffle::LVMRelation::end(), and relation.
{
         return LVMRelInterface::iterator(new LVMRelInterface::iterator_base(id, this, relation.end()));
     }
size_t souffle::LVMRelInterface::getArity () const inline override virtual
Get arity.
Implements souffle::Relation.
Definition at line 65 of file LVMProgInterface.h.
References souffle::LVMRelation::getArity(), and relation.
Referenced by getAttrName(), getAttrType(), and souffle::LVMRelInterface::iterator_base::operator*().
{
         return relation.getArity();
     }
const char* souffle::LVMRelInterface::getAttrName (size_t idx) const inline override virtual
Get attribute name.
Implements souffle::Relation.
Definition at line 81 of file LVMProgInterface.h.
References attrNames, and getArity().
{
         assert(idx < getArity() && "exceeded tuple size");
         return attrNames[idx].c_str();
     }
const char* souffle::LVMRelInterface::getAttrType (size_t idx) const inline override virtual
Get attribute type.
Implements souffle::Relation.
Definition at line 75 of file LVMProgInterface.h.
References getArity(), and types.
Referenced by souffle::LVMRelInterface::iterator_base::operator*().
{
         assert(idx < getArity() && "exceeded tuple size");
         return types[idx].c_str();
     }
std::string souffle::LVMRelInterface::getName () const inline override virtual
Get name.
Implements souffle::Relation.
Definition at line 60 of file LVMProgInterface.h.
References name.
{
         return name;
     }
SymbolTable& souffle::LVMRelInterface::getSymbolTable () const inline override virtual
Get symbol table.
Implements souffle::Relation.
Definition at line 70 of file LVMProgInterface.h.
References symTable.
Referenced by souffle::LVMRelInterface::iterator_base::operator*().
{
         return symTable;
     }
void souffle::LVMRelInterface::insert (const tuple & t) inline override virtual
Insert tuple.
Implements souffle::Relation.
Definition at line 40 of file LVMProgInterface.h.
References souffle::tuple::data, souffle::LVMRelation::getArity(), souffle::LVMRelation::insert(), and relation.
{
         relation.insert(TupleRef(t.data, relation.getArity()));
     }
void souffle::LVMRelInterface::purge () inline override virtual
Eliminate all the tuples in relation.
Implements souffle::Relation.
Definition at line 92 of file LVMProgInterface.h.
References souffle::LVMRelation::purge(), and relation.
{
         relation.purge();
     }
std::size_t souffle::LVMRelInterface::size () const inline override virtual
Get number of tuples in relation.
Implements souffle::Relation.
Definition at line 87 of file LVMProgInterface.h.
References relation, and souffle::LVMRelation::size().
{
         return relation.size();
     }
Field Documentation
std::vector<std::string> souffle::LVMRelInterface::attrNames private
Attribute Names.
Definition at line 165 of file LVMProgInterface.h.
Referenced by getAttrName(), and souffle::LVMProgInterface::LVMProgInterface().
uint32_t souffle::LVMRelInterface::id private
Unique id for wrapper.
Definition at line 168 of file LVMProgInterface.h.
std::string souffle::LVMRelInterface::name private
Name of relation.
Definition at line 159 of file LVMProgInterface.h.
Referenced by getName(), and souffle::LVMProgInterface::LVMProgInterface().
LVMRelation& souffle::LVMRelInterface::relation private
Wrapped interpreter relation.
Definition at line 153 of file LVMProgInterface.h.
Referenced by begin(), contains(), end(), getArity(), insert(), purge(), and size().
SymbolTable& souffle::LVMRelInterface::symTable private
Symbol table.
Definition at line 156 of file LVMProgInterface.h.
Referenced by getSymbolTable(), and souffle::LVMProgInterface::getSymbolTable().
std::vector<std::string> souffle::LVMRelInterface::types private
Attribute type.
Definition at line 162 of file LVMProgInterface.h.
Referenced by getAttrType(), and souffle::LVMProgInterface::LVMProgInterface().
The documentation for this class was generated from the following file:
LVMProgInterface.h