souffle: souffle::LVMContext Class Reference
souffle::LVMContext Class Reference
Evaluation context for Interpreter operations.
#include <LVMContext.h>
Public Member Functions
void addReturnValue (RamDomain val, bool err=false)
RamDomain * allocateNewTuple (size_t size)
Allocate a tuple.
RamDomain getArgument (size_t i) const
const std::vector< RamDomain > & getArguments () const
std::vector< bool > & getReturnErrors () const
std::vector< RamDomain > & getReturnValues () const
LVMContext (size_t size=0)
TupleRef & operator[] (size_t index)
void setArguments (const std::vector< RamDomain > &a)
void setReturnErrors (std::vector< bool > &retErrs)
void setReturnValues (std::vector< RamDomain > &retVals)
virtual ~LVMContext ()=default
Private Attributes
std::vector< std::unique_ptr< RamDomain[]> > allocatedDataContainer
const std::vector< RamDomain > * args = nullptr
std::vector< TupleRef > data
std::vector< bool > * returnErrors = nullptr
std::vector< RamDomain > * returnValues = nullptr
Detailed Description
Evaluation context for Interpreter operations.
Definition at line 30 of file LVMContext.h.
Constructor & Destructor Documentation
souffle::LVMContext::LVMContext (size_t size = 0) inline
Definition at line 39 of file LVMContext.h.
References ~LVMContext().
 : data(size) {}
virtual souffle::LVMContext::~LVMContext () virtual default
Referenced by LVMContext().
Member Function Documentation
void souffle::LVMContext::addReturnValue (RamDomain val, bool err = false) inline
Definition at line 67 of file LVMContext.h.
References err.
Referenced by souffle::LVM::execute().
{
         assert(returnValues != nullptr && returnErrors != nullptr);
         returnValues->push_back(val);
         returnErrors->push_back(err);
     }
RamDomain* souffle::LVMContext::allocateNewTuple (size_t size) inline
Allocate a tuple.
LVMContext has ownership of allocated tuples.
Definition at line 51 of file LVMContext.h.
Referenced by souffle::LVM::execute().
{
         std::unique_ptr<RamDomain[]> newTuple(new RamDomain[size]);
         allocatedDataContainer.push_back(std::move(newTuple));
         // Return the reference as raw pointer.
         return allocatedDataContainer.back().get();
     }
RamDomain souffle::LVMContext::getArgument (size_t i) const inline
Definition at line 89 of file LVMContext.h.
References i.
Referenced by souffle::LVM::execute().
{
         assert(args != nullptr && i < args->size() && "argument out of range");
         return (*args)[i];
     }
const std::vector<RamDomain>& souffle::LVMContext::getArguments () const inline
Definition at line 81 of file LVMContext.h.
References args.
{
         return *args;
     }
std::vector<bool>& souffle::LVMContext::getReturnErrors () const inline
Definition at line 73 of file LVMContext.h.
References returnErrors.
{
         return *returnErrors;
     }
std::vector<RamDomain>& souffle::LVMContext::getReturnValues () const inline
Definition at line 59 of file LVMContext.h.
References returnValues.
{
         return *returnValues;
     }
TupleRef& souffle::LVMContext::operator[] (size_t index) inline
Definition at line 42 of file LVMContext.h.
{
         if (index >= data.size()) {
             data.resize((index + 1));
         }
         return data[index];
     }
void souffle::LVMContext::setArguments (const std::vector< RamDomain > & a) inline
Definition at line 85 of file LVMContext.h.
Referenced by souffle::LVM::executeSubroutine().
{
         args = &a;
     }
void souffle::LVMContext::setReturnErrors (std::vector< bool > & retErrs) inline
Definition at line 77 of file LVMContext.h.
Referenced by souffle::LVM::executeSubroutine().
{
         returnErrors = &retErrs;
     }
void souffle::LVMContext::setReturnValues (std::vector< RamDomain > & retVals) inline
Definition at line 63 of file LVMContext.h.
Referenced by souffle::LVM::executeSubroutine().
{
         returnValues = &retVals;
     }
Field Documentation
std::vector<std::unique_ptr<RamDomain[]> > souffle::LVMContext::allocatedDataContainer private
Definition at line 36 of file LVMContext.h.
const std::vector<RamDomain>* souffle::LVMContext::args = nullptr private
Definition at line 35 of file LVMContext.h.
Referenced by getArguments().
std::vector<TupleRef> souffle::LVMContext::data private
Definition at line 32 of file LVMContext.h.
std::vector<bool>* souffle::LVMContext::returnErrors = nullptr private
Definition at line 34 of file LVMContext.h.
Referenced by getReturnErrors().
std::vector<RamDomain>* souffle::LVMContext::returnValues = nullptr private
Definition at line 33 of file LVMContext.h.
Referenced by getReturnValues().
The documentation for this class was generated from the following file:
LVMContext.h