souffle: souffle::RamRelationOperation Class Reference
souffle::RamRelationOperation Class Reference
Abstract class for operations on relations.
#include <RamOperation.h>
Public Member Functions
void apply (const RamNodeMapper &map) override
Apply the mapper to all child nodes.
std::vector< const RamNode * > getChildNodes () const override
Obtain list of all embedded child nodes.
const RamRelation & getRelation () const
Get search relation.
RamRelationOperation (std::unique_ptr< RamRelationReference > relRef, int ident, std::unique_ptr< RamOperation > nested, std::string profileText="")
Public Member Functions inherited from souffle::RamTupleOperation
int getTupleId () const
Get identifier.
RamTupleOperation (int ident, std::unique_ptr< RamOperation > nested, std::string profileText="")
void setTupleId (int id)
Set identifier.
Public Member Functions inherited from souffle::RamNestedOperation
RamOperation & getOperation () const
Get nested operation.
const std::string & getProfileText () const
Get profile text.
void print (std::ostream &os, int tabpos) const override
Pretty print with indentation.
RamNestedOperation (std::unique_ptr< RamOperation > nested, std::string profileText="")
Public Member Functions inherited from souffle::RamOperation
RamOperation * clone () const override=0
Create a clone (i.e.
void print (std::ostream &os) const override
Print RAM node.
Public Member Functions inherited from souffle::RamNode
bool operator!= (const RamNode &other) const
Inequality check for two RAM nodes.
bool operator== (const RamNode &other) const
Equivalence check for two RAM nodes.
RamNode ()=default
virtual ~RamNode ()=default
Protected Member Functions
bool equal (const RamNode &node) const override
Equality check for two RAM nodes.
Protected Attributes
std::unique_ptr< RamRelationReference > relationRef
Search relation.
Protected Attributes inherited from souffle::RamTupleOperation
int identifier
Identifier for the tuple, corresponding to its position in the loop nest.
Protected Attributes inherited from souffle::RamNestedOperation
std::unique_ptr< RamOperation > nestedOperation
Nested operation.
const std::string profileText
Text used by the profiler.
Detailed Description
Abstract class for operations on relations.
One such operation is a for loop
Definition at line 155 of file RamOperation.h.
Constructor & Destructor Documentation
souffle::RamRelationOperation::RamRelationOperation (std::unique_ptr< RamRelationReference > relRef, int ident, std::unique_ptr< RamOperation > nested, std::string profileText = "") inline
Definition at line 157 of file RamOperation.h.
             : RamTupleOperation(ident, std::move(nested), std::move(profileText)),
               relationRef(std::move(relRef)) {}
Member Function Documentation
void souffle::RamRelationOperation::apply (const RamNodeMapper & mapper) inline override virtual
Apply the mapper to all child nodes.
Reimplemented from souffle::RamNestedOperation.
Reimplemented in souffle::RamIndexAggregate, souffle::RamAggregate, souffle::RamIndexChoice, souffle::RamChoice, and souffle::RamIndexOperation.
Definition at line 167 of file RamOperation.h.
References souffle::RamNestedOperation::apply().
Referenced by souffle::RamIndexOperation::apply(), souffle::RamChoice::apply(), souffle::RamIndexChoice::apply(), and souffle::RamAggregate::apply().
{
         RamTupleOperation::apply(map);
         relationRef = map(std::move(relationRef));
     }
bool souffle::RamRelationOperation::equal (const RamNode & other) const inline override protected virtual
Equality check for two RAM nodes.
Default action is that nothing needs to be checked.
Reimplemented from souffle::RamTupleOperation.
Reimplemented in souffle::RamIndexAggregate, souffle::RamAggregate, souffle::RamIndexChoice, souffle::RamChoice, and souffle::RamIndexOperation.
Definition at line 182 of file RamOperation.h.
References souffle::RamTupleOperation::equal().
Referenced by souffle::RamIndexOperation::equal(), souffle::RamChoice::equal(), souffle::RamIndexChoice::equal(), and souffle::RamAggregate::equal().
{
         assert(nullptr != dynamic_cast<const RamRelationOperation*>(&node));
         const auto& other = static_cast<const RamRelationOperation&>(node);
         return RamTupleOperation::equal(other) && getRelation() == other.getRelation();
     }
std::vector<const RamNode*> souffle::RamRelationOperation::getChildNodes () const inline override virtual
Obtain list of all embedded child nodes.
Reimplemented from souffle::RamTupleOperation.
Reimplemented in souffle::RamIndexAggregate, souffle::RamAggregate, souffle::RamIndexChoice, souffle::RamChoice, and souffle::RamIndexOperation.
Definition at line 172 of file RamOperation.h.
References souffle::RamTupleOperation::getChildNodes().
Referenced by souffle::RamIndexOperation::getChildNodes(), and souffle::RamAggregate::getChildNodes().
{
         auto res = RamTupleOperation::getChildNodes();
         res.push_back(relationRef.get());
         return res;
     }
const RamRelation& souffle::RamRelationOperation::getRelation () const inline
Get search relation.
Definition at line 163 of file RamOperation.h.
Referenced by souffle::Synthesiser::emitCode(), souffle::RAMI::evalOp(), souffle::MakeIndexTransformer::rewriteAggregate(), souffle::MakeIndexTransformer::rewriteIndexScan(), souffle::IfConversionTransformer::rewriteIndexScan(), souffle::ChoiceConversionTransformer::rewriteIndexScan(), souffle::MakeIndexTransformer::rewriteScan(), souffle::ChoiceConversionTransformer::rewriteScan(), souffle::LVMGenerator::visitAggregate(), souffle::LVMGenerator::visitChoice(), souffle::LVMGenerator::visitIndexAggregate(), souffle::LVMGenerator::visitIndexChoice(), souffle::LVMGenerator::visitIndexScan(), and souffle::LVMGenerator::visitScan().
{
         return *relationRef->get();
     }
Field Documentation
std::unique_ptr<RamRelationReference> souffle::RamRelationOperation::relationRef protected
Search relation.
Definition at line 180 of file RamOperation.h.
The documentation for this class was generated from the following file:
RamOperation.h