souffle: souffle::RAMIInterface Class Reference
souffle::RAMIInterface Class Reference abstract
Interpreter Interface.
#include <RAMIInterface.h>
Public Member Functions
virtual void executeMain ()=0
Interface for executing the main program.
virtual void executeSubroutine (const std::string &name, const std::vector< RamDomain > &arguments, std::vector< RamDomain > &returnValues, std::vector< bool > &returnErrors)=0
Execute the subroutine.
RamTranslationUnit & getTranslationUnit ()
Get translation unit.
RAMIInterface (RamTranslationUnit &tUnit)
virtual ~RAMIInterface ()=default
Protected Member Functions
void * getMethodHandle (const std::string &method)
virtual std::map< std::string, RAMIRelation * > & getRelationMap ()=0
Get relation map.
SymbolTable & getSymbolTable ()
Get symbol table.
const std::vector< void * > & loadDLL ()
Load dll.
Protected Attributes
std::vector< void * > dll
Dynamic library for user-defined functors.
RamIndexAnalysis * isa
IndexAnalysis.
friend RAMIProgInterface
RamTranslationUnit & translationUnit
RAM translation Unit.
Detailed Description
Interpreter Interface.
Definition at line 44 of file RAMIInterface.h.
Constructor & Destructor Documentation
souffle::RAMIInterface::RAMIInterface (RamTranslationUnit & tUnit) inline
Definition at line 46 of file RAMIInterface.h.
References ~RAMIInterface().
             : translationUnit(tUnit), isa(tUnit.getAnalysis<RamIndexAnalysis>()) {}
virtual souffle::RAMIInterface::~RAMIInterface () virtual default
Referenced by RAMIInterface().
Member Function Documentation
virtual void souffle::RAMIInterface::executeMain () pure virtual
Interface for executing the main program.
Implemented in souffle::RAMI.
Referenced by getTranslationUnit().
virtual void souffle::RAMIInterface::executeSubroutine (const std::string & name, const std::vector< RamDomain > & arguments, std::vector< RamDomain > & returnValues, std::vector< bool > & returnErrors) pure virtual
Execute the subroutine.
Implemented in souffle::RAMI.
Referenced by getTranslationUnit().
void* souffle::RAMIInterface::getMethodHandle (const std::string & method) inline protected
Definition at line 109 of file RAMIInterface.h.
References loadDLL().
Referenced by souffle::RAMI::evalExpr().
{
         // load DLLs (if not done yet)
         for (void* libHandle : loadDLL()) {
             auto* methodHandle = dlsym(libHandle, method.c_str());
             if (methodHandle != nullptr) {
                 return methodHandle;
             }
         }
         return nullptr;
     }
virtual std::map<std::string, RAMIRelation*>& souffle::RAMIInterface::getRelationMap () protected pure virtual
Get relation map.
Implemented in souffle::RAMI.
Referenced by getSymbolTable().
SymbolTable& souffle::RAMIInterface::getSymbolTable () inline protected
Get symbol table.
Definition at line 123 of file RAMIInterface.h.
References getRelationMap(), souffle::RamTranslationUnit::getSymbolTable(), and translationUnit.
{
         return translationUnit.getSymbolTable();
     }
RamTranslationUnit& souffle::RAMIInterface::getTranslationUnit () inline
Get translation unit.
Definition at line 52 of file RAMIInterface.h.
References executeMain(), executeSubroutine(), and translationUnit.
{
         return translationUnit;
     }
const std::vector<void*>& souffle::RAMIInterface::loadDLL () inline protected
Load dll.
Definition at line 65 of file RAMIInterface.h.
References souffle::Global::config(), dll, and souffle::splitString().
Referenced by getMethodHandle().
{
         if (!dll.empty()) {
             return dll;
         }
         if (!Global::config().has("libraries")) {
             Global::config().set("libraries", "functors");
         }
         if (!Global::config().has("library-dir")) {
             Global::config().set("library-dir", ".");
         }
         for (const std::string& library : splitString(Global::config().get("libraries"), ' ')) {
             // The library may be blank
             if (library.empty()) {
                 continue;
             }
             auto paths = splitString(Global::config().get("library-dir"), ' ');
             // Set up our paths to have a library appended
             for (std::string& path : paths) {
                 if (path.back() != '/') {
                     path += '/';
                 }
             }
             if (library.find('/') != std::string::npos) {
                 paths.clear();
             }
             paths.push_back("");
             void* tmp = nullptr;
             for (const std::string& path : paths) {
                 std::string fullpath = path + "lib" + library + ".so";
                 tmp = dlopen(fullpath.c_str(), RTLD_LAZY);
                 if (tmp != nullptr) {
                     dll.push_back(tmp);
                     break;
                 }
             }
         }
         return dll;
     }
Field Documentation
std::vector<void*> souffle::RAMIInterface::dll protected
Dynamic library for user-defined functors.
Definition at line 137 of file RAMIInterface.h.
Referenced by loadDLL().
RamIndexAnalysis* souffle::RAMIInterface::isa protected
IndexAnalysis.
Definition at line 134 of file RAMIInterface.h.
Referenced by souffle::RAMI::evalCond(), souffle::RAMI::evalOp(), and souffle::RAMI::evalStmt().
friend souffle::RAMIInterface::RAMIProgInterface protected
Definition at line 120 of file RAMIInterface.h.
RamTranslationUnit& souffle::RAMIInterface::translationUnit protected
RAM translation Unit.
Definition at line 131 of file RAMIInterface.h.
Referenced by souffle::RAMI::executeMain(), souffle::RAMI::executeSubroutine(), souffle::RAMI::getSymbolTable(), getSymbolTable(), and getTranslationUnit().
The documentation for this class was generated from the following file:
RAMIInterface.h