souffle: souffle::RamNegation Class Reference
souffle::RamNegation Class Reference
Negates a given condition.
#include <RamCondition.h>
Public Member Functions
void apply (const RamNodeMapper &map) override
Apply the mapper to all child nodes.
RamNegation * clone () const override
Create a clone (i.e.
std::vector< const RamNode * > getChildNodes () const override
Obtain list of all embedded child nodes.
const RamCondition & getOperand () const
Get operand of negation.
void print (std::ostream &os) const override
Print RAM node.
RamNegation (std::unique_ptr< RamCondition > operand)
Public Member Functions inherited from souffle::RamNode
bool operator!= (const RamNode &other) const
Inequality check for two RAM nodes.
bool operator== (const RamNode &other) const
Equivalence check for two RAM nodes.
RamNode ()=default
virtual ~RamNode ()=default
Protected Member Functions
bool equal (const RamNode &node) const override
Equality check for two RAM nodes.
Protected Attributes
std::unique_ptr< RamCondition > operand
Operand.
Detailed Description
Negates a given condition.
For example:
(NOT t0 IN A)
Definition at line 162 of file RamCondition.h.
Constructor & Destructor Documentation
souffle::RamNegation::RamNegation (std::unique_ptr< RamCondition > operand) inline
Definition at line 164 of file RamCondition.h.
 : operand(std::move(operand)) {}
Member Function Documentation
void souffle::RamNegation::apply (const RamNodeMapper & mapper) inline override virtual
Apply the mapper to all child nodes.
Reimplemented from souffle::RamNode.
Definition at line 186 of file RamCondition.h.
{
         operand = map(std::move(operand));
     }
RamNegation* souffle::RamNegation::clone () const inline override virtual
Create a clone (i.e.
deep copy) of this node
Implements souffle::RamCondition.
Definition at line 182 of file RamCondition.h.
{
         return new RamNegation(std::unique_ptr<RamCondition>(operand->clone()));
     }
bool souffle::RamNegation::equal (const RamNode & other) const inline override protected virtual
Equality check for two RAM nodes.
Default action is that nothing needs to be checked.
Reimplemented from souffle::RamNode.
Definition at line 194 of file RamCondition.h.
References getOperand().
{
         assert(nullptr != dynamic_cast<const RamNegation*>(&node));
         const auto& other = static_cast<const RamNegation&>(node);
         return getOperand() == other.getOperand();
     }
std::vector<const RamNode*> souffle::RamNegation::getChildNodes () const inline override virtual
Obtain list of all embedded child nodes.
Reimplemented from souffle::RamNode.
Definition at line 178 of file RamCondition.h.
{
         return {operand.get()};
     }
const RamCondition& souffle::RamNegation::getOperand () const inline
Get operand of negation.
Definition at line 167 of file RamCondition.h.
Referenced by souffle::Synthesiser::emitCode(), equal(), souffle::RAMI::evalCond(), souffle::RamLevelAnalysis::getLevel(), and souffle::LVMGenerator::visitNegation().
{
         assert(nullptr != operand && "operand of negation is a null-pointer");
         return *operand;
     }
void souffle::RamNegation::print (std::ostream & out) const inline override virtual
Print RAM node.
Implements souffle::RamNode.
Definition at line 172 of file RamCondition.h.
{
         os << "(NOT ";
         operand->print(os);
         os << ")";
     }
Field Documentation
std::unique_ptr<RamCondition> souffle::RamNegation::operand protected
Operand.
Definition at line 192 of file RamCondition.h.
The documentation for this class was generated from the following file:
RamCondition.h