souffle: souffle::RamTupleElement Class Reference
souffle::RamTupleElement Class Reference
Access element from the current tuple in a tuple environment.
#include <RamExpression.h>
Public Member Functions
RamTupleElement * clone () const override
Create a clone (i.e.
size_t getElement () const
Get element.
int getTupleId () const
Get identifier.
void print (std::ostream &os) const override
Print RAM node.
RamTupleElement (size_t ident, size_t elem, std::unique_ptr< RamRelationReference > relRef=nullptr)
Public Member Functions inherited from souffle::RamNode
virtual void apply (const RamNodeMapper &mapper)
Apply the mapper to all child nodes.
virtual std::vector< const RamNode * > getChildNodes () const
Obtain list of all embedded child nodes.
bool operator!= (const RamNode &other) const
Inequality check for two RAM nodes.
bool operator== (const RamNode &other) const
Equivalence check for two RAM nodes.
RamNode ()=default
virtual ~RamNode ()=default
Protected Member Functions
bool equal (const RamNode &node) const override
Equality check for two RAM nodes.
Protected Attributes
const size_t element
Element number.
const size_t identifier
Identifier for the tuple.
Detailed Description
Access element from the current tuple in a tuple environment.
In the following example, the tuple element t0.1 is accessed:
IF t0.1 in A
    ...
Definition at line 205 of file RamExpression.h.
Constructor & Destructor Documentation
souffle::RamTupleElement::RamTupleElement (size_t ident, size_t elem, std::unique_ptr< RamRelationReference > relRef = nullptr) inline
Definition at line 207 of file RamExpression.h.
             : identifier(ident), element(elem) {}
Member Function Documentation
RamTupleElement* souffle::RamTupleElement::clone () const inline override virtual
Create a clone (i.e.
deep copy) of this node
Implements souffle::RamExpression.
Definition at line 224 of file RamExpression.h.
References souffle::identifier().
{
         return new RamTupleElement(identifier, element);
     }
bool souffle::RamTupleElement::equal (const RamNode & other) const inline override protected virtual
Equality check for two RAM nodes.
Default action is that nothing needs to be checked.
Reimplemented from souffle::RamNode.
Definition at line 235 of file RamExpression.h.
References getTupleId().
{
         assert(nullptr != dynamic_cast<const RamTupleElement*>(&node));
         const auto& other = static_cast<const RamTupleElement&>(node);
         return getTupleId() == other.getTupleId() && getElement() == other.getElement();
     }
size_t souffle::RamTupleElement::getElement () const inline
Get element.
Definition at line 220 of file RamExpression.h.
Referenced by souffle::Synthesiser::emitCode(), souffle::RAMI::evalExpr(), and souffle::LVMGenerator::visitTupleElement().
{
         return element;
     }
int souffle::RamTupleElement::getTupleId () const inline
Get identifier.
Definition at line 215 of file RamExpression.h.
References souffle::identifier().
Referenced by souffle::Synthesiser::emitCode(), equal(), souffle::RAMI::evalExpr(), souffle::RamLevelAnalysis::getLevel(), souffle::IfConversionTransformer::rewriteIndexScan(), souffle::ChoiceConversionTransformer::rewriteIndexScan(), souffle::ChoiceConversionTransformer::rewriteScan(), and souffle::LVMGenerator::visitTupleElement().
{
         return identifier;
     }
void souffle::RamTupleElement::print (std::ostream & out) const inline override virtual
Print RAM node.
Implements souffle::RamNode.
Definition at line 210 of file RamExpression.h.
References souffle::identifier().
{
         os << "t" << identifier << "." << element;
     }
Field Documentation
const size_t souffle::RamTupleElement::element protected
Element number.
Definition at line 233 of file RamExpression.h.
const size_t souffle::RamTupleElement::identifier protected
Identifier for the tuple.
Definition at line 230 of file RamExpression.h.
The documentation for this class was generated from the following file:
RamExpression.h