souffle: souffle::RamAbstractAggregate Class Reference
souffle::RamAbstractAggregate Class Reference
Abstract class for aggregation.
#include <RamOperation.h>
Public Member Functions
std::vector< const RamNode * > getChildNodes () const
const RamCondition & getCondition () const
Get condition.
const RamExpression & getExpression () const
Get target expression.
AggregateFunction getFunction () const
Get aggregation function.
void print (std::ostream &os, int tabpos) const
RamAbstractAggregate (AggregateFunction fun, std::unique_ptr< RamExpression > expression, std::unique_ptr< RamCondition > condition)
Protected Member Functions
bool equal (const RamNode &node) const
Protected Attributes
std::unique_ptr< RamCondition > condition
Aggregation tuple condition.
std::unique_ptr< RamExpression > expression
Aggregation expression.
AggregateFunction function
Aggregation function.
Detailed Description
Abstract class for aggregation.
A particular function (e.g. MIN) is applied given a that a condition holds
Definition at line 648 of file RamOperation.h.
Constructor & Destructor Documentation
souffle::RamAbstractAggregate::RamAbstractAggregate (AggregateFunction fun, std::unique_ptr< RamExpression > expression, std::unique_ptr< RamCondition > condition) inline
Definition at line 650 of file RamOperation.h.
             : function(fun), expression(std::move(expression)), condition(std::move(condition)) {}
Member Function Documentation
bool souffle::RamAbstractAggregate::equal (const RamNode & node) const inline protected
Definition at line 705 of file RamOperation.h.
References getCondition().
Referenced by souffle::RamAggregate::equal(), and souffle::RamIndexAggregate::equal().
{
         assert(nullptr != dynamic_cast<const RamAbstractAggregate*>(&node));
         const auto& other = dynamic_cast<const RamAbstractAggregate*>(&node);
         return getCondition() == other->getCondition() && getFunction() == other->getFunction() &&
                getExpression() == other->getExpression();
     }
std::vector<const RamNode*> souffle::RamAbstractAggregate::getChildNodes () const inline
Definition at line 671 of file RamOperation.h.
Referenced by souffle::RamAggregate::getChildNodes(), and souffle::RamIndexAggregate::getChildNodes().
{
         return {expression.get(), condition.get()};
     }
const RamCondition& souffle::RamAbstractAggregate::getCondition () const inline
Get condition.
Definition at line 655 of file RamOperation.h.
Referenced by souffle::Synthesiser::emitCode(), equal(), souffle::RAMI::evalOp(), souffle::RamLevelAnalysis::getLevel(), souffle::MakeIndexTransformer::rewriteAggregate(), souffle::LVMGenerator::visitAggregate(), and souffle::LVMGenerator::visitIndexAggregate().
{
         assert(condition != nullptr && "Condition of aggregate is a null-pointer");
         return *condition;
     }
const RamExpression& souffle::RamAbstractAggregate::getExpression () const inline
Get target expression.
Definition at line 666 of file RamOperation.h.
Referenced by souffle::Synthesiser::emitCode(), souffle::RAMI::evalOp(), souffle::RamLevelAnalysis::getLevel(), souffle::MakeIndexTransformer::rewriteAggregate(), souffle::LVMGenerator::visitAggregate(), and souffle::LVMGenerator::visitIndexAggregate().
{
         assert(expression != nullptr && "Expression of aggregate is a null-pointer");
         return *expression;
     }
AggregateFunction souffle::RamAbstractAggregate::getFunction () const inline
Get aggregation function.
Definition at line 661 of file RamOperation.h.
Referenced by souffle::Synthesiser::emitCode(), souffle::RAMI::evalOp(), souffle::MakeIndexTransformer::rewriteAggregate(), souffle::LVMGenerator::visitAggregate(), and souffle::LVMGenerator::visitIndexAggregate().
{
         return function;
     }
void souffle::RamAbstractAggregate::print (std::ostream & os, int tabpos) const inline
Definition at line 675 of file RamOperation.h.
References souffle::COUNT, souffle::MAX, and souffle::MIN.
Referenced by souffle::RamAggregate::print(), and souffle::RamIndexAggregate::print().
{
         switch (function) {
             case MIN:
                 os << "MIN ";
                 break;
             case MAX:
                 os << "MAX ";
                 break;
             case COUNT:
                 os << "COUNT ";
                 break;
             case SUM:
                 os << "SUM ";
                 break;
         }
         if (function != COUNT) {
             os << *expression << " ";
         }
     }
Field Documentation
std::unique_ptr<RamCondition> souffle::RamAbstractAggregate::condition protected
Aggregation tuple condition.
Definition at line 703 of file RamOperation.h.
std::unique_ptr<RamExpression> souffle::RamAbstractAggregate::expression protected
Aggregation expression.
Definition at line 700 of file RamOperation.h.
AggregateFunction souffle::RamAbstractAggregate::function protected
Aggregation function.
Definition at line 697 of file RamOperation.h.
The documentation for this class was generated from the following file:
RamOperation.h