souffle: souffle::RamRelationStatement Class Reference
souffle::RamRelationStatement Class Reference
RAM Statements with a single relation.
#include <RamStatement.h>
Public Member Functions
void apply (const RamNodeMapper &map) override
Apply the mapper to all child nodes.
std::vector< const RamNode * > getChildNodes () const override
Obtain list of all embedded child nodes.
const RamRelation & getRelation () const
Get RAM relation.
RamRelationStatement (std::unique_ptr< RamRelationReference > relRef)
Public Member Functions inherited from souffle::RamStatement
RamStatement * clone () const override=0
Create a clone (i.e.
virtual void print (std::ostream &os, int tabpos) const =0
Pretty print with indentation.
void print (std::ostream &os) const override
Print RAM node.
Public Member Functions inherited from souffle::RamNode
bool operator!= (const RamNode &other) const
Inequality check for two RAM nodes.
bool operator== (const RamNode &other) const
Equivalence check for two RAM nodes.
RamNode ()=default
virtual ~RamNode ()=default
Protected Member Functions
bool equal (const RamNode &node) const override
Equality check for two RAM nodes.
Protected Attributes
std::unique_ptr< RamRelationReference > relationRef
Relation.
Detailed Description
RAM Statements with a single relation.
Definition at line 55 of file RamStatement.h.
Constructor & Destructor Documentation
souffle::RamRelationStatement::RamRelationStatement (std::unique_ptr< RamRelationReference > relRef) inline
Definition at line 57 of file RamStatement.h.
 : relationRef(std::move(relRef)) {}
Member Function Documentation
void souffle::RamRelationStatement::apply (const RamNodeMapper & mapper) inline override virtual
Apply the mapper to all child nodes.
Reimplemented from souffle::RamNode.
Reimplemented in souffle::RamLogRelationTimer, and souffle::RamFact.
Definition at line 69 of file RamStatement.h.
Referenced by souffle::RamFact::apply(), and souffle::RamLogRelationTimer::apply().
{
         relationRef = map(std::move(relationRef));
     }
bool souffle::RamRelationStatement::equal (const RamNode & other) const inline override protected virtual
Equality check for two RAM nodes.
Default action is that nothing needs to be checked.
Reimplemented from souffle::RamNode.
Reimplemented in souffle::RamLogSize, souffle::RamLogRelationTimer, souffle::RamFact, souffle::RamStore, souffle::RamLoad, and souffle::RamAbstractLoadStore.
Definition at line 77 of file RamStatement.h.
References getRelation().
Referenced by souffle::RamAbstractLoadStore::equal(), souffle::RamFact::equal(), souffle::RamLogRelationTimer::equal(), and souffle::RamLogSize::equal().
{
         assert(nullptr != dynamic_cast<const RamRelationStatement*>(&node));
         const auto& other = static_cast<const RamRelationStatement&>(node);
         return getRelation() == other.getRelation();
     }
std::vector<const RamNode*> souffle::RamRelationStatement::getChildNodes () const inline override virtual
Obtain list of all embedded child nodes.
Reimplemented from souffle::RamNode.
Reimplemented in souffle::RamLogRelationTimer, and souffle::RamFact.
Definition at line 65 of file RamStatement.h.
Referenced by souffle::RamFact::getChildNodes(), and souffle::RamLogRelationTimer::getChildNodes().
{
         return {relationRef.get()};
     }
const RamRelation& souffle::RamRelationStatement::getRelation () const inline
Get RAM relation.
Definition at line 60 of file RamStatement.h.
Referenced by souffle::Synthesiser::emitCode(), equal(), souffle::RAMI::evalStmt(), souffle::RAMI::executeMain(), souffle::LVM::executeMain(), souffle::Synthesiser::generateCode(), souffle::LVMProgInterface::LVMProgInterface(), souffle::RAMIProgInterface::RAMIProgInterface(), souffle::LVMGenerator::visitClear(), souffle::LVMGenerator::visitCreate(), souffle::LVMGenerator::visitDrop(), souffle::LVMGenerator::visitFact(), souffle::LVMGenerator::visitLoad(), souffle::LVMGenerator::visitLogRelationTimer(), souffle::LVMGenerator::visitLogSize(), and souffle::LVMGenerator::visitStore().
{
         assert(relationRef != nullptr && "Relation reference is a null-pointer");
         return *relationRef->get();
     }
Field Documentation
std::unique_ptr<RamRelationReference> souffle::RamRelationStatement::relationRef protected
Relation.
Definition at line 75 of file RamStatement.h.
The documentation for this class was generated from the following file:
RamStatement.h