souffle: souffle::Order Class Reference
souffle::Order Class Reference
An order to be enforced for storing tuples within indexes.
#include <LVMIndex.h>
Public Member Functions
template<std::size_t Arity>
ram::Tuple< RamDomain, Arity > decode (const ram::Tuple< RamDomain, Arity > &entry) const
template<std::size_t Arity>
ram::Tuple< RamDomain, Arity > encode (const ram::Tuple< RamDomain, Arity > &entry) const
const std::vector< int > & getOrder () const
bool operator!= (const Order &other) const
bool operator< (const Order &other) const
bool operator== (const Order &other) const
template<typename... Positions>
Order (Positions...pos)
std::size_t size () const
bool valid () const
Determines whether this order is a valid order.
Static Public Member Functions
static Order create (size_t arity)
Private Attributes
std::vector< int > order
Friends
std::ostream & operator<< (std::ostream &out, const Order &order)
Detailed Description
An order to be enforced for storing tuples within indexes.
The order is defined by the sequence of component to be considered in sorting tuples.
Definition at line 132 of file LVMIndex.h.
Constructor & Destructor Documentation
template<typename... Positions> souffle::Order::Order (Positions... pos) inline
Definition at line 137 of file LVMIndex.h.
                             : order{pos...} {
         assert(valid());
     }
Member Function Documentation
Order souffle::Order::create (size_t arity) static
Definition at line 33 of file LVMIndex.cpp.
References arity, i, and order.
{
     Order res;
     res.order.resize(arity);
     for (size_t i = 0; i < arity; i++) {
         res.order[i] = i;
     }
     return res;
 }
template<std::size_t Arity> ram::Tuple<RamDomain, Arity> souffle::Order::decode (const ram::Tuple< RamDomain, Arity > & entry) const inline
Definition at line 161 of file LVMIndex.h.
References i.
Referenced by souffle::GenericIndex< Structure >::Source::load().
{
         ram::Tuple<RamDomain, Arity> res;
         for (std::size_t i = 0; i < Arity; ++i) {
             res[order[i]] = entry[i];
         }
         return res;
     }
template<std::size_t Arity> ram::Tuple<RamDomain, Arity> souffle::Order::encode (const ram::Tuple< RamDomain, Arity > & entry) const inline
Definition at line 152 of file LVMIndex.h.
References i.
Referenced by souffle::GenericIndex< btree_set< ram::Tuple< RamDomain, Arity >, comparator< Arity > > >::contains(), souffle::GenericIndex< btree_set< ram::Tuple< RamDomain, Arity >, comparator< Arity > > >::insert(), and souffle::GenericIndex< btree_set< ram::Tuple< RamDomain, Arity >, comparator< Arity > > >::range().
{
         ram::Tuple<RamDomain, Arity> res;
         for (std::size_t i = 0; i < Arity; ++i) {
             res[i] = entry[order[i]];
         }
         return res;
     }
const std::vector<int>& souffle::Order::getOrder () const inline
Definition at line 169 of file LVMIndex.h.
References souffle::operator<<().
Referenced by souffle::createIndirectIndex().
{
         return this->order;
     }
bool souffle::Order::operator!= (const Order & other) const
Definition at line 68 of file LVMIndex.cpp.
{
     return !(*this == other);
 }
bool souffle::Order::operator< (const Order & other) const
Definition at line 72 of file LVMIndex.cpp.
References order.
{
     return order < other.order;
 }
bool souffle::Order::operator== (const Order & other) const
Definition at line 64 of file LVMIndex.cpp.
References order.
{
     return order == other.order;
 }
std::size_t souffle::Order::size () const
Definition at line 42 of file LVMIndex.cpp.
References order.
Referenced by souffle::createBrieIndex(), souffle::createBTreeIndex(), and souffle::createIndirectIndex().
{
     return order.size();
 }
bool souffle::Order::valid () const
Determines whether this order is a valid order.
Definition at line 46 of file LVMIndex.cpp.
References i, j, and order.
{
     // Check that all indices are in range.
     for (int i : order) {
         if (i < 0 || i >= int(order.size())) {
             return false;
         }
     }
     // Check that there are no duplicates.
     for (std::size_t i = 0; i < order.size(); i++) {
         for (std::size_t j = i + 1; j < order.size(); j++) {
             if (order[i] == order[j]) {
                 return false;
             }
         }
     }
     return true;
 }
Friends And Related Function Documentation
std::ostream& operator<< (std::ostream & out, const Order & order) friend
Definition at line 76 of file LVMIndex.cpp.
{
     return out << "[" << join(order.order) << "]";
 }
Field Documentation
std::vector<int> souffle::Order::order private
Definition at line 133 of file LVMIndex.h.
Referenced by create(), souffle::createBrieIndex(), souffle::createBTreeIndex(), operator<(), souffle::operator<<(), operator==(), souffle::GenericIndex< btree_set< ram::Tuple< RamDomain, Arity >, comparator< Arity > > >::range(), souffle::GenericIndex< btree_set< ram::Tuple< RamDomain, Arity >, comparator< Arity > > >::scan(), size(), and valid().
The documentation for this class was generated from the following files:
LVMIndex.h
LVMIndex.cpp